README.md
deploy/role_binding.yaml

Update the README with instructions for setting up the controller in a
dev environment using minishift.
Update the role binding YAML file to allow a developer to run the
controller from outside the cluster. We will likely want to do
something different when we get to really packaging this for
deployment.
Signed-off-by: Doug Hellmann <doug@doughellmann.com>

add instructions for running against minishift

---

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/controller/baremetalhost/baremetalhost_controller.go

Instead of expecting users of the BareMetalHost to understand how to
fetch the status from the label, add a method.

add a method to host to retrieve the operational status

---

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/apis/metalkube/v1alpha1/zz_generated.deepcopy.go

When specified, the MachineRef will indicate that a host should be provisioned
and added to the cluster as a Node by way of the specified Machine.

adds Machine reference to spec

---

build/Dockerfile

Switch to using the openshift base image.
Add a build step.

fix up docker file

---

deploy/operator.yaml

The Dockerfile installs the operator to / and without the explicit
prefix in the command in the deployment settings the executable can't
be found and the pod fails to launch.

fix the command in the deployment instructions

---

docs/dev-setup.md

The build needs the operator-sdk so make sure we mention it.

mention operator-sdk in setup instructions

---

deploy/crds/metalkube_v1alpha1_baremetalhost_cr.yaml
docs/api.md
pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/bmc/credentials.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go
test/e2e/baremetal_test.go

This changes IP to Address with the assumption that it will hold a URL.
fixes #27

rename IP field of BareMetalHost.BMC to Address

---

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go

Opening this to start a discussion: are these the right fields?
I was going by the wireframes which are in turn based on the kubevirt CRD.
Once we are happy with the fields, I will also update the defaults.

Add fields to NIC and Storage types

---

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go

Add a field in the spec to hold the image to be provisioned and
another in the provision status block to hold the URL of the image
that was provisioned so we can detect a change.
See https://github.com/metalkube/metalkube-docs/pull/16 for more
details.

add fields to hold image URL

---

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/provisioner/fixture/fixture.go

Instead of using the provisioning state field, use a separate field.

save power status to its own variable

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

Update the Provisioner API so that all of the potentially multi-step
operations return the same Result type with instructions for the
caller about whether to store the host and how long to wait before
retrying the call.

add result type for provisioner API responses

---

pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/ipmi.go
pkg/provisioner/ironic/ironic.go

Rather than having methods with lots of if-then statements, define an
interface so we can have multiple implementations and just select the
right one in NewAccessDetails().

create AccessDetails interface

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go

We may not need it at all and for now it interferes with testing
provisioning.

turn off power management sections of reconcile

---

pkg/controller/baremetalhost/baremetalhost_controller_test.go

Sometimes the result from a step is a request to requeue after a
delay. In those cases, the Requeue flag is not set but the
RequeueAfter value is non-zero.

update test wait loop to look for delayed requeue

---

docs/dev-setup.md
pkg/controller/baremetalhost/baremetalhost_controller.go

The UX team needs a way to run the operator without the full
provisioning environment. This switch lets them have a provisioner
that does properly set up the host objects, and does not require
ironic.

add -test-mode command line flag

---

cmd/make-worker/main.go
docs/dev-setup.md

Add a utility to generate the YAML for registering a host by querying
the virsh and vbmc settings.

command to build worker file from virsh domain

---

pkg/controller/baremetalhost/baremetalhost_controller.go

The instance information comes from the actuator now, so these consts
are not needed.

remove some consts that are no longer needed

---

docs/dev-setup.md

Link to the vbmc docs using markdown syntax instead of restructuredtext.

use markdown syntax for links

---

cmd/make-worker/main.go
pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go

This PR includes a couple of related changes to clean up the way we handle status values that we were storing in labels but that we want to store in the status fields instead.

stop using labels for status values

---

Makefile
cmd/manager/main.go

Add "make run" target to simplify running the operator locally.
Add a -dev switch to turn on "development mode", which changes the
logging format to something a little easier for a human to parse.

dev mode enhancements

---

cmd/make-worker/main.go

instanceImageSource is constant and can be used within
templates' declaration.

Don't hardcode instanceImageSource into templateBody

---

docs/dev-setup.md

In order to make the docs less specific to OpenShift, convert the
instructions based on minishift to use minikube instead.  The
instructions remain very similar.

dev-setup: Use minikube instead of minishift.

---

pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/idrac.go
pkg/bmc/ipmi.go
pkg/provisioner/ironic/ironic.go

When the BMC address is of the form idrac://... the iDRAC driver in
Ironic will be used instead of the default IPMI driver.

Add iDRAC support

---

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go

When we discover a host from scanning Ironic's database, we will not
have BMC addresses or credentials. That is not an error, it is just an
incompletely registered host, so add a special state so the UI can
detect the special case.

add a "discovered" state for hosts

---

cmd/make-worker/main.go

Template wasn't update to reflect changes in commit: e21971636a6
which results in error:
unknown field 'ImageSourceUrl' in struct literal of type TemplateArgs

Add ImageSourceUrl to TemplateArgs template.

---

cmd/make-worker/main.go
docs/api.md
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go

The unit tests for the actuator are failing because we require it to
provide a full checksum for the image being provisioned. This will
allow it to just pass us the URL, and have the operator download it to
learn the checksum from there. Eventually we can just pass the URL to
ironic and let it do the download, but we have to upgrade to a newer
ironic for that.

let the baremetal operator download the checksum from a URL

---

docs/api.md
pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/idrac.go

Support `idrac+https://` and `ipmi:` without the `//`, and document the allowed URL types in the API docs.

Improve and document bmc.address URL support

---

Makefile
pkg/bmc/access_test.go

go vet is apparently pickier than golint

add 'go vet' to 'make lint' commands

---

pkg/controller/baremetalhost/baremetalhost_controller_test.go

Hosts need a unique name to avoid reporting errors when events are
created.

give each test host a unique name

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

Regularly check the power status of the host to ensure it matches the
desired state.

add active power state monitoring

---

docs/api.md
pkg/bmc/access_test.go
pkg/bmc/idrac.go

The `drac_address` is not actually a URL as [previously indicated](https://review.openstack.org/648493) in the Ironic docs. Rather, it is just the hostname and the other components of the URL can optionally be passed as `drac_protocol`, `drac_port`, and `drac_path`.

Fix idrac driver_info format

---

docs/dev-setup.md

In the minikube section of the docs, the final step of creating a CR
references a file that no longer exists. Point it to example-host.yaml
instead.

Fix CR reference in the docs

---

pkg/provisioner/ironic/ironic.go

Fill in the instance UUID in ironic when we start provisioning so that
ironic will monitor the status of the host regularly.

set instance uuid

---

Makefile
deploy/crds/demo-hosts.yaml
pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go
tools/clean_demo_hosts.sh
tools/show_host_status.sh

This change should make tracking "activity" more consistent because it all happens in 1 field. The main status field is then left for tracking whether a host is OK or not. Note that only the most recent patch in the series is part of this PR. The others are from #100, on which this is based.

Move inspecting status location

---

Makefile
deploy/crds/demo-hosts.yaml
pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go
tools/clean_demo_hosts.sh
tools/show_host_status.sh

In the course of building this demo provisioner, I found some additional ways to clean up the controller logic for error handling. I have prepared separate patches in a series so they are easier to review.

Demo provisioner and controller logic cleanup

---

deploy/crds/demo-hosts.yaml
tools/clean_demo_hosts.sh

Instead of relying on the names of the hosts, add a label that we can
use in the cleanup script to find them again.

label all demo hosts for more robust cleanup

---

pkg/controller/baremetalhost/baremetalhost_controller.go

This is an attempt to restructure the Reconcile() method based on a series of phases so we can add consistent handling for the need to save data or report errors. I have it split up into separate commits to make reviews easier, and the tests all worked at each commit point.

Split Reconcile() into phases

---

pkg/controller/baremetalhost/baremetalhost_controller.go

The BMC credentials can be changed over time, so track successful
updates using operational events.

publish event when the BMC access can be verified

---

pkg/controller/baremetalhost/baremetalhost_controller.go

When the hardware profile is set, include the name in the event
published to the object.

include the name of the hardware profile in the event title

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

Rather than fetch the user data every time we reconcile the host
during provisioning, use a callback to allow the provisioner to
request the data when it is actually needed.

move user data fetching into a callback

---

pkg/controller/baremetalhost/baremetalhost_controller.go

Only publish operational events after we have successfully stored the new status for the host object. This avoids situations where we can publish an event but then not store the host, causing another event to be published the next time we reconcile.

Delay event publishing

---

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

Define a type to constraint the values for the provisioning state
field. In order to use the type in the host API and provisioner, we
have to define it in the host API module to avoid a circular reference
between the two modules.

define type for provisioning state values

---

deploy/operator.yaml

The baremetal-operator is written against the design of having Ironic
running within the same pod and accessible by localhost.  That isn't
working yet, so update the pod deployment yaml to show how to proxy to
an external Ironic for now.

deploy: Add temporary ironic proxy container.

---

deploy/crds/metalkube_v1alpha1_baremetalhost_crd.yaml

Add a few columns with useful details about the host so that 'oc get'
or 'kubectl get' will report more than the name and age.

add printer columns to the CRD

---

pkg/provisioner/ironic/ironic.go

When we register masters while we're still talking to the provisioning
host's ironic instance they will be "active" because ironic knows the
image it provisioned to them.

allow registering active nodes

---

cmd/make-virt-host/main.go
deploy/crds/demo-hosts.yaml
deploy/crds/worker-0.yaml
docs/api.md

The image changed name in dev-scripts, so we need to update
this to match.
Co-Authored-By: Russell Bryant <rbryant@redhat.com>

Update image references to oopta image

---

docs/dev-setup.md
tools/run_local_ironic.sh

Ironic should eventually run in the baremetal-operator pod.  Right now
our sample pod yaml includes a sidecar proxy container that redirects
connections to the expected local Ironic to an Ironic running
elsewhere.
This script runs a set of containers for Ironic built from metalkube
repos.  It's useful for development environments until we move these
containers into the cluster properly.
This is copied from a repo of scripts where a group is workgin on
metalkube integration with OpenShift, but with the OpenShift specifics
removed and made more generally useful.
The original script was here:
https://github.com/openshift-metalkube/dev-scripts/blob/master/04_setup_ironic.sh

Add script to run a local Ironic for development.

---

cmd/make-bm-worker/main.go

Commit https://github.com/openshift-metalkube/dev-scripts/commit/470a7bcbdc76db9ac7e9cf4086db79b418215fcf#diff-6aaa4e12b6fddc1b93b9ee994b50a49b introduced
ability to register both master and worker nodes.
This change brings in custom changes to make-bm-worker utility
to the BMO's repo.

Align make-bm-worker with dev-script's version

---

deploy/crds/metalkube_v1alpha1_baremetalhost_crd.yaml
pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/hardware/profile.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go

Add some temporarily hacky logic to guess the hardware profile so we
can get a root device. The real profile will eventually come from
matching inspected inventory, when we implement that. In the mean
time, use the BMC type to detect virt vs. physical, and provide a
field in the host spec to override the guess of a profile if we get it
wrong.
Also rewrite the logic for setting individual host and image
properties so they are all checked and added or updated as required.

use the hardware profile to configure ironic to provision correctly

---

pkg/controller/baremetalhost/baremetalhost_controller.go

If a host fails registration with the same error message a second
time, that means we have reconciled it twice with the same data and it
still does not work. Rather than keep trying, which toggles the host
between "registering" and "registration error" indefinitely, leave the
host in the "registration error" state.

make registration error a steady state

---

docs/api.md
pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
pkg/apis/metalkube/v1alpha1/baremetalhost_types_test.go

Previously to change the provisioned image, you would have to first set
the image URL to "" and wait for deprovisioning to complete before
reprovisioning with a new image URL. With this change, a change to the
image URL will cause the server to be deprovisioned and reprovisioned
with the new image.

Support changing the provisioned image

---

Makefile
pkg/provisioner/ironic/ironic.go

Apparently make passes the quotes through as part of the value of the
variable, which then causes problems when we try to use the URLs. So,
remove the quotes.
Also adds 1 log call to show which values are going to be used when
the ironic provisioner is created.

remove quotes from env vars in makefile

---

pkg/provisioner/ironic/ironic.go

Logging is not configured when init() is running, so using the log API
to report errors means they are not output at all. Switch to simple
print statements.

switch startup error reporting to Fprintf()

---

pkg/bmc/access.go
pkg/bmc/credentials.go
pkg/bmc/credentials_test.go
pkg/bmc/errors.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go
pkg/controller/baremetalhost/errors.go

This pull request refactors the error handling for many `Reconcile` BMC operations and introduces a few strongly typed errors for both the `bmc` and the `baremetalhost` packages.  I hope this type of error typing is continued.  It is heavily based on the feedback in the now closed [PR#135](https://github.com/metalkube/baremetal-operator/pull/135) and attempts to incorporate the feedback there and I hopefully satisfies many of the requests.
This also closes [Issue#126](https://github.com/metalkube/baremetal-operator/issues/126)  as missing secrets should no longer result in tracebacks.
Closes: #126

Refactor Reconciler BMC Error Handling

---

build/Dockerfile
cmd/manager/main.go
deploy/operator.yaml
docs/dev-setup.md
docs/publishing-images.md
pkg/apis/addtoscheme_metalkube_v1alpha1.go
pkg/controller/add_baremetalhost.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go
pkg/controller/baremetalhost/demo_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go
pkg/provisioner/provisioner.go
test/e2e/baremetal_test.go

This change is part of renaming metalkube to metal3. We have renamed
the git repository, so in order to build this repo in its new location
it needs to have the imports updated. We do not want the full rename
in this branch, though, to minimize changes in a "stable" branch.

rename git repository in metalkube branch

---

docs/dev-setup.md

When we try to bring **baremetal-operator** up via **operator-sdk** CLI, it raises an error due to the missing of some environment variables to tell it where ironic is. This PR aims to update the doc by including these env variables.

Update dev documents by adding required env variables

---

pkg/hardware/profile.go

Someone reported trying to deploy a host where the root disk needed to
be 0:2:0:0.  Add another built in profile for this.

Add a dell-raid profile.

---

Makefile
deploy/operator.yaml
docs/configuration.md
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

Note that https://github.com/metalkube/baremetal-operator/commit/fb54f2943004e7364cffd1f438768462adb1192e is a fix to the vendored gophercloud that is awaiting upstream acceptance in https://github.com/gophercloud/gophercloud/pull/1548

Add hardware introspection support using ironic-inspector

---

Makefile
cmd/make-bm-worker/main.go
cmd/make-bm-worker/templates/templates.go
cmd/make-bm-worker/templates/templates_test.go

Add unit tests for the template rendering in make-bm-worker.
In the process, restructure the code so it is testable and so the
template type does not need the separate boolean fields and so the
caller does not need to provide username and password as base64
encoded values.
Fixes #160

add tests for make-bm-worker

---

pkg/hardware/profile.go

Someone reported trying to deploy a host where the root disk needed to
be 0:2:0:0.  Add another built in profile for this.

[metalkube] Add a dell-raid profile.

---

docs/dev-setup.md

The operator did not load until I exported  IRONIC_INSPECTOR_ENDPOINT to fix
INFO[0000] Running the operator locally.
INFO[0000] Using namespace metal3.
Cannot start: No IRONIC_INSPECTOR_ENDPOINT variable setError: failed to run operator locally:
(failed to exec []string{"build/_output/bin/baremetal-operator-local"}: exit status 1)

Adding IRONIC_INSPECTOR_ENDPOINT

---

pkg/provisioner/ironic/ironic.go

cloud-init requires that the meta_data.json file exists and that it
contains at least the uuid key.  Add this to make provisioning of
cloud-init based images work and read user_data from the config drive.

Make userdata work with cloud-init images.

---

pkg/provisioner/ironic/ironic.go

This allows nodes to be deleted when the IPMI details are wrong,
otherwise you can get stuck with an undeletable BaremetalHost.
Closes: #170

Handle enroll/verifying states on node delete

---

pkg/provisioner/ironic/ironic.go

cloud-init requires that the meta_data.json file exists and that it
contains at least the uuid key.  Add this to make provisioning of
cloud-init based images work and read user_data from the config drive.

[metalkube] Make userdata work with cloud-init images.

---

docs/api.md
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
test/e2e/baremetal_test.go

It looks like there are some remnants from "stop using labels for status values" in #78

Operational status cleanups

---

tools/show_host_status.sh

Not needed anymore now that the CRD includes printer columns.

Remove tools/show_host_status.sh

---

tools/run_local_ironic.sh

Podman is trying to pull image with tag latest but there is no this tag at this moment here: https://quay.io/repository/metal3-io/ironic?tag=latest&tab=tags. Only **master** and **no-cleaning** are available.
This PR also configure a shared folder for ironic-inspector container

Update Ironic image tag and Ironic-inspector shared folder

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go
pkg/provisioner/fixture/fixture.go

This change fixes a bug in which an existing host could be updated to have
bad credentials and then that mistake could be corrected but the host
status would not be fixed. Always clear any existing error messages when
the credentials are recognized as changed and good.
Also adds a unit test for that case.
Fixes #195

clear error when credentials are recognized as good

---

pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/idrac.go
pkg/bmc/ipmi.go
pkg/provisioner/ironic/ironic.go

Currently boot interface is hard-code of 'ipxe'. This patch allows
boot interface to be set by vendor driver.
#230 
Signed-off-by: Dao Cong Tien <tiendc@vn.fujitsu.com>

Allows boot interface to be customizable

---

Makefile
cmd/make-virt-host/main.go
pkg/provisioner/ironic/ironic.go

gosec does static code analysis and checks for common security issues in golang codebases.
This PR introduces the tool, and sets it up as a test target in the Makefile; it also ignores a couple of warnings that were found which are probably not very problematic.

 Introduce gosec for security checks

---

cmd/manager/main.go

This patch configures a prometheus metrics endpoint for the
baremetal-operator.  The metrics endpoint only listens on localhost by
default, but this can be configured through a command line argument.
This can be tested with `make run` and then run the following command:
$ curl http://localhost:8080/metrics
Closes #245

Configure metrics endpoint.

---

cmd/manager/main.go

In the OpenShift integrated case this conflicts with coredns which binds
to :::8080, switching to 8085 should avoid this conflict with the
default.
Fixes: #252

Avoid port conflict for metrics endpoint

---

Gopkg.lock
Gopkg.toml
vendor/github.com/gophercloud/gophercloud/acceptance/openstack/compute/v2/compute.go
vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/results.go
vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/testing/fixtures.go
vendor/github.com/gophercloud/gophercloud/openstack/baremetal/apiversions/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/microversions.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/results.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/testing/fixtures.go

This change pulls includes:
- Improvement: return versions supported by the API
- Bug fix: Reformat Args in CleanStep from `map[string]string` to `map[string]interface{}`

Update to latest gophercloud revision

---

pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go

Introduce handling of the gophercloud's Firmware ExtraHardwareDataSection.  
Today, this only includes known BIOS fields.  If we are able to determine all likely data potentially within the Firmware section we can expand the data and fields handled.
Resolves: #220

Persist firmware and bios data during introspection.

---

deploy/operator_ironic.yaml

I don't think this file is being used but we
should probably reference the current names.

Reference the current ironic images

---

.travis.yml
Makefile

This enables gosec to run as part of the lint target, therefore running
it as well as part of CI.
This also adds the needed command to install it as part of the CI run.

Run gosec with lint target

---

pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
pkg/provisioner/ironic/ironic.go

Using the presence of a consumerRef value to indicate that a host is
in use means we have a race condition when a host is first registered
if the machine controller grabs the host and allocates it to a
machine before the host has finished inspection. To avoid the race,
use the WasProvisioned() function to test whether a host has actually
been provisioned instead of looking only at the consumer reference.
This update requires changing the expected behavior in an existing
unit test (because it was wrong) and adding a new unit test for the
new case.

only skip inspection for fully provisioned hosts

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/ironic/ironic.go

Instead of logging all of the ironic settings every time the
reconciler builds a provisioner, log them once on startup.
We don't use the init() function for this because logging isn't
configured yet by the time that is called.

move ironic settings logging to startup function

---

pkg/provisioner/ironic/ironic.go

When the host is in certain provisioning states we cannot change its
power status. Rather than erroring and trying over and over, report
the issue and delay retrying to give the host a chance to move into a
state where power can be changed.

improve error handling in power state management code

---

pkg/bmc/access.go
pkg/bmc/idrac.go
pkg/bmc/ipmi.go
pkg/bmc/irmc.go

Instead of hard-coding the creation of the AccessDetails structs in
one function, register the factories for making different types and
associate them with the values that show up in the URL scheme field to
select them.

use a registry to make access details type management more dynamic

---

pkg/provisioner/ironic/ironic.go

The adoption flow logs a message that it is waiting for adoption to
complete, even when no adoption is actually happening. Remove the log
message entirely to avoid cluttering the logs and confusing users.

remove debugging log statement in adoption

---

pkg/provisioner/ironic/ironic.go

When attempting to power a host on or off with Ironic, we were declaring
success (updating the power status and dropping back to polling only
every 60s) as soon as we saw the target power state change in Ironic
even if the host had not yet reached that state.
Ensure that the power state has actually changed before we consider the
change complete.
Fixes #290

Wait for power status to change

---

pkg/bmc/access_test.go

Convert the separate test functions for parsing BMC URLs to a table
test to cut down on the repetition.

simplify bmc access tests

---

pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/idrac.go
pkg/bmc/ipmi.go
pkg/bmc/irmc.go

This enhancements changes the BMC drivers factory method to accept a url.URL object instead of separate string arguments, allowing more flexibility in passing information to the BMC drivers.

Modify BMC drivers to handle url.URL instead of separate arguments and refactor BMC tests

---

docs/api.md
pkg/bmc/access_test.go
pkg/bmc/redfish.go

accepts bmc address like
`redfish+https://my.host:8080/redfish/v1/Systems/MySystem`

Add redfish BMC support in baremetal operator

---

docs/dev-setup.md

Example host should be created in namespace metal3 because it is the namespace the operator is watching for changes.

Fix doc of setting up development env with minikube

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/provisioner/ironic/ironic.go

When we get an HTTP 409 response in ValidateManagementAccess, we should
retry after a delay. In one case we were not delaying (i.e. retrying
immediately), and in another we added a delay before moving to the next
state but reported that the management access was valid when that had
not been verified.
Handle both with a retry after a delay.
Since this was the only case where the provisioner would request a delay
while reporting success, this also removes the code handling that case
in actionRegistering(). Once the host is registered we always want to
requeue immediately so we can move to the next state.

Handle conflicts consistently in ValidateManagementAccess()

---

.travis.yml
Makefile

Instead of telling users to install gosec without saying how, this will
do it for them. I didn't have gosec installed and had to google to find
the full name of the package. Saves future developers a few seconds.

Install gosec and golint in Makefile if needed

---

pkg/controller/baremetalhost/baremetalhost_controller.go

When an error occurred during inspection, we weren't setting the Requeue
flag, which is required for the event to actually be published and the
CR to be updated (although it doesn't actually cause the reconcile to be
requeued, because of the error).
Had we published the event, it would have wrongly stated that it was a
registration error.
Finally, we weren't actually changing the Host's ProvisionState to
RegistrationError (since changes weren't written), so don't start now.

Set error message on inspection error 

---

pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go

Previously when checking if a Secret has changed we could have confused
two Secrets with the same name in different namespaces.

Check namespace when matching Secret references

---

Makefile
deploy/ironic_bmo_configmap.yaml
deploy/mariadb-password.yaml
deploy/operator_ironic.yaml

This creates a mariadb scret, deploys the bmo configmap, and creates the
IPA downloader as an init container.

Update ironic deployment to latest requirements

---

docs/api.md

After our chat over email (@hardys) , I'm sending this PR that adds:
* diagram in SVG for future modifications
* diagram in PNG for linking
* Markdown document with the explanation and showing the diagram
I could also provide the original Google Drawing if that's preferred over the SVG.
Let me know if anything would need amending or changed completely :nerd_face: 
**UPDATE**:
* Tried to merge both api.md and my previous addition
* Add missing or erroneous fields
* Add a complete example of the BareMetalHost resource

doc: add more literature to api doc

---

deploy/crds/metal3_v1alpha1_baremetalhost_crd.yaml
pkg/apis/metal3/v1alpha1/baremetalhost_types.go

The status fields for tracking credentials will be empty when the host
is created, so make them optional.

make the credential tracking fields optional

---

docs/api.md
docs/baremetalhost-states.md
docs/dev-setup.md
docs/publishing-images.md
docs/testing.md
hack/gofmt.sh
hack/gosec.sh
hack/govet.sh
hack/markdownlint.sh
hack/shellcheck.sh
hack/unit.sh
pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/idrac.go
pkg/bmc/redfish.go
tools/clean_host.sh
tools/run_local_ironic.sh

This PR adds a series of scripts in the hack/ directory that can be used to run various tests or linters in containers.  The scripts can be run directly, and they'll launch a container env to run the test in.  When the scripts are run from prow, prow will run this script in a Pod, using the same image that the script is using.
This same pattern is being used in capbm and metal3-dev-env.

Add a set of hack scripts and fix corresponding warnings

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go

The Stein version of Ironic supports passing a URL.
When we upgrade, we can stop doing this work ourself.
Closes: #298

let ironic look up the image checksum value

---

cmd/manager/main.go

There are[ two options for the leader election](https://docs.openshift.com/container-platform/4.1/applications/operator_sdk/osdk-leader-election.html). The SDK defaults to the simpler one ("Leader for life") which trades off slower failover (5 minutes by default - the pod-eviction-timeout) for a guarantee that there can never be two leaders. The other one (used here) fails over faster, but there may be two leaders if one node is running a clock 50% faster(!) than the others unless you tweak the default timeouts to accommodate the clock skew rate you expect.
The controller-runtime library provides a way to set leader among pods via config map annotation, that includes leader lease. In case when the pod fails to update the lease under the config map, the other pod will acquire the leader. …

Use leader election mechanism from controller-runtime library

---

deploy/role.yaml
deploy/role_binding.yaml

This commit addresses two issues.
1. Currently, the BMO has access to all resources in the 'metal3.io' api-groups. Considering principle of least privilege as a good practice, It limits it to only the BareMetalHost resource.
2. It also allows it to see BareMetalHosts in all namespaces, much like the CAPBM controller does.

Limit BMO access to only BMH in all namespaces

---

deploy/role.yaml

The metal3-baremetal-operator pod does not start due to no able to perform operations on configmap and secret resources. 
This commit gives it the required privileges. 
Co-authored-by: Feruzjon Muyassarov feruzjon.muyassarov@est.tech

Add more privilege to BMO for configmap and secret resources

---

pkg/bmc/access_test.go
pkg/bmc/redfish.go

Open questions:
* Are we happy with the `redfish+virtualmedia` prefix?
* Should we add another level to support both SSL and non-SSL schemes? `redfish+virtualmedia+https`?

Add support for redfish virtual media

---

pkg/bmc/irmc.go

Currently, RAID interface is not set when we create Ironic node(#320). This PR aims to make RAID interface to be set by vendor driver.
Co-Authored-By: Dao Cong Tien <tiendc@vn.fujitsu.com>

Configure RAID Interface for iRMC driver 

---

pkg/controller/baremetalhost/action_result.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/host_state_machine.go

Add an actionResult interface with several implementations (for complete, in-progress, failed, and error). Each action (corresponding to a state in the state machine) now returns one of these results. An actionResult can produce the reconcile.Result that we ultimately need to return, but also transmit additional data to the intervening code, such as the state machine itself. This has several advantages:
* It removes a lot of duplicated code, some of which was buggy as a result of inconsistent updating.
* It makes the reason for returning a particular result from an action self-documenting.
* In future it will allow the state machine to infer the reason for a result.
* It allows us to stop overloading the meaning of the Requeue field in reconcile.Result.
* It allows us to distinguish new …

Create an actionResult type to encapsulate the result of a reconcile action

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml

This change will update the CRD apiversion from apiextensions.k8s.io/v1beta1 to v1, which is the default since k8s 1.16.
Address #327

Change CRD apiversion to apiextensions.k8s.io/v1

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml

Reverting the CRD version change as this broke the BMH CRD. Some changes to the CRD are required for the version bump and should be tested with /test-v1a1-integration

Revert "Change CRD apiversion to apiextensions.k8s.io/v1"

---

deploy/ironic_bmo_configmap.env
deploy/ironic_ci.env

Until the ironic bug is fixed upstream, we need to disable
fasttrack for the provisioning to work properly
/cc @elfosardo

Disable fast track temporarily

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
pkg/controller/baremetalhost/action_result.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/host_state_machine.go

Previously, external consumers (such as the OpenShift UI) could only rely on the provisioning status to determine the cause of an error in a structured way (i.e. without having a lookup table of the possible error strings). This requires us to perform a lot of gymnastics with the provisioning status, and still did not always yield the correct results. This PR adds a well-defined field for determining the type of an error that systems such as UIs can use to direct the user to debugging the relevant thing.

Expose error types through the CRD Status

---

deploy/role.yaml

This PR applies the principle of least privilege on the BMO by limiting verbs it can invoke.
Closes metal3-io#356

Restrict BMO access to only required RBAC verbs

---

pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go

If you cancel provisioning before it has finished, both NeedsProvisioning() and NeedsDeprovisioning() return false because the latter assumes that provisioning has to be complete before the host needs to be deprovisioned.
Because the state machine remembers the state, it tries to continue provisioning (if it ever finished it would move on to deprovisioning, but it doesn't). This results in a crash because the Ironic provisioner assumes (quite reasonably) that the Image is non-null when we are trying to provision.

Fix crash when cancelling provisioning

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml
pkg/apis/metal3/v1alpha1/baremetalhost_types.go

Using operator-sdk v0.12.0, CRD generation part fails with an unspecified error. Digging further reveals a slight format change in validation pragma for enums (';' replaces ',').
Address #360

Fix error generating CRDs with operator-sdk v0.12.0

---

deploy/ironic_bmo_configmap.env
deploy/ironic_ci.env

the fix was merged upstream and is in the tripleO package:
https://opendev.org/openstack/ironic/commit/7f1f79ac25e270c3585dd23c042a037431b97718

Enable fasttrack for ironic

---

pkg/apis/metal3/v1alpha1/baremetalhost_types.go

This propagates in UI which has broken (unclickable) links for bare metal host events. Since the APIGroup is not separately included event's InvolvedObject, it is expected to be included in APIVersion.
This change adds whole GroupVersion string as InvolvedObject's APIVersion.

InvolvedObject APIVersion is expected to be SchemeGroupVersion string

---

deploy/operator/ironic/operator_ironic.yaml
deploy/operator/ironic_keepalived/operator_ironic_keepalived.yaml

Removing the privileged security context to have a more
fine-grained control with capabilities. NET_ADMIN set for
dnsmasq and httpd (in case the user specifies a low port)

Remove container privileges and add NET_ADMIN capability

---

docs/api.md

Use the same path that is found in the Ironic documentation at
https://docs.openstack.org/ironic/latest/admin/drivers/redfish.html

update example URL for redfish driver

---

pkg/apis/metal3/v1alpha1/baremetalhost_types.go

This is step 1 adding *stateAvailabel*  ProvisioningState to BMO, 
Required  for the completion of  PR https://github.com/metal3-io/baremetal-operator/pull/340
Once this is merged the new bmh.StateAvailable will be available for CAPBM
step 2. Create a pull request for CAPBM to add stateAvailabel to case statement
[code to change](https://github.com/metal3-io/cluster-api-provider-baremetal/blob/7164d28f2e9c875ea7180eb8f315de322cf45512/baremetal/baremetalmachine_manager.go#L391)
Step 3. Merger BMO PR 340
Step 4 caret a PR to remove *stateReady* ProvisioningState from CAPBM

Add available ProvisioningState  , so CAPBM is aware of this state 

---

docs/api.md
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go

When pivoting, we need a way to temporarily disable the reconciliation of objects while we are moving them. The BMH status needs to be moved along with the spec, and that is a two-step operation (create the BMH and update the status). If the reconciliation was happening in the meantime, this could trigger an introspection of a deployed host, hence messing up the host. Adding the annotation on the BMH would prevent such issues.

Add a Pause annotation for pivoting

---

pkg/provisioner/ironic/ironic.go

This is needed as a temporary fix for #439 
This adds a metadata key "local-hostname" set to the BMH name passed as metadata by Ironic.

add local-hostname in ironic metadata

---

test/e2e/baremetal_test.go

There is a typo for DisableCertificateVerification that
causes the e2e tests to fail.
Signed-off-by: Yolanda Robla <yroblamo@redhat.com>

Fix typo in e2e testing in certificate test

---

docs/api.md

We did not update the documentation for BMC URLs when we added the
virtual media variants.

expand BMC URL documentation to include virtual media support

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go

This can be one of two keys, depending on whether the host
got an ipv4 or ipv6 address, so use the ipv6 key in the case
where the ipv4 one is unset.
Currently in a single-stack ipv6 deployment the IP ends up
empty like:
```
Hostname:     worker-0.ostest.test.metalkube.org
Nics:
Ip:
```
But with this change Ip should be correctly populated.

Don't assume IPv4 in introspection data

---

go.mod
pkg/controller/baremetalhost/host_config_data.go
pkg/controller/baremetalhost/host_config_data_test.go

Empty namespaces in userdata and networkdata object references
now default to the baremetalhost namespace
Fixes #462

Default user and network data namespace to BMH namespace

---

README.md

Remove v1alpha2 CI status badge as v1alpha2 integration CI is not going to be supported anymore.

Remove v1alpha2 CI status badges

---

Makefile

The `make test`  still calls for dep-check which was removed previously. The call to dep-check in Makefile was accidentally left-behind.

Fix make test phony to remove dep-check call

---

deploy/ironic_ci.env

Ironic fast-track is not working properly yet. Setting it to false for local BMO deployment.

Fix Ironic fast-track for local BMO deployment

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml
docs/api.md
go.mod
go.sum
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/apis/metal3/v1alpha1/zz_generated.deepcopy.go
pkg/controller/baremetalhost/host_config_data.go
pkg/controller/baremetalhost/host_config_data_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

Metadata is required for cloud-init config drive which is used by
Ironic. User should be able to create custom metadata in a secret and
reference it in a BareMetalHost object.

Implement metadata interface for baremetal operator

---

docs/api.md
pkg/hardware/profile.go

OCP Baremetal IPI inside of Openstack environment requires the RootDeviceHint to be /dev/vdb when a pxeboot is performed given that OSP uses nova rescue and a pxeboot.img as /dev/vda.

Add openstack profile

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml
pkg/apis/metal3/v1alpha1/baremetalhost_types.go

The validation rules need to be set where the type is defined, not
where it is used.
Addresses #434

fix kubebuilder validation for vlanid

---

go.mod
go.sum

Running `make gosec` introduces changes to the local working
directory, so let's update the dependencies properly.

update vendored gosec dependencies

---

docs/dev-setup.md

Since we updated to operator-sdk 0.17.0 developers need to install
openapi-gen separately.

document openapi-gen dependency

---

Makefile
hack/Dockerfile.operator-sdk
hack/generate.sh

Add a make target 'generate-check' to ensure that both the code and
CRDs have been regenerated for any change.
Add hack/Dockerfile.operator-sdk to build an image containing the
operator-sdk and other dependencies for the generator check.
Add hack/generate.sh to run the check in a container using the image
built by the new Dockerfile.
Addresses #434

set up check to ensure operator-sdk generation is done

---

Makefile

Expand the docker make target to test both docker files that appear in
the repo. The existing travis-ci job will try to build both images.

add test for operator-sdk docker file

---

deploy/role.yaml

Create a symlink from deploy/role.yaml to deploy/rbac/role.yaml so
that the operator-sdk will find the role file it needs for the `add
api` command.
We cannot make the link in the opposite direction because kustomize
refuses to follow symlinks outside of the directory where its
configuration is.
Replaces #501
Fixes #500
Related to #434

symlink role file used by operator-sdk

---

Makefile

operator-sdk  `up local` is now  `run --local` since v0.15.0.
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

Makefile: update operator-sdk command

---

tools/run_local_ironic.sh

To give some time for Ironic to start properly and avoid
inspector failing to start due to ironic not being ready

Postpone inspector start when running out of cluster

---

docs/dev-setup.md

This PR fixes the broken link to vBMC docs in docs/dev-setup.md. It's just one line.
Addresses: #507

fix the broken link to vbmc doc

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml
docs/api.md
go.mod
go.sum
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go

The BareMetalHost.Spec currently supports providing a checksum for the image to be provisioned as either a string or URL. But at the moment, the checksum defaults to md5 only. This PR supports other types of checksums such as sha256, etc.
The BareMetalHost.Spec's checksum string value is expanded to specify other checksum algorithms and its value in the form of: "sha256:abcdef...", "md5:xyzabc...", etc
Address #148

Expand image checksum support

---

tools/run_local_ironic.sh

The Ironic endpoint is not reachable as reported in [#310](https://github.com/metal3-io/metal3-dev-env/pull/310). This patch adds `ironic-endpoint-keepalived` container to run outside of the cluster when the Ironic is running locally. 
This is related to [#310](https://github.com/metal3-io/metal3-dev-env/pull/310).

Run ironic-endpoint-keepalived container outside the cluster

---

Makefile

After updating the operator-sdk the command to run a local instance is
now different.

fix operator-sdk commands in the makefile

---

pkg/controller/baremetalhost/baremetalhost_controller.go

If we are copying the Status in from a baremetalhost.metal3.io/status
annotation, return and requeue immediately after writing it rather than
try to continue to do other things, which may result in a write
conflict.
Also, invert the output of the hostHasStatus() method, so that it no
longer returns the exact opposite of what it says on the tin.

Requeue after writing status from annotation

---

Makefile

This PR adds the required build parameter to the `build` target to correctly display the baremetal-operator version string.
The echo has been removed for the `tools` targets since it was unused

Fix version string

---

pkg/controller/baremetalhost/baremetalhost_controller.go

Now that 'deleting' is treated as its own provisioning status, returning
actionContinue is sufficient to ensure that the state gets written at
the conclusion of reconciliation. Doing an early write will cause an
error to be logged when we go to do the final write, since the object
generation will no longer match.

Get rid of extra resource write during delete

---

tools/run_local_ironic.sh

A sleep was added to give time for ironic to start properly before
starting inspector. It is not needed any more, the bug in
inspector was fixed

Remove ironic workaround when running locally

---

pkg/controller/baremetalhost/metrics.go

The prometheus metric metal3_host_config_data_error_total added in
004fc7a72f95ba7130c5ddf658de309c11e9bafa (#348) was not registered.

Register host config data error metric

---

pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go

The BareMetalHost.GetImageChecksum method must not assume there is any
image information present.

handle missing image in GetImageChecksum

---

deploy/operator/no_ironic/operator.yaml

Kustomizing the image in metal3-dev-env requires the image to
be specific. This unifies the BMO image across different
deployments so that the image kustomization works in all cases

Unify the image reference in operator deployments

---

pkg/provisioner/ironic/ironic.go

We discovered in #519 that it is possible for the Ironic node to remain in a `inspect wait` state even after the operator has received the inspection results and changed the state to Ready.
When calling ValidateManagementAccess() from the Ready state, we should wait some time before re-reconciling if the host is not in the `manageable` state. Previously, it was requeuing immediately with the effect that the operator would poll the Ironic state in essentially a tight loop.
Also fix up some redundant code that makes it confusing to read.

Add missing delay in ValidateManagementAccess()

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml
pkg/apis/metal3/v1alpha1/baremetalhost_types.go

Disk sizes less than zero do not make sense.

add minimum validation for root device hint size

---

cmd/get-hardware-details/main.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go

The problem won't be caused by the operator's version of the annotation, but we're using the annotation to load just the hardware details portion of the status and that is causing reconciliation to continuously copy the status from the annotation to the host and never let the host move past that point.

remove infinite reconcile loop when fetching status annotation

---

pkg/provisioner/ironic/ironic.go

Older versions of ironic that do not have
https://review.opendev.org/#/c/711816/ refuse to provision if the
image information does not include 'image_checksum', even if the other
hash value parameters are given. It seems safe to always pass the old
name, so go ahead and do so.

support older ironic checksum expectations

---

docs/dev-setup.md

Updated the doc to point to the correct installation page for operator-sdk, since the SDK documentation has significantly changed to the website version now.
Also, updated the command in `Deploy Operator Locally` section to reflect newer operator-sdk version v0.17.1

Update doc link and operator-sdk command

---

docs/api.md
pkg/apis/metal3/v1alpha1/baremetalhost_types.go

CAPM3 node remediation needs the simple way of coordinate the provisioning and remediation of the unhealthy BMH. We want the user to be able to mark an unhealthy BMH with an ```unhealthy``` annotation. That annotation is used to control provisioning and remediation at the CAPM3 level.
For example, use of current pause annotation prevents the deletion of the machine objects and blocks the remediation of the unhealthy nodes.

New BMH unhealthy annotation

---

deploy/default/kustomization.yaml
docs/deploying.md

**What this PR does / why we need it:**
This patch fixes configMapGenerator behavior so that when BMO is deployed as part of CAPM3 it needs to be able to `create` configmap rather than `merge` and also addresses few fixes to some comments (typo and rephrasing) in #541 
Logs:
`Error: accumulating resources: accumulateFile "accumulating resources from '../deploy/default': '/home/****/go/src/github.com/metal3-io/baremetal-operator/deploy/default' must resolve to a file", accumulateDirector: "recursed accumulation of path '/home/****/go/src/github.com/metal3-io/baremetal-operator/deploy/default': merging from generator &{0xc0007bb230 { } {{ ironic-bmo-configmap merge {[] [] [ironic_bmo_configmap.env]} <nil>}}}: id resid.ResId{Gvk:resid.Gvk{Group:\"\", Version:\"v1\", Kind:\"ConfigMap\"}, …

🏃 Change configMapGenerator behavior in kustomization and typo fixes

---

pkg/provisioner/ironic/ironic.go

Sometimes a caller actually needs to know whether we succeeded in
changing the provisioning state or if we're just retrying because of a
conflict.
Mostly it doesn't though, so implement it as a separate method to avoid
adding complexity everywhere.
This is needed by #292.

Add tryChangeNodeProvisionState() method in ironic provisioner

---

tools/run_local_ironic.sh

Since `tools/run_local_ironic.sh `  installs  `ironic-endpoint-keepalived` , it should also delete this container while it deleted the other ironic containers, otherwise while doing iterations on this file, docker finds `ironic-endpoint-keepalived` already installed and throws an error.

Fix: Delete ironic-endpoint-keepalived container also while deleting other ironic containers

---

pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go

Since float is not considered a valid type we will eventually have to
convert this field to an integer. That's probably going to involve some
very not-fun contortions regardless (see metal3-io/metal3-docs#101), but
at the very least it's not helping anybody to continue creating Hosts
with fractional values that will be non-round-trippable later.

Round clock frequency to integer when setting HW details

---

docs/ironic-endpoint-keepalived-configuration.md

The kustomization workflow  has changed significantly and the different deployment scenarios have also been updated. This PR removes the obsolete info from  Ironic Keepalived container documentation and also updates the documentation with the way it should be deployed now.

Update Ironic Keepalived container documentation

---

pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/ibmc.go
pkg/bmc/idrac.go
pkg/bmc/ipmi.go
pkg/bmc/irmc.go
pkg/bmc/redfish.go

All of the redfish BMC's should support `+http` or `+https` explicitly,
however it's not configured for any of the virtualmedia BMC's. This
refactories the registerFactory code to allow specifying schemes for a
BMC, and ensuring the schemed versions exist for every one.
This keeps it explicit, so we can say which BMC's support specifying a
scheme.

pkg/bmc: refactor to support all schemes

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go

This commit removes the code setting the status annotation and
requiring to reconcile the object twice. This is now done in
CAPM3.

Do not set the status annotation

---

pkg/provisioner/ironic/errors.go
pkg/provisioner/ironic/ironic.go

#273
Signed-off-by: Dao Cong Tien <tiendc@vn.fujitsu.com>

Default to use soft power off instead of hard power off

---

docs/api.md
pkg/bmc/redfish.go

The "redfish" type implies generic support for the Redfish
protocol. If a hardware vendor ever needs customization, we will want
an alias in place. This patch adds such an alias for iLO 5 gear,
without adding any customization.

add ilo5-redfish alias

---

docs/baremetalhost-states.md
pkg/apis/metal3/v1alpha1/baremetalhost_types.go

Define a new state for newly-created Hosts with no BMC details.
We need the state definition so we can add it to CAPM3 so that does
not break when #569 merges.
See https://github.com/metal3-io/metal3-docs/pull/120 for more
details.

define the Unmanaged state

---

docs/testing.md

Fixing a couple of variable declarations that were being
complained about by ``make lint``.
Edit: This was because of an outdated version of ``golint``. This patch will now focus on updating the testing documentation to add directions for installing latest testing tools.
Addresses: #575

Update testing documentation with tool installation directions

---

pkg/controller/baremetalhost/baremetalhost_controller.go

As commented on #566.
Return the correct error if we fail to update the status subresource or
remove status annotation. Remove the status annotation even when it
contains data that cannot be unmarshalled correctly.

Fix error handling reading status annotation

---

pkg/controller/baremetalhost/baremetalhost_controller.go

Do not log reconcile attempts for paused hosts. This keeps the logs
quieter for debugging.

do not log for paused hosts

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml
pkg/apis/metal3/v1alpha1/baremetalhost_types.go

This PR extends the API to include the new field described in
https://github.com/metal3-io/metal3-docs/blob/master/design/baremetal-operator/implicit-boot-mode.md
without using it, so we can update the cluster API providers to avoid
overwriting the user-provided value when provisioning a host.
We need this before approving #586

add explicit boot mode field to baremetal host

---

pkg/controller/baremetalhost/baremetalhost_controller.go

If the power state is correct then we don't need to
save host status.

Use actionContinueNoWrite when power State == desired

---

pkg/controller/baremetalhost/baremetalhost_controller.go

The extra requeues added in 871926d407c4758f96a7fc011f254a57b2c0eaa1 to
ensure that the Status got written immediately after updating the status
annotation were incompletely reverted by
f1b81a06527cb41b2b7e0212e76fc86976b32324, after which they are no longer
required as we no longer write a status annotation and just write the
Status immediately. This reverts the remaining changes to prevent
unnecessary requeueing.

Avoid extra requeues when credentials missing

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go

If a host is paused, there is no need to reconcile it
periodically. Any change that removes the pause annotation will
trigger normal reconciliation.
See comments on #589 for more context

stop reconciling paused hosts

---

pkg/bmc/idrac_virtualmedia.go
pkg/bmc/redfish.go
pkg/bmc/redfish_virtualmedia.go

The redfish drivers were mixed together in one file and relied
on inheritance. The point of the BMC types is that they're very
simple, so a little repetition isn't a bad thing. This PR moves the
redfish-virtualmedia and idrac-virtualmedia drivers out to their own
files and removes the inheritance to make them easier to understand.

refactor redfish driver hierarchy

---

go.mod
go.sum

go-openapi/spec v0.19.9 bumps go-openapi/jsonreference to v0.19.4
go-openapi/jsonreference v0.19.4 bumps golang.org/x/text to v0.3.3
golang.org/x/text v0.3.3 mitigates against CVE-2020-14040
https://groups.google.com/g/golang-announce/c/bXVeAmGOqz0?pli=1

dep: cve: bump go-openapi/spec to v0.19.9

---

cmd/make-bm-worker/main.go
cmd/make-bm-worker/templates/templates.go

metal3-dev-env uses this program to create host resources. In order to
let metal3-dev-env change the boot mode for hosts, we need to add an
option to pass the value through to the template.

add -boot-mode argument to make-bm-worker

---

Makefile
deploy/crds/metal3.io_baremetalhosts_crd.yaml

The existing apiextensions.k8s.io/v1beta1 version is deprecated and will
be removed in k8s 1.19. v1 is available from k8s 1.16.
Using v1, unknown fields are now pruned by default, which is what we
want.
Fixes #327
Fixes #580

Switch CRD version to apiextensions.k8s.io/v1

---

Makefile

This PR adds support for OpenShift build variables in order to set the build version and the correct source git commit reference

Add support for build variables

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go

Default to UEFI everywhere, but allow the user to override that value
by setting Spec.BootMode.
Implements https://github.com/metal3-io/metal3-docs/blob/master/design/baremetal-operator/explicit-boot-mode.md
Fixes #422

implement explicit boot mode api field

---

pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/baremetalhost_controller_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/dependencies.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go
pkg/provisioner/provisioner.go

This PR aims to improve the reconcile loop by checking the status of the Provisioner dependencies before trying to reconcile the state: if the provisioner is not ready, the current request is requeued.
In particular, it checks the availability of the Ironic and Ironic Inspector services (thanks to @stbenjam for specific check logic, extracted from https://github.com/openshift-metal3/terraform-provider-ironic/blob/master/ironic/provider.go).
This approach should help especially during the bootstrap of those deployment scenarios where the Ironic services are launched at the same time of the operator - where the reconcile loop could start to operate before Ironic services were effectively up and running.

Check provisioner ready status when applying reconcile logic

---

Makefile
cmd/get-hardware-details/main.go
docs/ironic-authentication.md
go.mod
go.sum
pkg/provisioner/ironic/clients/auth.go
pkg/provisioner/ironic/clients/auth_test.go
pkg/provisioner/ironic/clients/client.go
pkg/provisioner/ironic/ironic.go

This commit adds the support for BMO to interact with ironic when
using http_basic.
requires gophercloud 0.12.0

Add support for http_basic auth for ironic and inspector

---

resources/keepalived-docker/Dockerfile
resources/keepalived-docker/manage-keepalived.sh
tools/run_local_ironic.sh

Currently the keepalived container, when stopped does not remove the ip
address it sets as VIP. This commit fixes it so that the VIP is removed when the
container is stopped

Fix Keepalived container to stop cleanly

---

docs/api.md

The credentials have to be encoded by base64 before pasting them in YAML.

Added encoding of credentials using base64

---

pkg/provisioner/ironic/ironic.go

When we go to delete a node we look it up by either the UUID stored in
the Host or by name, but previously when we deleted it from Ironic we
only used the UUID from the Host. This meant if the Host UUID was empty
or didn't match, we would be stuck in a loop from which we could never
recover. We can't have it both ways; either a node found by name is the
one that matches and we should delete it, or it isn't and we should
report that the node cannot be found and thus the delete is complete.
It is not clear under what circumstances we end up in this state. It is
possible that it involves the node being discovered by Ironic before the
Host is created and then immediately deleted.
Treat a host matching by name as the one we are looking for, and delete
it regardless of whether we had already …

Always delete found host from Ironic on deletion

---

build/Dockerfile

The metal3 base image was based on Centos 7 and very outdated.
Using distroless image as base, the size of BMO image went
down from 1.76GB to 45MB.

Change base image to distroless

---

docs/api.md

When explaining the API to a user, it is frequently useful to be able
to refer to the documentation for a specific field. This patch
reformats the documentation to use headers for the top level fields in
the spec and status sections of the host CRD so that anchors are
generated automatically.

reformat api documentation to make linking to field definitions easier

---

deploy/default/ironic_bmo_configmap.env
deploy/ironic_ci.env
ironic-deployment/default/ironic_bmo_configmap.env
ironic-deployment/keepalived/ironic_bmo_configmap.env

This PR re-enables  Ironic Fast track.  It was disabled previously due to bug.

Re-enable Ironic Fast Track

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go

Rewrite the mock server for the ironic provisioner ready checks so it
does not need a specific port. This will
eventually make it easier to expand the server to support other tests.

allow mock ironic/inspector service to run without specifying a port

---

deploy/default/ironic_bmo_configmap.env
deploy/ironic_ci.env
ironic-deployment/default/ironic_bmo_configmap.env
ironic-deployment/keepalived/ironic_bmo_configmap.env

After enabling fast track we are experiencing slowness in CI and the following error messages for both the nodes: 
```
2020-09-15 02:16:46.092 75 ERROR ironic.api.controllers.v1.ramdisk [req-33f3ce40-2812-4bfb-8c6e-4d6197dd8ff7 - - - - -] Agent heartbeat received for node 323c7b30-593d-465b-b70a-bdd93778db3c without an agent token.[00m
2020-09-15 02:16:46.093 75 DEBUG ironic.api.expose [req-33f3ce40-2812-4bfb-8c6e-4d6197dd8ff7 - - - - -] Client-side error: Agent token is required for heartbeat processing. format_exception /usr/lib/python3.6/site-packages/ironic/api/expose.py:184[00m
2020-09-15 02:16:46.094 75 INFO eventlet.wsgi.server [req-33f3ce40-2812-4bfb-8c6e-4d6197dd8ff7 - - - - -] ::ffff:172.22.0.70 "POST /v1/heartbeat/323c7b30-593d-465b-b70a-bdd93778db3c HTTP/1.1" status: 400 …
```

Disable Ironic fasttrack

---

pkg/controller/baremetalhost/host_state_machine.go

In future (see #340) we will rename StateReady to StateAvailable, but for now make
sure we correctly handle a Host with StateAvailable so that resources
modified by a future release continue to operate as expected after a
downgrade.

Handle StateAvailable when we see it

---

deploy/crds/metal3.io_baremetalhosts_crd.yaml
pkg/apis/metal3/v1alpha1/baremetalhost_types.go
pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go
pkg/controller/baremetalhost/action_result.go
pkg/controller/baremetalhost/action_result_test.go
pkg/controller/baremetalhost/baremetalhost_controller.go
pkg/controller/baremetalhost/host_state_machine_test.go

This PR replaces the one started from @honza on PR #584.
Reconciliation loop now retries the operation whenever an action failure is detected, with a backoff. The backoff calculation has been reviewed and some jitter added, and the error count is zeroed when the action succeeds.

Always retry provisioning operations on failure (continue)

---

Makefile
Tiltfile
docs/dev-setup.md
hack/kind_with_registry.sh
tools/install_kustomize.sh

This commit adds a setup to deploy BMO in a Tilt environment for
easier development. The image is built and reloaded live from
changes in the code. This commit:
- adds Tiltfile
- adds script to install kustomize locally
- adds script to start kind with a registry

Add Tilt setup

---

docs/api.md
pkg/bmc/access_test.go
pkg/bmc/ilo4.go
pkg/bmc/ilo5.go

This commit add support for iLO hardware type to
deploy ilo4 based systems using BMO.

Adding support for hardware type iLO

---

Makefile

Using bash syntax for environment variables in a Makefile results in
extra work building tools, as the ones at OPATH/... are never found.

Fix environment variables in Makefile

---

hack/gomod.sh

This script verifies that go.mod and go.sum are up to date, and that `go mod tidy` can be executed successfully.
This script should be run on every patch in CI.

Add gomod script

---

Makefile
hack/install-controller-gen.sh

The shell script to install controller-gen is a little verbose, so
move it out of the Makefile and into a separate hack script.
Have the script fetch the version of controller-tools that we expect,
then build it and install the results into the bin directory under the
root of the repository.
Have all of the commands that use controller-gen ensure that it is
built.

always install our desired version of controller-gen

---

ironic-deployment/ironic/ironic.yaml
tools/run_local_ironic.sh

This is a PR to split the ironic components in CI.

Split Ironic API and Conductor containers in run_local_ironic.sh

---

.gitignore
cmd/get-hardware-details/main.go
deploy/tls/kustomization.yaml
deploy/tls/tls_ca.yaml
docs/configuration.md
docs/deploying.md
go.mod
go.sum
ironic-deployment/ironic/ironic.yaml
ironic-deployment/keepalived-tls/kustomization.yaml
ironic-deployment/keepalived-tls/tls.yaml
ironic-deployment/tls/kustomization.yaml
ironic-deployment/tls/tls.yaml
pkg/provisioner/ironic/clients/client.go
pkg/provisioner/ironic/ironic.go
tools/run_local_ironic.sh

This PR introduces support for TLS using a custom CA certificate in BMO and modifies the deployment file to be able to deploy Ironic, inspector and BMO with TLS enabled.
This requires https://github.com/metal3-io/ironic-image/pull/198 and https://github.com/metal3-io/ironic-inspector-image/pull/62

Add TLS support between Ironic and BMO

---

docs/api.md

Clarify about interaction between the 'externallyProvisioned' field and the 'image' sub-fields.

Bug 1859999: Expand API documentation

---

main.go

Use the WATCH_NAMESPACE environment variable to set the default for
the --namespace command line option, to preserve configuration
compatibility with deployments that only set that variable and do not
pass the argument.

restore WATCH_NAMESPACE variable

---

Makefile
config/manager/manager.yaml
config/render/deployment.yaml

This PR adds a render of BMO deployment. 
It takes care of the task done at #667

Render BMO deployment

---

Makefile
config/kustomization.yaml
config/manager/manager.yaml
config/namespace/kustomization.yaml
config/namespace/namespace.yaml
config/render/capm3.yaml

We realized that for capm3 having the namespace in `config/manager/manager.yaml` is problematic, fetching it out of there and adding it in its own directory (namespace). 
To allow using namespace and default, a root level kustomization is added. 
Fixing, the command for `config/manager/manager.yaml` from `manager` to `baremetal-operator`

Add capm3 specific configurations in config/ dir

---

config/basic-auth/default/credentials.yaml
config/basic-auth/default/kustomization.yaml
config/basic-auth/tls/credentials.yaml
config/basic-auth/tls/kustomization.yaml
config/tls/kustomization.yaml
config/tls/tls_ca.yaml
tools/deploy.sh

This is a fix to the tls certificate path. It should be `config` instead of `deploy`

Fix tls certificate fetch path 

---

config/basic-auth/default/kustomization.yaml
config/tls/kustomization.yaml
tools/deploy.sh

This PR fixes the kustomization path for CAPM3 v1alpha3. It should point to `config/` to include the namespace

Fix kustomization path

---

Makefile
Tiltfile
config/manager/manager.yaml
config/render/capm3.yaml
ironic-deployment/keepalived/kustomization.yaml

This PR changes the name in `config/manager/manager.yaml` to point to `quay.io/metal3-io/baremetal-operator`
It also does some other changes to take the new config/ dir into account.

Fix image name in manager + other small nits

---

config/rbac/role.yaml
config/render/capm3.yaml
controllers/metal3.io/baremetalhost_controller.go

This PR adds the missing RBAC rules for secrets and events

Add missing RBAC for secrets and events

---

pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic_test.go
pkg/provisioner/ironic/testserver/inspector.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/ironic/testserver/server.go

Increasing test coverage for Ironic provisioner

start adding unit tests for Ironic.InspectHardware

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml

In the HardwareDetails output, our description of a disk's Name field
and some of the NIC fields were pretty misleading about what they
actually contains.

Correct the description of HardwareDetails fields

---

Makefile

There doesn't seem to be much point in running all of the lint and
unit tests before building the docker image, and it means we have to
keep the CI system set up to run extra tools in that job. This patch
removes the dependency so `make docker` only builds the image.

remove test dependency from docker build

---

docs/deploying.md

Document explaining deploying workflow has old structure for some folders. This PR updates the document with recent folder structure, i.e `config` and `ironic-deployment` folders.

📖 Update deploying document to reflect recent changes

---

tools/install_kustomize.sh

When running `make build`, I encountered the following error:
```
$ make build
./bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
cd tools; ./install_kustomize.sh
Verifying kustomize version
kustomize not found, installing
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   661  100   661    0     0   3755      0 --:--:-- --:--:-- --:--:--  3755
100 12.5M  100 12.5M    0     0  6312k      0  0:00:02  0:00:02 --:--:-- 8614k
kustomize
mv: cannot stat 'kustomize': No such file or directory
./bin/controller-gen "crd:trivialVersions=false,allowDangerousTypes=true,crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
tools/bin/kustomize …
```

Fix path in install kustomize

---

.travis.yml
Dockerfile
Tiltfile
go.mod
hack/Dockerfile.golint
hack/generate.sh
hack/gofmt.sh
hack/gomod.sh
hack/govet.sh
hack/unit.sh

**What this PR does / why we need it:**
In order to avoid differences in go version across all repositories, this PR updates go to the latest in hack scripts. The motivation behind this is from [project-infra/pull/124](https://github.com/metal3-io/project-infra/pull/124).

Update golang to latest to match version across all repos

---

controllers/metal3.io/host_config_data.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/adopt_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/power_test.go
pkg/provisioner/ironic/provision_test.go
pkg/provisioner/ironic/testserver/ironic.go

this builds on top of https://github.com/metal3-io/baremetal-operator/pull/649

Unit tests for ironic.{Adopt,PowerOn,PowerOff,Provision,Deprovision}

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/demo_test.go
controllers/metal3.io/host_config_data_test.go
controllers/metal3.io/host_state_machine_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go

Use consistent capitalization and naming conventions for the loggers.

make logger names more consistent

---

Tiltfile
tools/deploy.sh

cc #692 
In #691, we moved the kustomize binary from `tools/bin/kustomize` to `bin/kustomize` but forgot to update a few paths. This PR fixes those issues.

Change kustomize path from tools/bin/ to bin/

---

.travis.yml

All of the Travis tests except building the Docker image have duplicates
in Prow, so stop running them.

Disable unnecessary Travis tests

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/ironic/updatehardwarestate_test.go

Increasing test coverage for Ironic provisioner

start adding unit tests for Ironic.UpdateHardwareState

---

config/manager/manager.yaml
config/render/capm3.yaml
main.go

Add a command line option to specify the address for a health-check
endpoint and use the address to configure that endpoint in the
controller.
Fixes #656

add health check endpoint

---

README.md

This PR adds important information about 'config/render/capm3.yaml in README. This was not clear before. Please check the README for more detail

Add info about 'config/render/capm3.yaml in README 

---

tilt-provider.json

This PR removes the main-go path in tilt-provider.json file. This enable bmo to run properly when [using Tilt](https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/docs/dev-setup.md#tilt-development-environment)

Remove main.go path in tilt-provider.json file

---

docs/dev-setup.md

This PR updates the documentation to add TLS variables that need to be exported in case the local ironic containers are expected to run with TLS enabled.

Update local ironic documentation with TLS information

---

config/manager/manager.yaml
config/render/capm3.yaml
main.go

v1alpha3 based CI jobs are failing by not being able to render livenessProbe field. It seems due to the indentation in the deployment manifest.
```
+ /home/****/go/src/github.com/metal3-io/baremetal-operator/tools/deploy.sh true false true true true
~/go/src/github.com/metal3-io/baremetal-operator ~/go/src/github.com/metal3-io/baremetal-operator
make[1]: Entering directory '/home/****/go/src/github.com/metal3-io/baremetal-operator'
./tools/install_kustomize.sh
+ OUTPUT=bin/kustomize
+ '[' -d vendor ']'
+ CMDPATH=/home/****/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.8.5
+ '[' '!' -f /home/****/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.8.5 ']'
+ go mod download
+ go build -o bin/kustomize /home/****/go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.8.5
make[1]: Leaving directory …
```

Fix livenessProve for BMO

---

ironic-deployment/ironic/ironic.yaml
tools/run_local_ironic.sh

Adding ironic and  ironic-inspector log watch entry points per this design proposal: https://github.com/metal3-io/metal3-docs/blob/master/design/ironic-debuggability-improvement.md

Add log watch entry points

---

tools/remove_local_ironic.sh
tools/run_local_ironic.sh

Separating the local container removal from run_local_ironic script, so that it can be used in metal3-dev-env also. This simplifies ironic container handling.

Add remove local ironic script

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml

Change column 'Provisioning Status' to 'Provisioning_Status'
Change column 'Hardware Profile' to 'Hardware_Profile'
Columns 'Status', 'BMC', 'Hardware_Profile' only visible with '-o wide'

Make 'get bmh' output concise and column one-word

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
controllers/metal3.io/action_result.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine.go
controllers/metal3.io/host_state_machine_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/adopt_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go
pkg/provisioner/ironic/updatehardwarestate_test.go
pkg/provisioner/provisioner.go

Ensure that regardless of the current provisioning state, we always re-register the Node in ironic if the ironic database has been lost.
Ensure that if this occurs during deprovisioning, the Node is re-adopted so that we commence deprovisioning again, so that the Host is always left in a clean state.
This also changes the steady state that we use for Ready hosts in Ironic. Previously we would try to maintain the ironic state as `manageable`. Now we maintain it in `available` if possible. This means that we don't end up doing a second automated cleaning on provisioning if we have just done an automated cleaning on deprovisioning.

Handle re-registration in all states

---

Makefile
docs/testing.md
hack/manifestlint.sh

This adds a new `manifest-lint` target in the Makefile to run
manifest validation checks via ./hack/manifestlint.sh script.

Add a Makefile target for running manifest validation

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

If an existing Ironic node, and a BMH share a MAC address, link them together.
Also includes some new functions in the test server for testing port logic

Look up existing nodes by MAC address

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

It is not safe to assume in ValidateManagementAccess() that the ironic
state will eventually converge to manageable, available, or active. The
state may in fact be something (like e.g. adopt failed) that requires
action on the part of the actual provisioning function for the current
state to resolve. We previously weren't allowing that, because
ValidateManagementAccess() was always forcing a requeue whenever it
encountered a node in another state.
Since b7b10d79a86bb8e5f04fc86986c7b84fb1a34871 we call
ValidateManagementAccess() in substantially every provisioning state, so
there are even more node states (e.g. inspect failed) that we could get
stuck in.
Move the code for handling the verifying state so that it runs only in
that state, and allow all other states from manageable on to be …

Avoid getting stuck in ValidateManagementAccess due to node state

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go

The first time we provision a Node, we must move it from the manageable
to available state. This involves automated cleaning, and it may fail.
If it does, we should attempt to recover.

Handle cleaning failures during provisioning

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml

This small patch adds kubebuilder validation format for ClockSpeed as double.
Signed-off-by: seivanov <seivanov@mirantis.com>

Add kubebuilder validation for ClockSpeed

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go

Everytime the BMH status is saved the `LastUpdated` field is updated with the current time, and a new update is generated if the marshalled string results different from the previous version (up to the seconds), producing more reconcile loops than needed.
This PR filters out all the updates on the Status by ignoring all those ones that do not increase the Generation field (except for the finalizers and annotations) [1]
[1] https://www.openshift.com/blog/kubernetes-operators-best-practices

Filter out status updates from the reconcile loop

---

docs/dev-setup.md

Fix a typo in docs/dev-setup.md document

Fix a typo in doc/dev-setup.md

---

docs/dev-setup.md

Update the document to instruct creating [`baremetal-operator-system`](https://github.com/metal3-io/baremetal-operator/blob/40246049da00e2f98beaf5d2a451472e0a1c0f35/config/default/kustomization.yaml#L2) namespace instead of `metal3`

Fix manager namespace in docs

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
apis/metal3.io/v1alpha1/baremetalhost_types_test.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/demo_test.go
controllers/metal3.io/host_state_machine.go

It is up to the consumer, not the host, to decide when a host is ready
to have provisioning instructions added. The checks in the Available()
method will be inlined in cluster-api-provider-metal3.
Similarly, the host.Status.ErrorMessage field is the API for determining if a host has an error, so remove HasError().

remove convenience methods from BareMetalHost

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_state_machine.go
controllers/metal3.io/host_state_machine_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/empty/empty.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go
pkg/provisioner/ironic/validatemanagementaccess_test.go
pkg/provisioner/provisioner.go

As [discussed](https://github.com/metal3-io/baremetal-operator/issues/739#issuecomment-742218022) in #739, in order to decide whether an error we see from Ironic is one that we have seen and dealt with before (in which case we should retry the present operation) or not (in which case we should deal with the error) we need to store some sort of state.
This PR uses a differential between the ErrorType/ErrorMessage and the ErrorCount to encode this differential. The actual error is cleared whenever we successfully start or continue a new operation, but the error count is preserved until the operation is fully complete. This allows us to both determine when an error is new (when no error is currently recorded in the Status) and yet still do exponential backoff when multiple consecutive errors …

Do retries with backoff in ValidateManagementAccess, Inspect, and Deprovision

---

pkg/provisioner/ironic/ironic.go

This aims to de-duplicate the code where ironic image settings are managed, so that new code planned for the LiveImage enhancement don't need to be added in two places

ironic provisioner de-duplicate image options

---

controllers/metal3.io/action_result.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_state_machine.go
controllers/metal3.io/host_state_machine_test.go
main.go
pkg/provisioner/demo/demo.go
pkg/provisioner/empty/empty.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/delete_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go
pkg/provisioner/ironic/power_test.go
pkg/provisioner/ironic/provision_test.go
pkg/provisioner/ironic/result.go
pkg/provisioner/ironic/updatehardwarestate_test.go
pkg/provisioner/ironic/updateopts_test.go
pkg/provisioner/ironic/validatemanagementaccess_test.go
pkg/provisioner/provisioner.go

Use semantic functions (`retryAfterDelay()`, `operationContinuing()`, `operationComplete()`, `operationFailed()`, `transientError()`) to generate return values from ironic provisioner. This is a first step toward changing the `provisioner.Result` type to include richer information (e.g. to be able to distinguish between a request to retry after a delay and the operation simply continuing).
Stop writing to the BareMetalHost Status subresource in the provisioner, and require all changes to be communicated back to the controller via return values from the Provisioner interface.
Only update the BareMetalHost Status subresource when something has changed, instead of on ~every reconcile.

Improve communications between controller and provisioner

---

pkg/provisioner/ironic/ironic.go

We always want to get the checksum from the Image passed as imageData.
Due to an inadvertant change during the refactoring that created this
method (177d9efb4d627f6c3d9fae92e0b68c94c06aa713), we were always
getting the checksum from the Image in the Spec, even though imageData
may reference the one in the Status during registration.
This meant that during deprovisioning (with no image in the Spec),
adoption would fail as the node would not have image data added during
registration.

Get correct image checksum in getImageUpdateOptsForNode()

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/updateopts_test.go

This isn't required for whole-disk images but was added prior to
https://storyboard.openstack.org/#!/story/2005165 which landed some
time ago.

Remove root_gb workaround

---

controllers/metal3.io/baremetalhost_controller.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go

If provisioning fails and the node ends up in the `deploy failed` state,
we try to recover by deprovisioning. That would work better if we
actually handled `deploy failed` in `Deprovision()`.
Only call `Adopt()` if the previous provisioning completed and recorded
the requisite image data.

Fix issues with deprovisioning after an error/failover

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine_test.go

Currently when adoption fails, we use RegistrationError but this gets
cleared any time registration succeeds. We need a separate signal for
adoption failure, which allows us to force retry the adoption again.
Fixes #697

Force retry when adoption fails

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml

Show `status.errorType` intead of `status.errorMessage` under ERROR field when listing baremetalhosts
Fixes https://github.com/metal3-io/baremetal-operator/issues/721

Use errorType intead of errorMessage

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go

During deprovisioning of a Host, if 'deleting' (i.e. deprovisioning) the
node succeeds (i.e. it doesn't go to the Error state) but the automated
cleaning that follows fails, the only way to recover is to return the
node to the manageable state.
Previously, once in the manageable state we would attempt adoption on
the node so that we could deprovision again. However, in the course of
'deleting' the node, the image information is cleared from it so it
cannot be adopted again. (Adoption continues to be the right thing to do
if the node has just been re-registered due to the Ironic database being
recreated, and in that case the image information is present since it
gets added during the initial registration.)
To work around this, don't attempt to adopt during the Deprovisioning
state if the …

Ironic: Don't adopt after clean failure during deprovisioning

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/testserver/ironic.go

When registering a new host, we check if its bootMACAddress conflicts
with any existing Ironic nodes.  This procedure queries Ironic ports,
and if a port is found, we use the port's NodeUUID to find the
conflicting node.  However, we are using `ports.List()` which only
returns minimal resources by default; e.g. any returned ports will have
their NodeUUID property set to an empty string.
We are now explicitly asking for Ironic to include the `node_uuid`
field.
We also adjust the mock test mechanism to account for this.

Ask Ironic to include NodeUUID when querying ports

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

If we can't find a node by name, and have to resort to using MAC address
lookup, we can't accept a node that has a name.  In that scenario, we
have detected a MAC address collision, and human intervention is
required.  We signal this by returning an `operationFailed` provisioning
result with the offending MAC address in the error message.

Fail registration when boot MAC conflicts

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml
controllers/metal3.io/action_result.go
controllers/metal3.io/action_result_test.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_state_machine.go
controllers/metal3.io/host_state_machine_test.go
controllers/metal3.io/metrics.go
docs/configuration.md
pkg/provisioner/demo/demo.go
pkg/provisioner/empty/empty.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provisioncapacity_test.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/ironic/testserver/server.go
pkg/provisioner/provisioner.go

This PR introduces a soft limit for the number of hosts being simultaneously being provisioned.
Design doc: https://github.com/metal3-io/metal3-docs/blob/master/design/baremetal-operator/limit-hosts-provisioning.md. 
A new configuration variable is provided, called `PROVISIONING_LIMIT` (defaulted to 20), to specify the desired batch size that the operator will try to honor while provisioning new hosts. If there are no available slots, the current action for an host will be rescheduled using a fixed backoff with jittering to spread evenly the delayed requests.
Due the asynchronous behaviour of the Ironic subsystem, and the configurable level of concurrency of the operator, it's not possible to guarantee that such limit will be always respected, and occasional overflows could happen …

Limit the number of hosts simultaneously provisioned

---

ironic-deployment/keepalived/keepalived_patch.yaml

The capability 'NET_RAW' is needed to open a raw socket in ironic-endpoint-keepalived otherwise the container will fail.

Add "NET_RAW" to ironic-endpoint-keepalived

---

Makefile
main.go
pkg/version/version.go

This PR adds BuildTime variable to manager binary and populates this variable during build via Makefile.
Additional small fixes:
- use short git commit hash in manager binary
- use $(OPERATOR_NAME) variable for manager output name (to sync with Dockerfile)
- do not print empty variables in manager binary version package (Dockerfile does not set them)

Add BuildTime to manager binary.

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml

When migrating from older CRDs this filed is not available in bmh CRs.
Making this optional fixes ability to edit bmh CRs that where created before operationHistory filed was introduced.

Make operationHistory none-required field

---

pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go

The previous logic for `Provisioner.InspectHardware()` considered the action completed by just looking at the Inspector result flags `Finished` and `Error`. Anyhow, even though the inspection was effectively completed, there could be some cases where the related node `Provisioning` state was still in `inspectWait` since the update in Ironic is not simultaneous.
This could be a problem since the BMO state machine goes on and some BMO states could report an error if the node is not in the expected provisioning state (as the new `Preparing` state introduced in #763).
This PR so waits also for the node to _not be_ in `inspectWait` before considering the inspection successfully done.
/cc @dtantsur @zaneb @Hellcatlk

Wait for inspection completion

---

docs/api.md

The hardware subfield for the CPU clock rate is called
`clockMegahertz`, but the description uses `GHz`. This changes the
description to use `MHz`.

Fix the CPU clock rate unit in the API description

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go

When inspect.metal3.io=disabled is specified as an annotation we skip
inspection and return complete immediately from the Inspecting state.
Partially-Implements: https://github.com/metal3-io/metal3-docs/pull/155

Add inspect.metal3.io=disabled annotation

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml

Currently we force the status annotation to provide every
field, but when #796 lands it may be preferable to allow
a subset, so it's possible to set only a subset of the
hardware status fields when inspection is disabled.

Make BMH HardwareDetails fields optional

---

hack/install-controller-gen.sh
hack/install-golangci-lint.sh
tools/install_kustomize.sh

This variable has a well known default, just use it.

Development: account for unset GOPATH

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
docs/inspectAnnotation.md
docs/statusAnnotation.md

As described in https://github.com/metal3-io/metal3-docs/pull/155
This enables addition of only the hardware part of the status,
unlike the status annotation which can only be set on the first
reconcile, since it allows all fields of the status to be modified.

Add inspect.metal3.io/hardwaredetails annotation

---

OWNERS

After following the process described in our community documentation
[1], there were no objections to adding Dmitry as an approver.
[1] https://github.com/metal3-io/metal3-docs/tree/master/maintainers

add dmitry tantsur as approver

---

pkg/provisioner/ironic/ironic.go

This isolates options that are related to specific deploy_interface into separate methods making them a bit more readable.
This also would help with implementing new deploy_interface methods in the future.

Use separate methods for setting update node options.

---

docs/api.md
pkg/bmc/access_test.go
pkg/bmc/redfish.go

This is a rebased and gofmted #419 
Original PR description below
-------------------------------------------
The idrac BMCs have partiular handling of boot mode as configuration
change requests which need to be honored only at power state changes
as opposed to immediately, because this can conflict and over-write
existing configuration jobs.
While we shouldn't be in this state without more advanced bmc
features being leveraged, it is best to use the vendor supported
hardware type and interfaces for using redfish with their hardware.
This boot interface defaults to using iPXE, as opposed to virtual
media. A separate idrac specific redfish virtual media interface
already existed in the baremetal-operator.

Add idrac-redfish url type (continue)

---

pkg/provisioner/ironic/ironic.go

We are missing ironic node Inspecting state in this particular place. This was initially done in https://github.com/metal3-io/baremetal-operator/pull/607 but it was suggested by @dtantsur to have this fix separately so that it can be also bakcported in OpenShift BMO older versions.

Bug: fix missing Inspecting state

---

main.go

Any host which lacks BMC details should reach the Unmanaged
state regardless of whether it is externally provisioned or not.
Currently in this case we encounter an error creating the ironic
provisioner, because it expects BMC details to exist:
```
2021-03-22T18:15:46.443Z	ERROR	controller-runtime.manager.controller.baremetalhost	Reconciler error	{"reconciler group": "metal3.io", "reconciler kind": "BareMetalHost", "name": "ostest-worker-2", "namespace": "openshift-machine-api", "error": "failed to create provisioner: failed to parse BMC address information: missing BMC address", "errorVerbose": "missing BMC address\ngithub.com/metal3-io/baremetal-operator/pkg/bmc.NewAccessDetails\n\t/home/shardy/baremetal-operator/pkg/bmc/access.go:116\ngithub.com/metal3-io/baremetal-operator/pkg/provision …
```

Decouple Unmanaged state from externallyProvisioned

---

controllers/metal3.io/baremetalhost_controller.go
pkg/provisioner/ironic/ironic.go

This PR introduce a debug logger for the provisioner, to avoid printing too many traces in the log during the steady cases.

Review registration log traces for Provisioner

---

pkg/bmc/access_test.go
pkg/bmc/ibmc.go
pkg/bmc/idrac.go
pkg/bmc/ilo4.go
pkg/bmc/ipmi.go
pkg/bmc/redfish.go
pkg/bmc/redfish_virtualmedia.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/testbmc/testbmc.go

Instead of using `""` we will be using `no-raid`.
The support for RAID was considering  RAIDInterface defaul value as `""`
to generate the clean steps, this is causing errors in vmedia
deployments with idrac because it uses `no-raid`:
"Node failed to start the first cleaning step. Error: node does not support
this clean step: {'interface': 'raid', 'step': 'delete_configuration'}"

 Change default of RAIDInterface

---

pkg/provisioner/ironic/validatemanagementaccess_test.go

Follow-up to https://github.com/metal3-io/baremetal-operator/pull/786

Add a unit test for unsupported secure boot

---

Makefile
hack/unit.sh

To make local development more convenient this PR add ability to pass go test flags via envars directly to unit-tests that are started in docker/podman instance.
So effectively one could use something like this:
```
CONTAINER_RUNTIME=docker TEST_FLAGS="-failfast" ./hack/unit.sh
```
Setting `failfast` flag and removing verbose output is super-helpful on local dev environment when screen is small (less to scroll) and CPU/MEM resources are limited, so running all tests takes some time.
(mainly this is scroll issue actually, but could also be helpful in other cases) 

Pass go tests flags via env.

---

config/manager/manager.yaml
config/render/capm3.yaml
main.go
pkg/provisioner/ironic/delete_test.go
pkg/provisioner/ironic/findhost_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provisioncapacity_test.go
pkg/provisioner/ironic/updatehardwarestate_test.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

Modify the hostname for ironic to prepend the namespace to the name to avoid naming conflicts.

Prepend the namespace to ironic nodenames to avoid conflicts

---

pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go

Ensure that if the ironic node enters the InspectFail state, we not only report the error but also wait until after the exponential backoff before retrying, instead of retrying immediately.
The previous attempt to fix this in 2d02462fb45dbb5dd9dd0189ce91e0c417bbab2e didn't take due to a missing return.

Don't immediately retry on Inspect fail

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go

Currently we only handle the case where the json fails to parse
e.g is invalid json, but we silently ignore any value which is
valid data but fails to unpack into the HardwareDetails object.
In this case we should avoid removing the annotation since it's
not been copied into the status.hardware, and return an error
so the user can detect that the json data wasn't in the expected
format.

Handle hardwaredetails annotation value error

---

pkg/provisioner/ironic/ironic.go

This will set 'name' field of metaData as bmh name, otherwise by default ironic name gets set as hostname by default and ~ in hostname seems to be problematic for kubeadm during cloudinit nodeRegistration.

Set bmh 'name' in metadata as hostname

---

pkg/provisioner/ironic/ironic.go

Always update the image data within `ValidateManagementAccess()` regardless of Ironic node existence or not. Currently, image data update is happening only if Ironic node doesn't exist. That means, if we failed to write image data, we won't be able to update it again in the next retries since node already exists.
Fixes https://github.com/metal3-io/baremetal-operator/issues/839.

Always update image details

---

pkg/bmc/idrac.go

This PR also fix mis-configured function calls
buildManualCleaningSteps() and setTargetRAIDCfg().
They were using Status.Provisioning.RAID instead of
Spec.RAID. This now correctly performs RAID configuration.

Extend RAID configuration for iDRAC BMC type

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

This PR addresses the problem reported in https://github.com/metal3-io/baremetal-operator/issues/843.
Note that it completes the changes introduced by @zaneb in [beea4d0](https://github.com/metal3-io/baremetal-operator/commit/beea4d0ead807a8f19b38d538db3502ee3504b97) which already fixed the problem of deleting a BMH resource being created with a malformed BMC address (such issue originally also addressed by @kirankt in #713)

Fix error reporting when creating an host with invalid BMC url

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go

In 269ff1eef216af719251daa4a33bc294409d1945 we stopped potentially
making use of the image from the Spec in the provisioner when there is
no image in the Status, except for the Provisioning state where we want
to register with the image we are provisioning even though it hasn't
completed yet.
We also need to make an exception for the ExternallyProvisioned state,
because in that state the image details are never copied to the Status.
This relies on the change in c0373bbfa38d3169d1b994cf0f0429396f12e651,
which ensures that the image data can be added to the Node once the Host
reaches the ExternallyProvisioned state. Prior to this, the image data
was only added when the Node was created, so we would have had to pass
the image details starting with the first call to
ValidateManagementAccess() …

Fix adoption in ExternallyProvisioned state

---

.golangci.yml
Makefile
controllers/metal3.io/action_result.go
pkg/provisioner/demo/demo.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

Most linters are disabled by default when using golangci-lint, we need
to explicitely enable them if we want them to run.
This change enables the basic golint support.
For more info please check https://golangci-lint.run/usage/quick-start

Enable golint with golangci-lint

---

pkg/bmc/irmc.go

When `irmc` `power_interface` is used, Soft Reboot (Graceful Reset) and Soft Power Off (Graceful Power Off)
are only available if `ServerView` agents are installed.
Modify the value of `power_interface` to `ipmitool`, so that soft power off can be used directly.

modify power_interface for irmc

---

pkg/provisioner/ironic/capabilities_test.go
pkg/provisioner/ironic/delete_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/update_opts.go
pkg/provisioner/ironic/updateopts_test.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

It became clear from #839 and #849 that in order to ensure consistent behaviour, we must ensure that the Ironic Node's image data is up to date on every reconcile, and this was implemented in #845 by unconditionally updating it. This will result in a write to Ironic on every reconcile, which is excessive.
We have the ability to check whether the data we want to set is already present, but we largely don't because of the huge amount of messy boilerplate currently required to update each option. This PR refactors the code so that we can just pass a map of the options we want to set to a function and lazy updates come for free, along with standardised logging.

Always lazily update Node options in Ironic

---

docs/configuration.md
pkg/provisioner/ironic/clients/client.go
pkg/provisioner/ironic/ironic.go

Add ability to pass Client Certificate and Private Key to `ironic/ironic-inspector` client configuration.
Code is modeled after `TrustedCAFile` realization.
This enables to have Ironic behind TLS offload proxy with no-password authentication (mTLS).

Enable Client certificate authorization for Ironic TLS client.

---

pkg/provisioner/ironic/ironic.go

This PR fixes issues below:
- While node is created in Ironic DB and some misfortune happens to Ironic pod or DB pod, Ironic does not allocate port created node, this in turn breaks inspection with Ironic erroring on absence of allocated port, operator does not handle this case and stuck in erroring reconcile loop until back-off timer is triggered.
When node has no allocated port to it, Ironic returns this error
```
No lookup attributes were found, inspector won't be able to find it after introspection, consider creating ironic ports or providing an IPMI address
```
_IPMI address part is just wrong, BMC creds are checked in Registering state and are validated, also they where validated manually just in case._
After checking sources that return this error in: …

Allocate Ironic port when node exists and has no port allocated.

---

ironic-deployment/ironic/ironic.yaml
ironic-deployment/tls/default/tls.yaml
ironic-deployment/tls/keepalived/tls.yaml
tools/run_local_ironic.sh

Some of the CI jobs (especially Centos based integration tests) are failing with a common issue as below. This reverts https://github.com/metal3-io/baremetal-operator/pull/861.
to unblock CI and keep it running without failure. It seems there is a conflict in the httpd port and this probably needs to be fixed in Ironic image. See the [slack discussion](https://kubernetes.slack.com/archives/CHD49TLE7/p1620663788347600).
```
ERROR 1146 (42S02) at line 1: Table 'ironic.conductor_hardware_interfaces' doesn't exist
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using fc00:f853:ccd:e793::1. Set the 'ServerName' directive globally to suppress this message
(98)Address already in use: AH00072: make_sock: could not bind to address [::]:6180
no listening …
```

Revert: Point ironic-inspector to the ironic image in quay

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
docs/api.md

We have had several users report problems with credential management
that turned out to be caused by extra whitespace in the encoded values
placed into the secrets they created. Most often this is caused by
using command line tools to encode the values. For example,
$ echo -n root | base64
cm9vdA==
$ echo root | base64
cm9vdAo=
This change assumes that extraneous whitespace in the encoded values
is not part of the real username or password, and strips it before
trying to use the credentials. The logic to extract the credentials
from the secret is moved into its own function so that new unit tests
can be added.

strip whitespace after decoding secret values

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

When an annotation appears to force re-inspection, the Host returns to
the Inspecting state from the Ready/Available state. Originally the
ironic node would always be in the "manageable" state for a ready Host,
but we have usually been leaving it in the "available" state after
deprovisioning since 18465130c8f42bda4aa8191b5093656dcc029d90, and after
the initial preparation since 9a55ce5bc63a2f24916f1f604c736570836fdaea.
Handle the "available" node state during inspection by moving the node
to the "manageable" state. Since the first call to InspectHardware may
not start a new inspection, we have to return a new value to indicate
when inspection has actually started and thus it is safe to clear the
annotation. This also fixes a bug where failing to set the boot mode due
to a conflict would …

Fix bug with re-inspection due to Node in "available" state

---

Makefile

Correctly run controller-gen for new apis module

---

ironic-deployment/basic-auth/default/auth.yaml
ironic-deployment/basic-auth/default/kustomization.yaml
ironic-deployment/basic-auth/keepalived/auth.yaml
ironic-deployment/basic-auth/keepalived/kustomization.yaml
ironic-deployment/basic-auth/tls/default/auth.yaml
ironic-deployment/basic-auth/tls/default/kustomization.yaml
ironic-deployment/basic-auth/tls/keepalived/auth.yaml
ironic-deployment/basic-auth/tls/keepalived/kustomization.yaml
ironic-deployment/certmanager/certificate.yaml
ironic-deployment/certmanager/kustomization.yaml
ironic-deployment/default/kustomization.yaml
ironic-deployment/ironic/ironic.yaml
ironic-deployment/keepalived/keepalived_patch.yaml
ironic-deployment/keepalived/kustomization.yaml
ironic-deployment/tls/default/kustomization.yaml
ironic-deployment/tls/default/tls.yaml
ironic-deployment/tls/keepalived/kustomization.yaml
ironic-deployment/tls/keepalived/tls.yaml
pkg/provisioner/ironic/ironic.go
tools/deploy.sh
tools/run_local_ironic.sh

Ironic deployment doesn't have cert-manager setup for TLS and this PR will add the cert-manager for  TLS.

Add cert-manager setup for TLS in ironic deployment.

---

ironic-deployment/ironic/ironic.yaml
ironic-deployment/tls/default/tls.yaml
ironic-deployment/tls/keepalived/tls.yaml
tools/run_local_ironic.sh

This PR picks a commit of @elfosardo. The purpose of this commit is: After ironic-inspector merges with ironic image, we need to change the reference of the ironic-inspector container to point to the ironic image in quay.
This commit has been revert in the PR:https://github.com/metal3-io/baremetal-operator/pull/873. Now it can go in after the PR  https://github.com/metal3-io/ironic-image/pull/264/ which solves the problem that two httpd instances try to open the same port.

Point ironic-inspector to the ironic image in quay

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml
pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go

Motivation to add additional disk type is to allow custom storage provider assemble different types of storage based on needed storage profiles.
Something like:
- `fast and expensive` storage on NVME
- `general` storage on SSD
- `backup`, `cold data` storage on HDD
- `hybrid cache` storage with fast NVMEs backed by HDD
- ...

Add disk type field to BMH HardwareDetails

---

config/default/manager_auth_proxy_patch.yaml
config/render/capm3.yaml

Taking in changes as CAPI release-0.3 kubernetes-sigs/cluster-api#4639 
Eventually this means only to take a newer version of kube-rbac-proxy  into effect.

Uplift kube-rbac-proxy to v0.8.0

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine.go
docs/configuration.md

Instead of defaulting the $BMO_CONCURRENCY value (the maximum number of
Hosts to reconcile concurrently) to a hard-coded value of 3, set it
instead to the number of CPU threads available, but constrained to a
range between 2 and 8.
We never default to 1 so that we don't inadvertantly rely on
single-threadedness in tests. 8 seems to be a reasonable value for a
large scale deployment, while still being substantially below the
default $PROVISIONING_LIMIT of 20.
There remains no restriction on the value that can be passed in the
environment variable.
Fixes #905

Increase the default $BMO_CONCURRENCY for scale

---

pkg/bmc/irmc.go
pkg/provisioner/ironic/prepare_test.go

In view of the need for further discussion on #908, we can first disable RAID settings for iRMC to avoid clean fail on iRMC servers that do not support hardware RAID.

Disable raid feature for iRMC server

---

Makefile

The RBAC manifests are built from the controller (not api) code, so we have to run the `make manifests` commands at least on both the API module and the main module.

Also run controller-gen on the controller directory to get rbac

---

docs/api.md

Currently it's not clear that the `baremetalhost.metal3.io/detached`
annotation ignores the value. This PR makes it clear in the API
documentation that the annotation is not a boolean value so that setting
it as `"false"` may not have an expected result.
Supersedes: #912

Extend docs for "baremetalhost.metal3.io/detached" annotation

---

controllers/metal3.io/host_state_machine.go
controllers/metal3.io/host_state_machine_test.go

During provisioning, we want an error to cause the Host to be
deprovisioned again, but we very much do not want that to happen when
the Host is already provisioned. Due to an error in
0a7713bd3b4ff30aef2dac17c2d62a79bfe02872, provisioned Hosts were being
automatically deprovisioned whenever an error (other than a registration
error) occurred.
In practice this only manifested on Adopt() failures, since we don't yet
report power management failures.
Fixes #915

Don't deprovision provisioned host due to error

---

pkg/provisioner/ironic/configdrive_test.go
pkg/provisioner/ironic/ironic.go

I've spotted a few errors with the configdrive handling:
* We forgot to add configdrive to 'deploy failed' handler, so a repeated
deployment will always happen without a configdrive.
* ConfigDrive creation is conditional on UserData presence. This is
incorrect, any field being populated should trigger configdrive.
* There was no check on empty networkData, so we always tried to
deserialize empty string with YAML (which works, but is incorrect).
Create a new helper for configdrive and cover it with unit tests.

Fix configdrive handling

---

docs/api.md

Adding BIOS Parameters in api.md

---

docs/api.md
pkg/bmc/access_test.go
pkg/bmc/ipmi.go

Add a new parameter to optionaly set the ipmi privilage
level used when connected to BMC's over ipmi, the default
"ADMINISTRATOR" isn't always available (e.g. in ibmcloud).
Currently works on bootstrap node but not in the metal3 pod, so I'm missing something
tested with
openshift/installer#4845

baremetal: Add privLevel to bmc data

---

pkg/provisioner/ironic/prepare_test.go

Rather than testing the ironic Prepare method with a specific driver,
use a mock driver so that the tests can always run regardless of which
drivers currently have RAID enabled.

Use mock BMC for testing RAID

---

ironic-deployment/ironic/ironic.yaml

Ironic cannot run with more than 1 replica (the second crashes immediately) but the default rolling update strategy will try to get a second replica up and running before it removes the old one. This means that the rollout always gets stuck unless we first manually scale down the deployment to 0, then update, and finally scale it up again.
The recreate strategy is a better fit since it does the scale down
automatically.
For reference, here is how we currently upgrade ironic in the upgrade tests:
https://github.com/Nordix/metal3-dev-env/blob/1ab2dda79c717083f8ced21cdaeb885c93559dc6/vm-setup/roles/v1aX_integration_test/tasks/upgrade.yml#L217-L257

Use recreate strategy for ironic deployment

---

pkg/provisioner/ironic/ironic.go

Currently these states are unhandled. From DeployWait we can immediately
start undeploying, for Deploying we have to wait for another state.

Correctly deprovision nodes in DeployWait and Deploying

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/errors.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/power_test.go
pkg/provisioner/provisioner.go

Attempts to fix https://github.com/metal3-io/baremetal-operator/issues/828
This fix should have the following components based on the above bug:
1. If Ironic accepts the power state change but is unable to carry it out (expressed via LastError from ironic), that should result in PowerOn() and PowerOff() returning an ErrorMessage. 
2. Refactor PowerOff() in such a way that if soft power off fails, it proceeds to hard power off without reporting an error. It is possible that this logic is moved out of here and into Ironic itself.
3. Add a force flag to the PowerOff() so that it skips soft power off and directly proceeds to hard power off after the previous call results in an error.

Better handling of power management errors

---

config/tls/kustomization.yaml
ironic-deployment/basic-auth/default/auth.yaml
ironic-deployment/basic-auth/default/kustomization.yaml
ironic-deployment/basic-auth/keepalived/auth.yaml
ironic-deployment/basic-auth/keepalived/kustomization.yaml
ironic-deployment/basic-auth/tls/default/auth.yaml
ironic-deployment/basic-auth/tls/default/kustomization.yaml
ironic-deployment/basic-auth/tls/keepalived/auth.yaml
ironic-deployment/basic-auth/tls/keepalived/kustomization.yaml
ironic-deployment/certmanager/certificate.yaml
ironic-deployment/default/kustomization.yaml
ironic-deployment/ironic/ironic.yaml
ironic-deployment/keepalived/keepalived_patch.yaml
ironic-deployment/keepalived/kustomization.yaml
ironic-deployment/tls/default/kustomization.yaml
ironic-deployment/tls/default/tls.yaml
ironic-deployment/tls/keepalived/kustomization.yaml
ironic-deployment/tls/keepalived/tls.yaml
tools/deploy.sh
tools/run_local_ironic.sh

The changes in this PR will help to support TLS with CAPM3 v1a4(BMO part of CAPM3) and v1a5(BMO outside of CAPM3). This changes is needed to cope with v1a4 and v1a5 separately.

Modify namespace prefix in ironic deployment to support TLS

---

pkg/provisioner/ironic/raid.go
pkg/provisioner/ironic/raid_test.go

This PR replaces #941. I closed PR941 to avoid affecting openshift [PR165](https://github.com/openshift/baremetal-operator/pull/165).
PR165 should only track #908, rather than includes PR941, since it is a bug fix.
Unfortunately, PR941 and PR908 was on the same branch, so I have to close PR941 and open this one, sorry about that.
This PR aims to address a case in BuildRAIDCleanSteps which I missed in PR908.
In summary, it add the handling of the case when hardwareRAIDVolumes is nil and the target node doesn't have a RAID controller.  We shouldn't delete the RAID configuration on that node in that case, otherwise the `ironic` node will enter the clean failed state because of  `delete_configuration` clean step failure.

Fix missing case of BuildRAIDCleanSteps

---

config/crd/patches/cainjection_in_firmwareschemas.yaml
config/crd/patches/cainjection_in_hostfirmwaresettings.yaml
config/crd/patches/webhook_in_firmwareschemas.yaml
config/crd/patches/webhook_in_hostfirmwaresettings.yaml

apiextensions.k8s.io/v1beta1 API of CustomResourceDefinition is going to be removed in 1.22 release of K8s. This patch replaces currently used beta APIs with already available v1.

Don't use soon removed APIs

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
pkg/provisioner/ironic/configdrive_test.go
pkg/provisioner/ironic/ironic.go

We have default meta data that we should pass in any case.
PR based on top of https://github.com/metal3-io/baremetal-operator/pull/900.

Always build a configdrive except for live ISO

---

ironic-deployment/certmanager/certificate.yaml

This PR fixes the issue when cert-manager cannot generate ironic and mariadb certificates:
```
kubectl get certificate -n baremetal-operator-system
NAME                    READY   SECRET                  AGE
ironic-cacert           True    ironic-cacert           2m52s
ironic-cert             False   ironic-cert             2m51s
ironic-inspector-cert   False   ironic-inspector-cert   2m51s
mariadb-cert            False   mariadb-cert            2m51s
```
Which leads to the problem that all the nodes cannot reach the ready state: https://jenkins.nordix.org/view/Metal3/job/airship_master_v1a5_integration_test_centos/114/console

Add CommonName to Ironic and Mariadb certificates

---

config/rbac/auth_proxy_client_clusterrole.yaml
config/render/capm3.yaml

k8s 1.22 doesn't support rbac.authorization.k8s.io/v1beta1, uplifting the version to v1 instead.

Update rbac api version to v1

---

go.mod
go.sum
pkg/bmc/access.go
pkg/bmc/access_test.go
pkg/bmc/ibmc.go
pkg/bmc/idrac.go
pkg/bmc/idrac_virtualmedia.go
pkg/bmc/ilo4.go
pkg/bmc/ilo5.go
pkg/bmc/ipmi.go
pkg/bmc/irmc.go
pkg/bmc/redfish.go
pkg/bmc/redfish_virtualmedia.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/prepare_test.go
pkg/provisioner/ironic/testbmc/testbmc.go

Ironic sets the bios_interface by default for all drivers. For some drivers - particularly idrac-virtualmedia, the default should be overridden. If not explicitly set, Ironic will use the default.
This requires an upgrade to a Gophercloud release that supports BIOSInterface.

Explicitly set node bios_interface

---

pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/ironic/testserver/ironic_test.go

Calling the new `ClearDatabase()` method will change all registered non-POST handlers to reply with a 404.  Attempts to to create new resources via POST requests will still succeed.

unittests: Add a mechanism for simulating a lost ironic db

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml

BuildRAIDCleanSteps and saveHostProvisioningSettings rely on distinguishing between empty/missing and [].
Not allowing this causes errors like this:
```
Reconciler error,reconciler group:metal3.io,reconciler kind:BareMetalHost,name:sch05,namespace:cluster-sch,error:failed to save host status after "preparing": BareMetalHost.metal3.io "sch05" is invalid: status.provisioning.raid.hardwareRAIDVolumes: Invalid value: "null": status.provisioning.raid.hardwareRAIDVolumes in body must be of type array: "null",errorVerbose:BareMetalHost.metal3.io "sch05" is invalid: status.provisioning.raid.hardwareRAIDVolumes: Invalid value: "null": status.provisioning.raid.hardwareRAIDVolumes in body must be of type array: "null"
failed to save host status after "preparing" …
```

Allow writing 'null' for HardwareRAIDVolumes and SoftwareRAIDVolumes.

---

pkg/provisioner/ironic/clients/auth.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/ironic/testserver/server.go

We are now targeting go1.16. Starting with this release, the ioutils
package is now deprecated [0]. This updates usage of ioutils calls for
the new recommended io and os equivalents.
[0] [doc/go1.16#ioutil](https://golang.org/doc/go1.16#ioutil)
Similar changes in CAPM3: [cluster-api-provider-metal3/pull/287](https://github.com/metal3-io/cluster-api-provider-metal3/pull/287)

🌱 Remove deprecated ioutil usage

---

docs/deploying.md
docs/ironic-endpoint-keepalived-configuration.md

Updates tree structure for `config/`, `ironic-deployment/` and `resources/keepalived-docker/` folders. Also adds some more information re: what and why do we need those new folders/deployment files.

📖 Update docs and add more context concerning new deployment folders

---

README.md

Report `v1alpha5` CI job status instead of `v1alpha4` since that is the latest API version as of now.

📖 Update CI status badges in Readme

---

Makefile
tools/deploy.sh

The Makefile targets we use to build our tools rely on the `-modfile`
flag of the `go build` command.  Unfortunately, the golang build
toolchain doesn't respect the vendor directory relative to the `go.mod`
file specified by `-modfile`, and instead uses the vendor directory
relative to the current working directory.  Since each subdirectory in
this repository that contains a `go.mod` file needs to have its own
vendor directory in order to be built in vendorized scenarios, relying
on `-modfile` doesn't work.
The patch modifies the affected Makefile targets to instead change to
the directory of the tool being built instead of using the `-modfile`
flag.  This makes vendorization possible in downstream environments.
Finally, for consistency, we start building the kustomize tool in the
same …

Stop relying on -modfile to allow vendorization

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/errors.go
controllers/metal3.io/host_config_data.go
controllers/metal3.io/host_config_data_test.go
main.go
pkg/secretutils/label.go
pkg/secretutils/secret_manager.go

De-duplicate the labelling implementations for BMC creds and user data, into a single SecretManager type in a new secretutils package. Also adds the flexibility to add owner references that are not controller references. As much code as possible related to caching/watching of Secrets is moved into this new package.

Create a SecretManager type to manage Secrets

---

pkg/bmc/access_test.go
pkg/bmc/idrac_virtualmedia.go
pkg/bmc/redfish.go

There is no harm in having them enabled, they're not used implicitly.
In the future we may start using them, e.g. to eject virtual CD.
Requires https://github.com/metal3-io/ironic-image/pull/284.

Do not disable iDRAC Redfish vendor interfaces

---

pkg/provisioner/ironic/update_opts.go
pkg/provisioner/ironic/updateopts_test.go

Since b8dba2c016befacf2ff65004a2ff73008d5ab63a we use the nodeUpdater
with its built-in logging to update the ironic node when the credentials
change. This inadvertantly meant the BMC credentials will be logged in
this case (which is very rare; credentials don't often change).
To prevent this, sanitise new values as they are being logged. Ironic
does not return existing values for passwords, so there is no danger of
them being logged through that route. Currently password fields are only
redacted if they are set as part of a map; in practice this will be safe
for the foreseeable future as the bmc credentials are always set through
a map returned from the driver and not individually.
Fixes #980

Avoid logging BMC password when creds change

---

tools/deploy.sh

Deploy BMO&ironic with `deploy.sh` for the first time, the following errors have occurred.
```
Error from server (NotFound): error when creating "STDIN": namespaces "capm3-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "capm3-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "capm3-system" not found
```
This PR creates namespace for ironic and ignore any errors.
`shellcheck` passed.

Create namespace for ironic and ignore any errors

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml

This adds the AGE column to BMH CRDs to make the printed output consistent with the built in K8s resources.
Keeping things consistent with CAPI# kubernetes-sigs/cluster-api#5180

Add AGE column to BMH CRDs

---

tools/remove_local_ironic.sh

This is a leftover work of #945 which has removed ironic-inspector-log-watch.

Remove ironic-inspector-log-watch

---

Makefile
hack/gofmt.sh

This fixed non-existing `fmt` target in the Makefile. Also, updates `fmt-check` target to actually do the formatting.
Currently, if there is formatting issue running `./hack/gofmt.sh` would print
```
fmuyassarov@est:~/go/src/github/baremetal-operator$ ./hack/gofmt.sh 
+ IS_CONTAINER=false
+ CONTAINER_RUNTIME=docker
+ [ false != false ]
+ docker run --rm --env IS_CONTAINER=TRUE --volume /home/fmuyassarov/go/src/github/baremetal-operator:/workdir:rw,z --entrypoint sh --workdir /workdir registry.hub.docker.com/library/golang:1.16 /workdir/hack/gofmt.sh
+ IS_CONTAINER=TRUE
+ CONTAINER_RUNTIME=podman
+ [ TRUE != false ]
+ TOP_DIR=.
+ export XDG_CACHE_HOME=/tmp/.cache
+ cd .
+ gofmt -l .
+ [ -n apis/metal3.io/v1alpha1/baremetalhost_types.go ]
+ make fmt
make: *** No rule to make target 'fmt'. …
```

Fix non-existing fmt target usage

---

docs/dev-setup.md

We are missing a step to install cert-manager.
This patch addresses it.

Add cert-manager installation in the dev-setup doc

---

cmd/get-hardware-details/main.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_state_machine_test.go
go.mod
pkg/ironic/LICENSE
pkg/ironic/go.mod
pkg/ironic/raid.go
pkg/ironic/testbmc/testbmc.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/adopt_test.go
pkg/provisioner/ironic/bios_test.go
pkg/provisioner/ironic/configdrive_test.go
pkg/provisioner/ironic/delete_test.go
pkg/provisioner/ironic/factory.go
pkg/provisioner/ironic/findhost_test.go
pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go
pkg/provisioner/ironic/power_test.go
pkg/provisioner/ironic/prepare_test.go
pkg/provisioner/ironic/provision_test.go
pkg/provisioner/ironic/provisioncapacity_test.go
pkg/provisioner/ironic/raid.go
pkg/provisioner/ironic/ready_test.go
pkg/provisioner/ironic/updatehardwarestate_test.go
pkg/provisioner/ironic/updateopts_test.go
pkg/provisioner/ironic/validatemanagementaccess_test.go
pkg/provisioner/provisioner.go

`go get github.com/metal3-io/baremetal-operator/ironic` fails because
it can  not find new ironic module which lies under the pkg directory.
This PR fixes this bug by renaming ironic module to be parallel with folder
it lies.
LICENSE file is also added for GOPROXY url
can cache these modules in pkg.go.dev.
Fixes:  https://github.com/metal3-io/baremetal-operator/issues/996

Rename ironic go module to correct path for go get can find

---

.gitignore

Everybody has their own set of tools that generate different tempfiles
that should be ignored. The correct place to configure this is in the
global gitignore file "~/.config/git/ignore". Including ignore rules for
a select set of tools is an antipattern that encourages people to want
to add their own tools to the list in each of the hundreds of projects
they interact with instead of setting up their global rules once.

gitignore: Get rid of rules not associated with the project

---

pkg/ironic/bmc/access.go
pkg/ironic/bmc/ibmc.go
pkg/ironic/bmc/idrac.go
pkg/ironic/bmc/idrac_virtualmedia.go
pkg/ironic/bmc/ilo4.go
pkg/ironic/bmc/ilo5.go
pkg/ironic/bmc/ipmi.go
pkg/ironic/bmc/irmc.go
pkg/ironic/bmc/redfish.go
pkg/ironic/bmc/redfish_virtualmedia.go
pkg/ironic/testbmc/testbmc.go
pkg/provisioner/ironic/prepare_test.go

This PR adds new function namely RequiresProvisioningNetwork into
AccessDetails. Thanks to that, when provisioning network is disabled
or not, it becomes possible to check which BMCs support this.

Add RequiresProvisioningNetwork check into AccessDetails

---

pkg/ironic/bmc/access.go
pkg/ironic/bmc/access_test.go
pkg/ironic/bmc/credentials_test.go
pkg/ironic/bmc/ibmc.go
pkg/ironic/bmc/idrac.go
pkg/ironic/bmc/idrac_virtualmedia.go
pkg/ironic/bmc/ilo4.go
pkg/ironic/bmc/ilo5.go
pkg/ironic/bmc/ipmi.go
pkg/ironic/bmc/irmc.go
pkg/ironic/bmc/redfish.go
pkg/ironic/bmc/redfish_virtualmedia.go
pkg/ironic/go.mod
pkg/ironic/testbmc/testbmc.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/prepare_test.go

We'll want to use this package in validation (which must be defined in
the API), so don't have it depend on the API. Instead, define a local
structure for the FirmwareConfig data.

Remove bmc package dependency on API

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/preprovisioningimage_controller.go
pkg/secretutils/secret_manager.go

There is a race condition when deleting namespace using API/CLI that contains BMH and BMC Secrets.
Secrets can be deleting before actual de-provisioning of BMH has started and this leads to broken state with registration error.
By using finalizer that is set for secrets that are OwnerRef`ed this change ensures proper objects deletion order by un-setting secrets finalizer only after deprovisioning has ended, k8s will then be allowed to clean-up remaining BMC secrets.

Use finalizer for BMC secret.

---

config/manager/manager.yaml
config/render/capm3.yaml
ironic-deployment/ironic/ironic.yaml

Add readiness and readiness/liveness probes for the following pods:
```
Ironic-pod:
mariadb
ironic-api
ironic-inspector
runironic-conductor
ironic-dnsmasq
capm3
manager
bmo
manager
```

Add readiness and liveness probes

---

ironic-deployment/ironic/ironic.yaml

The liveness and readiness healthchecks for the ironic-dnsmasq container were using the $PROVISIONING_IP to determine whether the dnsmasq process was up and running properly. However, experimentally we've verified that the dnsmasq service can serve on port 69 bound to a different IP on the same subnet. This has caused flakes in the CI tests. It should be sufficient to check that some service is listening on port 69 for a sanity readiness / liveness check.

:bug: Remove provisioning IP from ironic-dnsmasq checks

---

OWNERS

Arda and Bob have both contributed substantial pieces of code and are
regular reviewers. Thus, they should have reviewer permissions as
documented at:
https://github.com/metal3-io/metal3-docs/blob/master/processes/managing-reviewers.md#proposal

Add ardaguclu and bfournie to reviewers

---

config/manager/manager.yaml
config/render/capm3.yaml
ironic-deployment/ironic/ironic.yaml

Fixes CentOS build failure on CentOS master/main by setting appropriate delays for health probes.
The ironic pod contains 7 containers and takes some time full start. The time it takes for all the containers to be up and running was measured and the delays in the PR were chosen accordingly. 
```
#!/bin/bash
echo "--------------start measurement: $(date)-------------------"
echo
kubectl scale deploy -n baremetal-operator-system baremetal-operator-ironic --replicas=1
while true; do
error=false
minikube ssh -- curl -sSfk https://127.0.0.1:6385 > /dev/null && echo "success, $(date), port: 6385" || error=true;echo "failure, $(date), port: 6385"
minikube ssh -- curl -sd '{}' -o ?~@~S -k https://127.0.0.1:8089 > /dev/null  && echo "success, $(date), port:8089" || error=true;echo "failure, …
```

Fixes CentOS build failure on CentOS master

---

.golangci.yml
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/hostfirmwaresettings_test.go
pkg/ironic/bmc/access_test.go
pkg/ironic/raid_test.go
pkg/provisioner/ironic/provision_test.go

golint is deprecated, and the deprecation notice suggests using "revive"

Replace deprecated linter & fix lint issues

---

apis/metal3.io/v1alpha1/preprovisioningimage_types.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/preprovisioningimage_controller.go
main.go
pkg/imageprovider/default.go
pkg/imageprovider/imageprovider.go

Create a new ImageProvider interface that the controller uses to obtain the image. The default implementation just obtains the URLs from environment variables as before, but is much easier to swap out for a new implementation than writing a separate controller.
Since custom controllers may need to cache data for each image, the controller needs to notify the image provider when a possibly cached image is no longer required. To this end, add a finalizer so that a cached image is cleared before a resource is deleted, and also mark the resource not ready when the config changes so that the existing image cache can be dropped.

Make PreprovisioningImage controller more generic

---

pkg/hardwareutils/bmc/access_test.go
pkg/hardwareutils/bmc/irmc.go

When adding iRMC type BMH in OCP environment, if `bootMACAddress` is not specified, the following error will occur:
```
Events:                              
Type    Reason             Age   From                         Message
----    ------             ----  ----                         -------
Normal  RegistrationError  47s   metal3-baremetal-controller  MAC address  conflicts with existing node openshift-machine-api~master-0
Normal  RegistrationError  47s   metal3-baremetal-controller  MAC address  conflicts with existing node openshift-machine-api~master-0
```
So modify the return value of `NeedsMAC` so that `bootMACAddress` must be specified when creating a BMH.

irmc: change the return value of NeedsMAC() to true

---

apis/metal3.io/v1alpha1/firmwareschema_types.go
apis/metal3.io/v1alpha1/hostfirmwaresettings_types.go
apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/metal3.io_hostfirmwaresettings.yaml
config/render/capm3.yaml
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/hostfirmwaresettings_controller.go
controllers/metal3.io/hostfirmwaresettings_test.go
pkg/provisioner/ironic/ironic.go

Change to use a poll cycle in the hfs reconciler to get data from Ironic instead of relying on state difference. In addition, the following changes were made to address follow-on comments in 
https://github.com/metal3-io/baremetal-operator/pull/938/.
- changed name of condition `UpdateRequested` to `FirmwareSettingsChangeDetected`
- add each hostFirmwareSettings as owner of its FirmwareSchema so that garbage collection will only be done when all removed
- Change the SetOwnerReference/SetControllerReference calls to before Create so the Update can be removed
- When building BIOS settings for cleaning make sure the hfs settings don't overwrite the vendor-agnostic settings
- When generating the hash for the firmwareSchema include the schema values in addition to the names

Change hfs controller to be level-triggered when handling bmh updates

---

controllers/metal3.io/preprovisioningimage_controller.go
pkg/imageprovider/default.go
pkg/imageprovider/invalid.go

Some failures to build images may be permanent, as opposed to transient
errors. Define a special error type that allows the imageprovider to
indicate a permanent failure, that is then reported in the CR.
Other errors are assumed to be transient and will continue to cause a
retry.

Add an interface for the image builder to report a failure

---

controllers/metal3.io/hostfirmwaresettings_controller.go

The password related fields aren't stored or settable in HostFirmwareSettings so these can also be removed from the schema.

Remove BIOS config password related settings from schema

---

apis/go.mod
apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go

Add validations to check if there are any invalid character(s) in the BMO resource name.

Add validations for bmo resource name

---

apis/metal3.io/v1alpha1/firmwareschema_types.go
controllers/metal3.io/hostfirmwaresettings_test.go

For HostFirmwareSettings, handle the case where a non-numeric string is set for an integer type.

Handle HostFirmwareSettings non-numeric string set for Integer type

---

apis/metal3.io/v1alpha1/firmwareschema_types.go
apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/metal3.io_firmwareschemas.yaml
config/render/capm3.yaml
pkg/provisioner/ironic/bios_test.go
pkg/provisioner/ironic/ironic.go

The reset_required field in the FirmwareSchema is both misleading and unnecessary. Changing HostFirmwareSettings is accomplished by resetting the host so this field doesn't provide any extra info; in addition not all vendors implement this field.

Remove reset_required from FirmwareSchema

---

docs/api.md
docs/dev-setup.md
docs/publishing-images.md
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/testserver/ironic.go

BMO's default branch is now `main`. This PR removes/updates any reference to `master` branch previously.

Add main branch reference instead of master

---

Tiltfile
tilt-provider.json

Update tilt-provider.json to add BMO label in Tilt UX. This [grouping feature](https://blog.tilt.dev/2021/08/09/resource-grouping.html) is supported in tilt version >= v0.22.2.
This patch provides two different grouping strategies:
- by controllers
- and local binaries
Also, the corresponding controller and binary will be grouped under 'BMO' group label as shown in the local Tilt setup using BMO,CAPM3&IPAM controllers.
Related patches in: [CAPM3](https://github.com/metal3-io/cluster-api-provider-metal3/pull/385)&[IPAM](https://github.com/metal3-io/ip-address-manager/pull/83).

✨Use grouping feature of Tilt to add BMO label

---

docs/api.md

Updated doc to match recent changes:
- Condition `UpdateRequested` renamed `ChangedDetected`
- Password settings are not returned in schema
- `reset_required` field is no longer in schema
- FirmwareSchema has a reference to each HFS using it

Minor doc fixes for HostFirmwareSettings

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine_test.go

This PR updates the error message in case of soft poweroff failure. 
Currently, the workflow when turning off a machine, BMO tries soft poweroff first. If failed, it performs a hard poweroff. The problem is that after soft poweroff fails, BMO would publish an error message got from ironic conductor, something like: `Failed to change power state to 'power off' by 'soft power off'. Error: Redfish exception occurred. Error: Setting power state to soft power off failed for node <node id>...`. This message can make user confused and think that this is a serious error and it can interrupt the poweroff workflow. 
This PR aims to clarify a bit more about the workflow by informing user about the followed hard poweroff after the soft one failure.

Update error message when soft poweroff fails

---

apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go

This PR adds some BareMetalHost validations as issued in #855.
* Invalid BMC Config
* RAID requested when not supported by driver
* Missing Boot MAC when required by driver
* BIOS requested when not supported by driver
* Add validations for BootMode

Add BareMetalHost validation

---

tools/run_local_ironic.sh

Ironic-image and ironic-ipa-downloader repos' default branch has been updated to main. Hence the latest image tag also changes to main.

Update ironic-image, ipa-downloader tag to main

---

controllers/metal3.io/hostfirmwaresettings_controller.go
controllers/metal3.io/hostfirmwaresettings_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go

For these types the value in clean steps should be stored as an integer, otherwise vendors reject the Redfish request.

Use integer value in clean steps for HostFirmwareSettings Integer type

---

pkg/hardwareutils/bmc/access_test.go
pkg/hardwareutils/bmc/irmc.go

Fixed iRMC server deployment failure during IPI.
See https://github.com/openshift/installer/issues/5504 for details.

Bug 2041765: irmc: change BootInterface to ipxe

---

apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
apis/metal3.io/v1alpha1/bmceventsubscription_webhook_test.go

Our intent is to make the subscription CR immutable; however, it doesn't
work if finalizers can't be added, or the spec updated.  Therefore, this
patch loosens the immutability requirement to the spec only.  This means
that any k8s bookkeeping can still happen, and we can prevent users from
changing existing subscriptions.

Make bmc subscription validator less aggressive

---

tools/remove_local_ironic.sh
tools/run_local_ironic.sh

This change also features significant simplifications to the way run_local_ironic works:
better defaults, automatic generation of TLS parameters, no requirement of kubectl.

Rework run_local_ironic to use combined Ironic

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_state_machine.go
controllers/metal3.io/host_state_machine_test.go
controllers/metal3.io/hostfirmwaresettings_controller.go
controllers/metal3.io/hostfirmwaresettings_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/prepare_test.go
pkg/provisioner/provisioner.go

Currently if the host is in the Available state and the HFS settings are changed it doesn't transition to the Preparing state as it would when the BareMetalHost settings are changed. This change fixes that.

Move from Available to Preparing if HostFirmwareSettings changed

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_state_machine.go
controllers/metal3.io/host_state_machine_test.go

The root device hints have a rotational field which is a pointer to a bool. Use DeepCopy and DeepEqual to ensure its handled properly.

Use deep copy/equal for host root device hints

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go

This may be needed e.g. to find linked objects.

Copy labels from BaremetalHost to PreprovisioningImage

---

docs/deploying.md
ironic-deployment/basic-auth/default/auth.yaml
ironic-deployment/basic-auth/default/kustomization.yaml
ironic-deployment/basic-auth/keepalived/auth.yaml
ironic-deployment/basic-auth/keepalived/kustomization.yaml
ironic-deployment/basic-auth/tls/default/auth.yaml
ironic-deployment/basic-auth/tls/default/kustomization.yaml
ironic-deployment/basic-auth/tls/keepalived/auth.yaml
ironic-deployment/basic-auth/tls/keepalived/kustomization.yaml
ironic-deployment/default/ironic_bmo_configmap.env
ironic-deployment/ironic/ironic.yaml
ironic-deployment/keepalived/ironic_bmo_configmap.env
ironic-deployment/tls/default/tls.yaml
ironic-deployment/tls/keepalived/tls.yaml
tools/deploy.sh
tools/run_local_ironic.sh

This change reduces the resource footprint of the installation and paves
the way to dropping MariaDB by default (not a part of this patch).

Switch the deployment to use a single ironic process

---

controllers/metal3.io/hostfirmwaresettings_controller.go
controllers/metal3.io/hostfirmwaresettings_test.go

Only update the HFS status if the settings from Ironic have changed or if the conditions were updated.
Currently the reconciler can run an additional time because the Status is updated on each pass.

Only update the HFS status on changes

---

pkg/hardwareutils/bmc/access_test.go
pkg/provisioner/ironic/raid.go
pkg/provisioner/ironic/raid_test.go

We need to use it in the terraform provider as well:
https://github.com/openshift-metal3/terraform-provider-ironic/pull/53.
Also remove no-op RAID testing bits from the access tests.

Expose CheckRAIDInterface from the RAID module

---

Dockerfile
Tiltfile

Hello, I am testing the baremetal-operator on arm, and noticed that this builds an arm container with an x86 image. I'd like to remove the hard-coded arch so the image builds based on the os arch.

Remove amd64 and linux to ensure multiarch container build

---

Makefile

I mistakenly thought `default` was the base of all Ironic
kustomizations, but it turns out `ironic` is the base, so that is where
we should set the image.
Edit: The problem is that some kustomizations depends on `ironic` directly instead of `default`, meaning that any changes made in `default` will not be picked up. See for example keepalived: https://github.com/metal3-io/baremetal-operator/blob/main/ironic-deployment/keepalived/kustomization.yaml

Fix make target for setting Ironic image

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/hostfirmwaresettings_controller.go

If the HFS status settings have not been populated, does not generate the
Invalid BIOS Setting events.
If the changes are detected, but the HFS status settings are empty, it waits
until hostFirmwareSettings are read.
Signed-off-by: tliu2021 <tali@redhat.com>

Check for empty HFS status settings

---

ironic-deployment/ironic/ironic.yaml

We are seeing failed jobs in the CI due to dnsmasq missing NET_RAW capability. This should solve the issue. But it would also be good to check with upstream what caused this change.

Add NET_RAW capability for dnsmasq

---

pkg/provisioner/ironic/ironic.go

I completely forgot that maintenance reason cannot be set directly. My bad.
Will build a proper change on top of https://github.com/gophercloud/gophercloud/pull/2384.
Reverts metal3-io/baremetal-operator#1088
Fixes #1113

Revert "Set maintenance reason when turning maintenance on"

---

apis/metal3.io/v1alpha1/preprovisioningimage_types.go
config/crd/bases/metal3.io_preprovisioningimages.yaml
config/render/capm3.yaml
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/preprovisioningimage_controller.go
pkg/imageprovider/default.go
pkg/imageprovider/imageprovider.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/validatemanagementaccess_test.go
pkg/provisioner/provisioner.go

Currently, we assume that the same kernel can be used for all images.
This is not the case in multi-arch scenarios. Add a new optional field
to pass a kernel from the provider.
Also add support for extra kernel parameters. These are required by
CoreOS to link to the correct rootfs.
Requires: https://review.opendev.org/c/openstack/ironic/+/837379

Allow image provider to override kernel and add kernel params

---

config/manager/manager.yaml
config/render/capm3.yaml
ironic-deployment/ironic/ironic.yaml

This is to make it easier to tell when the deployments are "available".
The default is to consider them available as soon as the pods have
started. But if there is some problem it is likely that the pods will
immediately crash. Therefore it makes sense to give them a few seconds
before we consider them available for real.
This is related to https://github.com/metal3-io/metal3-dev-env/issues/981 and https://github.com/metal3-io/metal3-dev-env/pull/983
It will be easier to check the health of the controllers when the deployments have `minReadySeconds` set.

Set minReadySeconds for BMO and Ironic

---

pkg/hardwareutils/bmc/access.go
pkg/hardwareutils/bmc/access_test.go

Adds a function to check if the bmc.address follows DNS standard and exports the GetParsedURL function to make it available in other validations.

Check if bmc hostname follows DNS Standard

---

ironic-deployment/basic-auth/default/auth.yaml
ironic-deployment/basic-auth/default/kustomization.yaml
ironic-deployment/basic-auth/keepalived/auth.yaml
ironic-deployment/basic-auth/keepalived/kustomization.yaml
ironic-deployment/basic-auth/tls/default/auth.yaml
ironic-deployment/basic-auth/tls/default/kustomization.yaml
ironic-deployment/basic-auth/tls/keepalived/auth.yaml
ironic-deployment/basic-auth/tls/keepalived/kustomization.yaml
ironic-deployment/certmanager/certificate.yaml
ironic-deployment/default/kustomization.yaml
ironic-deployment/ironic/ironic.yaml
ironic-deployment/keepalived/keepalived_patch.yaml
ironic-deployment/keepalived/kustomization.yaml
ironic-deployment/tls/default/kustomization.yaml
ironic-deployment/tls/default/tls.yaml
ironic-deployment/tls/keepalived/kustomization.yaml
ironic-deployment/tls/keepalived/tls.yaml
tools/deploy.sh

The Ironic kustomizations used envsubst to set the nameprefix, while BMO
was using the built in feature in kustomize. To unify them and simplify
the deploy script a bit, the Ironix kustomizations were changed to also
use the kustomize feature.
There is a slight change in the manifests since the namePrefix is
applied also to secrets, configmaps and label selectors that didn't have
the prefix set before.
The namespace is now also created as part of the kustomizations for
Ironic (same as for BMO).
Fixes #1072
Edit:
This breaks CAPM3 v1alpha4 (which is deprecated). The issue is that Ironic ends up in the wrong namespace. It is easily solve by copying the `ironic-cacert` secret to the namespace where BMO is running (`capm3-system`) or making changes to the Ironic manifests. However, v1alpha4 …

Get rid of envsubst for nameprefix

---

controllers/metal3.io/host_config_data.go

Report that NetworkData isn't available and return a
blank string id the sectret is present but doesn't contain
the expected key. This is the same as the behaviour when the
secret isn't present at all.

Stop treating missing network as fatal error

---

pkg/provisioner/ironic/ironic.go

The live-iso provisioning method does not require IPA to be booted on
the server, so don't fail if there is no PreprovisioningImage available.

Don't require pre-provisioning image for live ISO provisioning

---

tools/remove_local_ironic.sh

Some containers are no longer created in the run_local_ironic.sh script, so remove them from the list.

remove_local_ironic.sh: update the list of containers

---

ironic-deployment/ironic/ironic.yaml

It will be restarted because it is a path not in liveness probe
The default ironic deploy without ssl requires an http call.
```
[core:debug] [pid 26:tid 45] protocol.c(1447): [client 127.0.0.1:34436] AH00566: request failed: malformed request line
127.0.0.1 - - [23/Jul/2022:14:44:06 +0000] "\x16\x03\x01\x02" 400 226 "-" "-"
```

Fix ironic httpd readness & liveness Probe

---

pkg/provisioner/ironic/ironic.go

When creating a node with a 409 error, try again later.

Increase the handling of 409 errors when node creation fails

---

apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go

Validate host dns name part of BareMetalHost bmc address.

Validate Host DNS name in BareMetalHost resource

---

OWNERS

After following the process described in our community documents [1], there were no objections in adding Honza as an approver
[1] https://github.com/metal3-io/metal3-docs/tree/master/maintainers

add honza pokorny as approver

---

pkg/provisioner/ironic/adopt_test.go
pkg/provisioner/ironic/delete_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go

First, do not set the maintenance flag for nodes in manageable state,
it's not required.
Second, if the maintenance flag is on when we don't expect it and Ironic
does not report a fault, move the nodes off maintenance.
Finally, remove stale instanceUUID before deletion if it's present.

Handle maintenance more gracefully

---

docs/api.md
pkg/hardwareutils/bmc/access_test.go
pkg/provisioner/ironic/raid.go
pkg/provisioner/ironic/raid_test.go

The current code treats software RAID similarly to hardware RAID and
expects the driver's RAIDInterface value to be "agent" to use it.
This is never the case, as software RAID is not driver-specific.
This change adjusts the procedure to set the expected RAIDInterface
before setting the target configuration. This makes software RAID work
with any values of the driver's RAIDInterface.

Fix software RAID

---

apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go

Part of #855 
- Add validations for ImageUrl
- Add validations for Image.DiskFormat

Improve webhook verification

---

controllers/metal3.io/baremetalhost_controller_test.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>
t.Fatal* will report test failures and stop the test immediately.
**So some of the code is actually unreachable**
An example:
https://go.dev/play/p/5K3KZ5RzHhR
```go
package main
import (
"testing"
)
// LastIndex returns the index of the last instance of x in list, or
// -1 if x is not present.
func LastIndex(list []int, x int) int {
for i := len(list) - 1; i >= 0; i-- {
if list[i] == x {
return i
}
}
return -1
}
func TestLastIndex(t *testing.T) {
tests := []struct {
list []int
x    int
want int
}{
{list: []int{1}, x: 1, want: 0},
{list: []int{1, 1}, x: 1, want: 3}, // change want:1 to want:3, should fail
{list: []int{2, 1}, x: 2, want: 0},
{list: []int{1, 2, 1, 1}, x: 2, want: 1},
{list: []int{1, 1, 1, 2, 2, 1}, x: 3, want: -1},
{list: …
```

delete minor unreachable code in test caused by t.Fatal

---

apis/go.mod
go.mod

Please see #1082 for more information.
This PR seeks to resolve import errors when importing version `v0.1.0`
Resolves:
```sh
docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.32.2 golangci-lint run - 
level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: err: exit status 1: stderr: go: github.com/metal3-io/baremetal-operator/apis@v0.1.0 requires\n\tgithub.com/metal3-io/baremetal-operator/pkg/hardwareutils@v0.0.0: reading github.com/metal3-io/baremetal-operator/pkg/hardwareutils/pkg/hardwareutils/go.mod at revision pkg/hardwareutils/v0.0.0: unknown revision pkg/hardwareutils/v0.0.0\n"
```

🌱 Update versioning to match new package release versions

---

docs/configuration.md
pkg/provisioner/ironic/factory.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

When the BMC address is IPv6, we need to set the `external_http_url`
value on the node so that the node can access the provisioning image.

Set external_http_url on the node when BMC is IPv6

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
hack/markdownlint.sh

To have a better-structured way to formalize future issue/feature requests and pull requests. 
Adding a pull request template should also help with labeling the PRs since GitHub Actions filters the merged commits searching for prefix with the proper PR icons listed in https://github.com/metal3-io/baremetal-operator/blob/main/hack/tools/release_notes.go#L132-L161, and that in turn makes life easy during the release and sorting out changes in the CHANGELOG.
Once this is accepted and merged, reviewers and all contributors are urged to label their PRs' with appropriate label depending on the changes in the commit.

📖 Add issue and PR templates to the repository

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/preprovisioningimage_controller.go
pkg/secretutils/secret_manager.go

Secret may be shared across the several baremetal hosts. Delete the
controller flag which have been resricted the share.
Replaces https://github.com/metal3-io/baremetal-operator/pull/1073
Fix https://github.com/metal3-io/baremetal-operator/issues/1045

Delete controller flag for baremetalhost for secret

---

docs/configuration.md
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provisioncapacity_test.go

The limit was designed to avoid glitches when too many hosts DHCP or
boot from PXE. Virtual media requires neither, and with a pre-built ISO
is actually quite efficient.

Exclude hosts with virtual media from PROVISIONING_LIMIT

---

OWNERS

After following the process described in our community [documents][1], there were no objections to adding Kashif as an approver.
[1]: https://github.com/metal3-io/metal3-docs/tree/master/maintainers

Add Kashif Khan as approver

---

apis/metal3.io/v1alpha1/groupversion_info.go
pkg/provisioner/ironic/testserver/ironic.go

No idea why the CI does not complain, but the local build fails with:
pkg/provisioner/ironic/testserver/ironic.go:135: File is not `gofmt`-ed with `-s` (gofmt)

Run make fmt to fix issues

---

resources/keepalived-docker/Dockerfile

Proposing following improvements to keepalived Docker image build:
- Apt doesn't have stable CLI interface and it gives out warnings about it during build. Change `apt` to `apt-get`.
- Add `apt-get` clean to minimize image size.
- Change DEBIAN_FRONTEND from ENV to ARG to limit it to build time.
- Lock used base image to specific version of ubuntu (`ubuntu` -> `ubuntu:"22.04`) to avoid unexpected base OS upgrades + allows correct rebuilds later on

🌱 Dockerfile: use apt-get instead of apt

---

pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go

The demo and fixture provisioners had invalid MAC addresses hard coded. Now that we have validation of them it is necessary to have proper addresses for things to work.

🌱 Fix mac address for demo and fixture provisioners

---

docs/api.md
hack/markdownlint.sh

mdl 0.12 changes unordered list indentation rule default from 2 spaces to 3 spaces due Kramdown requirements.
https://github.com/markdownlint/markdownlint/pull/373
Pin markdownlint image to 0.12 (with SHA), and fix all markdown comply with mdl 0.12.
All other PR at the moment will fail to markdown check failure.

🌱markdown: pin mdl to 0.12 and fix complaints

---

controllers/metal3.io/hostfirmwaresettings_controller.go

The reconciler was endlessly re-queuing HostFirmwareSettings after the BMH was deleted. For BMH we treat missing resource as a special case that we don't re-queue to avoid this endless loop. This PR makes it the same for HostFirmwareSettings.
Fixes #1190

🐛 Fix endless requeue of HostFirmwareSettings

---

OWNERS

Following community standard, since Lennart has more than 10 commits, adding him as a reviewer here.

🌱 Add Lennart Jern as a reviewer

---

hack/shellcheck.sh

Pin shellcheck to 0.9.0 with digest.
Shellcheck 0.9.0 was released this morning. This way it is in line with other repositories, and pinned by digest.

🌱 shellcheck: pin to 0.9.0

---

go.mod
main.go
pkg/provisioner/ironic/factory.go

Refine the log data format from "1666158340.7038972" to "2022-10-19T05:45:40.674Z"
The original format is badly readable.
Fixes #

🌱 Refine ironic provisioner log data format

---

.github/workflows/kubesec.yml
.github/workflows/release.yaml

Set top-level permission to read, and allow write only where applicable.
Pin actions to a sha to prevent unwanted changes.

🐛 .github: secure github actions

---

Tiltfile
config/manager/manager.yaml
config/render/capm3.yaml

It is always good to not rely on the defaults, but be explicit. Set explicit, secure securityContext for the BMO controller manager deployment and containers.
CAPI has the same starting from upcoming v1.4.0 and cert-manager etc has them already.
Setting explicit securityContext has its downsides as well, for tilt. Tilt's live update cannot handle securityContext which sets the user as non-root, as it requires root to deploy the binaries on rebuild. To workaround this, strip function is added to Tiltfile to handle BMO securityContexts.
Also, reindent the manifest properly.

✨ add explicit securitycontexts to controller

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go

Currently, due to the way we compare these fields in Spec and Status,
we always trigger an update at least once. Avoid it if the fields are
completely empty.
Extract the root device hints function and call it when matching the
profile to avoid a new update later on.
Improve logging around the diff handling.

Do not consider empty RAID and root device hints updated

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/raid.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

Contrary to its name, ValidateManagementAccess also enrolls the node and
configures various deploy-related parameters. This change splits
cleaning, image, custom deploy and ramdisk settings to a new function
with a goal to eventually delineate them.
Fix tryUpdateNode to return the updated node.

🌱 Separate updating images from ValidateManagementAccess

---

Makefile

Fix the error that occur when executing `make docker` on a host that accesses the Internet through a proxy.
None.

:bug: Accept http_proxy/https_proxy from env when `make docker`

---

controllers/metal3.io/baremetalhost_controller.go

When BMH is deleted and NS is also in terminating state around the same time (usually GitOps/ArgoCD is involved), BMO may not be able to creating additional CRs as part of the deprovisioning steps. This condition essentially hangs the cleanup of BMH, its Secret (used for BMC) while the NS stays at a terminating state.
As long as registerHost is handling errors during this time, the issue goes away.
/cc @dtantsur
/cc @rhjanders
/cc @zaneb 
Fixes #

 🐛 allow namespace to continue terminating when bmh is deprovisioning at the same time

---

controllers/metal3.io/host_state_machine.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go

Not running cleaning immediately after a failure may:
1. cause side effects when the machine powers back on into the old
operating system (and e.g. rejoins the cluster as a worker);
2. confuse users with previous Ironic background since in Ironic a node
cannot enter available without going through cleaning (unless disabled).
This change moves hosts manageable -> available immediately. Users who want
to opt-out have to set automatedCleanMode to disabled or detach the host.
As of this change, we still give up cleaning after 3 attempts, so it's
still possible to end up with an unclean host causing issues.

:bug: Always retry failed cleaning on deprovisioning (fixes #1182)

---

config/OWNERS
ironic-deployment/OWNERS
resources/keepalived-docker/OWNERS
tools/OWNERS

As agreed with Kashif, these are obsolete OWNERS files, and they need to go. This way the review process falls to the root OWNERS.
fmyussarov is already emeritus approver on top-level.
/cc @kashifest @furkatgofurov7

🌱 remove old unnecessary OWNERS files

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine.go
controllers/metal3.io/host_state_machine_test.go

Delaying moving the host to deprovisioning or deleting allows other components to do whatever logic they need to do before BMO decides if the host should be deprovisioned or deleted.
In one specific case a finalizer could be added to a detached host which will attach the host to allow it to be cleaned at the time it is deleted. This logic needs to happen before BMO proceeds with its own delete logic.
@dtantsur PTAL

:seedling: Delay deprovision/delete when multiple finalizers exist

---

ironic-deployment/base/ironic.yaml
ironic-deployment/components/keepalived/keepalived_patch.yaml
resources/keepalived-docker/Dockerfile
resources/keepalived-docker/configure-nonroot.sh
resources/keepalived-docker/manage-keepalived.sh

BMO ironic has no reason to run as root. Make it run as "ironic" user.
dnsmasq requires elevated capabiities. k8s is missing the feature of ambient capabilities, so it requires us to setcap the binaries with expected capabilities and container must be running with "allowPrivilegeEscalation: true" in the manifest to allow elevation.
Read the ambient capabilities KEP for more details: https://github.com/kubernetes/enhancements/blob/master/keps/sig-security/2763-ambient-capabilities/README.md
Add securityContext to BMO deployment manifest and keepalived component, with correct UIDs and GIDs. This is important to be able to share files via /shared.
Modify keepalived image to run as ironic user, which we use the same UID and GID as the ironic-image.
This commit requires ironic-image with PR …

:warning: run BMO ironic deployment as non-root

---

cmd/make-bm-worker/templates/templates.go
cmd/make-virt-host/main.go
go.mod
go.sum

The library "text/template" is syntax-unaware and at risk of injection vulnerabilities. [More context](https://github.com/google/safetext).
Signed-off-by: Jie Yang <jieyangnku@gmail.com>
Fixes #

Replace package "text" with "google/safetext"

---

pkg/provisioner/ironic/ironic.go

For some reason, BMO creates nodes without the namespace~ prefix, then
updates them. This may cause conflicts between nodes belong to hosts
from different namespaces.

🐛 Create nodes with namespace already prepended

---

ironic-deployment/base/ironic.yaml
ironic-deployment/components/keepalived/keepalived_patch.yaml
ironic-deployment/components/mariadb/mariadb_patch.yaml
resources/keepalived-docker/Dockerfile
resources/keepalived-docker/configure-nonroot.sh
resources/keepalived-docker/manage-keepalived.sh

BMO ironic has no reason to run as root. Make it run as "ironic" user.
dnsmasq requires elevated capabiities. k8s is missing the feature of ambient capabilities, so it requires us to setcap the binaries with expected capabilities and container must be running with "allowPrivilegeEscalation: true" in the manifest to allow elevation.
Read the ambient capabilities KEP for more details: https://github.com/kubernetes/enhancements/blob/master/keps/sig-security/2763-ambient-capabilities/README.md
Add securityContext to BMO deployment manifest and keepalived component, with correct UIDs and GIDs. This is important to be able to share files via /shared.
Modify keepalived image to run as ironic user, which we use the same UID and GID as the ironic-image.
This commit requires ironic-image with PR …

⚠️ run BMO deployment as non-root (v2)

---

ironic-deployment/components/basic-auth/auth.yaml
ironic-deployment/components/basic-auth/kustomization.yaml
ironic-deployment/overlays/basic-auth_tls/basic-auth_tls.yaml

The htpasswd files for Ironic and Inspector contains clear text usernames and hashed passwords so it is better to store them in Secrets.
Depending on how exactly Ironic is deployed this could be a breaking change that requires manual action from the user.
I have tested this with the [deploy.sh](https://github.com/metal3-io/baremetal-operator/blob/main/tools/deploy.sh) script and confirmed that it is working. Re-deploying Ironic, with the updated kustomization using the script, automatically creates the new Secrets and configures Ironic and Inspector to use them instead of the ConfigMaps.
Note that the ConfigMaps are **not** automatically removed. Ideally, the user should remove the ConfigMaps and change the credentials. The ConfigMaps in question …

⚠️ Store htpasswd files in Secrets instead of ConfigMaps

---

apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go

This reverts commit 40986755ad389c5edc51e4feef045d3a6fb19e65 part of this PR - [https://github.com/metal3-io/baremetal-operator/pull/1107/commits](https://github.com/metal3-io/baremetal-operator/pull/1107/commits)
This validation is blocking pxe booting when live-iso image format is used along with non-virtualmedia drivers.
Fixes #

:bug: Revert live-iso validation as it is blocking pxe boot when non-virtualmedia drivers are used

---

.github/workflows/kubesec.yml
.github/workflows/release.yaml

Workflows use resources that are only available when run in the [metal3-io/baremetal-operator](https://github.com/metal3-io/baremetal-operator) repository, so workflow run would always fail when they run in a forked repository. They are of no value to fork repositories. They are triggered by the schedule event, so they cause regular annoying and confusing workflow failure notifications for every fork owner. Rather checking these workflows only in upstream repo is enough.

🌱 Disable scheduled workflows from running in forks

---

docs/dev-setup.md

Fix broken links in markdown files:
- dev-setup.md has broken link to virtualbmc.html, but vbmc documentation is moved elsewhere, and now it is more or less a placeholder as virtual.html
Broken link checker action is added in: https://github.com/metal3-io/baremetal-operator/pull/1254

📖 fix broken links in markdown files

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_state_machine_test.go
controllers/metal3.io/hostfirmwaresettings_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/provisioner.go

This change adds a new reboot variant:
```yaml
reboot.metal3.io: '{"force": true}'
```
This reboot mode works in available, provisioning and inspecting states.
Includes:
- https://github.com/metal3-io/baremetal-operator/pull/1240

✨ Supported forced reboot of preprovisioning images

---

main.go
pkg/provisioner/ironic/factory.go

Previously the ironic provisioner log was created in a separate module,
and didn't have access to the CLI arguments. Originally the provisioner
was always in structured mode even when the -dev flag was passed to put
it into development mode, and then after #1175 vice-versa.
Create the provisioning logger in main.go using the same settings as the
controller logger, and pass it in to the provisioner factory. Only change the
timestamp formatting in development log mode.

Use same settings for provisioner and controller logs 

---

Dockerfile

Change distroless from base:latest to static:nonroot like other controller images, and pin it with sha digest.

🌱 pin distroless to static:nonroot with sha digest

---

docs/releasing.md

Update releasing.md to refer to main process documentation for post-release steps.
1. Link to the metal3-docs releasing.md
2. Fix the go module tagging not to be annotated (release workflow might get messed up, only primary tag to be annotated)

📖 update releasing.md with links to main process

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
config/crd/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml
pkg/provisioner/ironic/devicehints/devicehints.go
pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go

Allow paths of the form `/dev/disk/by-path` in the root device hints field.
By-path support is needed because it is the only method of identifying a disk that is stable and doesn't require knowledge of the components of a particular server (e.g. the drive serial number). In particular, HCTL (which you might think would do that) is not stable because the H part is numbered in the order the SCSI hosts are discovered by the kernel.
Support for by-path was previously discussed in #317, but in that case it was proposed to add a separate field. This PR reuses the same field, so you can specify either device name. This avoids the weirdness of two separate fields, each containing a Linux device path, at the possible cost of confusing people into thinking that _any_ Linux device path is valid. To …

:sparkles: Support /dev/disk/by-path root device hints

---

Dockerfile

Bump golang for controller image to 1.19.9

:seedling: bump golang image from 1.19.6 to 1.19.9

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

Currently, if e.g. the deploy ISO has changed, BMO will try to update
the node. Such updates cannot work in most transient states, causing
the reconciler to return early with an error.

🐛 Do not try to update images for nodes in transient states

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine.go
controllers/metal3.io/host_state_machine_test.go

Ironic doesn't do any work to speak of in the host's 'deleting' state. It appears this was added (in c3c2c8841ca3ebe0341d4c6336346c397bdd99a2) due to confusion between ironic's 'deleting' (i.e. the 'deprovisioning' state in Metal³) and Metal³'s 'deleting' state.
A result of this was that hosts in the 'unmanaged' state could not be deleted, because by definition they do not have BMC credentials, but the check for Ironic capacity required them. Since unmanaged hosts do not go through 'deprovisioning', removing this unnecessary check from the 'deleting' state should be enough to allow them to be deleted again.

:bug: Don't check for ironic capacity in 'deleting' state

---

controllers/metal3.io/baremetalhost_controller.go

Five minutes is a lot. Neither the built-in image provider nor the one
we have in OpenShift takes so much to build images.

🌱 Reduce the preprovisioning image retry delay

---

controllers/metal3.io/baremetalhost_controller.go

Quoting @zaneb:
> Hold on, the controller is [watching](https://github.com/metal3-io/baremetal-operator/blob/main/controllers/metal3.io/baremetalhost_controller.go#L1747) the PreprovisioningImage so it will be notified immediately when something changes.
> This delay is for how long before we pointlessly requeue the BMH when nothing has changed. If anything it should maybe be longer than 5 minutes so that we don't pointlessly hammer the API when e.g. the preprovisioning image controller is down.
> I think we should revert this.
Reverts metal3-io/baremetal-operator#1275

Revert "🌱 Reduce the preprovisioning image retry delay"

---

apis/metal3.io/v1alpha1/profile/profile.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine_test.go
pkg/provisioner/ironic/updateopts_test.go
pkg/provisioner/provisioner.go

Since this code now defines how we map one API concept (the hardware profile string) to default values for other API concepts (root device hints), it is effectively part of the API definition. It is also not expected to exist in future API versions. The webhook for translating hosts between versions will need to access this code, so it will need to be inside the API module. Finally, similar to the hardwareutils module, this is useful in other contexts and moving it out of the main module eliminates extraneous external dependencies being dragged with it.

Move hardware profile code to the api module

---

Dockerfile

Fix the way nonroot is part of the image pinning.

🐛 fix distroless:nonroot pinning

---

.github/dependabot.yml
.github/workflows/dependabot.yml
Makefile

This PR adds dependabot configuration which enables dependabot to automatically open PRs for bumping go modules and tags while ignoring a few of the gomodule update for example controller-runtim or k8s.io/* for manual bumping. This will run as a github workflow.

 🌱 Add dependabot workflow and configuration

---

go.mod
go.sum
pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
pkg/provisioner/ironic/hardwaredetails/hardwaredetails_test.go

The core inventory has all we need. Extra comes from a plug-in that
may not be present (e.g. in upstream IPA images).

🌱 Stop using Extra when building hardware inventory

---

pkg/hardwareutils/bmc/access_test.go
pkg/hardwareutils/bmc/ibmc.go

All other drivers use either iPXE or virtual media. Our ironic-image
does not even configure plain PXE properly, so it's not usable.
In any case, all in-tree network booting drivers should use iPXE
for consistent user experience.

⚠️ Change iBMC to use iPXE instead of PXE

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_state_machine_test.go

Remove duplicate declaration of annotation constants in Controller
Fixes #

:bug: Remove duplicate declaration of annotation constants outside metal3api

---

main.go

The default in controller-runtime is for the minimum TLS webhook version to be TLS 1.0, which is pretty long in the tooth. We should set this explicitly.

Set minimum TLS version for webhook

---

go.mod
go.sum
main.go
main_test.go

Added tls configuration flags for bmo.
This enables flags `--tls-min-version` and `--tls-max-version` flags, which can be used to limit TLS versions server accepts. Choices are `TLS12` and `TLS13`, so you can force TLS 1.2 only, TLS 1.3 only, or (default) TLS 1.2 and TLS 1.3 is negotiated between server and client.
This also disables TLS 1.0 and TLS 1.1 as they're insecure and obsolete and not supported by Go TLS library.

:sparkles: Add TLS configuration flags for BMO

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/preprovisioningimage_controller.go

The default meaning of the Owns() method in the controller-runtime controller is to only trigger reconciles on owner references where we have the 'controller' flag set.
We have never set the 'controller' flag on the networkData Secret used in both the BareMetalHost and PreprovisioningImage controllers.
Since #1164 we no longer set the 'controller' flag on our owner references for Secrets either, in order to allow the same BMC Secret to be shared amongst multiple hosts.
In each of these case we were either never or no longer triggering a reconcile when the Secret changed. Add the MatchEveryOwner option to ensure that we still trigger a reconcile even when the 'controller' flag is not set in the owner reference.
Fixes #1321

:bug: Trigger reconcile on Secret change

---

main.go

Fixed the code quality issues mentioned in [1320](https://github.com/metal3-io/baremetal-operator/issues/1320)

:seedling: Fix code quality issues in BMO TLS configuration code

---

hack/golint.sh

Run docker as same uid as user, so Git doesn't complain about directory ownership. This makes linting work locally as well.

🌱 fix issue with git directory ownership in golint

---

.gitignore
hack/tools/release_notes.go

- Add missing empty link after release image before thanking contributors
- Add superseded or reverted category, which is filled manually but present 99% every time, so it is consistent

📖 improve release notes tool

---

config/basic-auth/default/kustomization.yaml
config/basic-auth/tls/kustomization.yaml
config/crd/kustomization.yaml
config/default/kustomization.yaml
config/kustomization.yaml
config/tls/kustomization.yaml
ironic-deployment/components/basic-auth/kustomization.yaml
ironic-deployment/components/keepalived/kustomization.yaml
ironic-deployment/components/mariadb/kustomization.yaml
ironic-deployment/components/tls/kustomization.yaml
ironic-deployment/overlays/basic-auth_tls/kustomization.yaml

building kustomize layers with kustomize v5 outputs warnings of deprecation
```
$ kustomize build default/ > render/capm3.yaml 
```

⚠️ adopt manifests for kustomize v5

---

pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go

Ironic provides enough information, we need to get rid of direct
Inspector calls eventually. This change significantly simplifies
the logic by using the existing call to fetch data to detect when
an inspection still needs to be started.
Add a missing unit test for the refresh argument.

🌱 Stop using Inspector API for inspection status

---

.github/dependabot.yml

Running dependabot weekly for GH actions is excessive. Each bump needs to be pruned in release notes etc. Change `weekly` to `monthly` for GH actions. Security updates will ignore these schedules anyways.

:seedling: run dependabot less often

---

hack/gosec.sh

Run gosec for each submodule separately.
Gosec is otherwise using the root go.mod instead of what is in the submodule.
Fixes #

🌱 Gosec: Run submodules separately

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/bmceventsubscription_controller.go
controllers/metal3.io/hostfirmwaresettings_controller.go
controllers/metal3.io/preprovisioningimage_controller.go
main.go

This PR adds concurrency in controllers through command line flags

🌱  Enable concurrency in BMO controllers through cmdLine flags

---

docs/releasing.md

Clarify module tagging instructions one more time. Signing is also creating annotated tags. Also add reminder to push the tags too.

:book: clarify tag usage in releasing.md

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_config_data.go
controllers/metal3.io/host_config_data_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

Ironic supports [DHCP-less provisioning](https://docs.openstack.org/ironic/latest/admin/dhcp-less.html), which I expected to work via Metal<sup>3</sup>, particularly since we already provide the [IPAM controller](https://github.com/metal3-io/ip-address-manager) which can be used to statically assign control plane IPs.
[Recent discussions](https://kubernetes.slack.com/archives/CHD49TLE7/p1695719774588889) however highlighted that this flow is not currently possible via Metal<sup>3</sup>, unless you implement a custom `PreprovisioningImage` controller, or have other downstream customisations.
In the case where `--build-preprov-image` is passed to BMO, we enable creation of the `PreprovisioningImage` CR and an internal default controller (which does …

:sparkles: Pass preprovisioningNetworkData to Ironic

---

hack/e2e/ensure_go.sh

Right now ensure_go.sh gives an error while e2e tests locally even when the go version is greater than MINIMUM_GO_VERSION which is wrong. This PR is fixing it, we already have this script working in CAPM3, this PR is just taking code from there. Check here: https://github.com/metal3-io/baremetal-operator/blob/783eb742630067146b4b98173c32a3d96348778a/hack/e2e/ensure_go.sh#L25C12-L25C12

🌱 Fixing ensure-go script to allow go versions greater than MINIMUM_GO_VERSION

---

.gitignore
Makefile
hack/ci-e2e.sh
hack/clean-e2e.sh
test/e2e/basic_provisioning_test.go
test/e2e/config/fixture.yaml
test/e2e/config/ironic.yaml

Introduce an end-to-end test validating the provisioning and deprovisioning flow of a BareMetalHost.
Fixes #1367

🌱 Implement BMH provisioning E2E test

---

test/go.mod
test/go.sum

Bump CAPI to v1.5.3, while fixing inconsistencies in the modules, and removing unnecessary replace that was even further changing the version.
Inconsistencies spotted via #1407

🌱 bump CAPI to v1.5.3

---

.gitignore
test/e2e/config/fixture.yaml
test/e2e/config/ironic.yaml
test/e2e/re_inspection_test.go

🌱 Re-inspection by annotation test added

---

README.md

 📖 Add release-0.3 branch test triggers in README

---

hack/ci-e2e.sh
hack/clean-e2e.sh
test/e2e/config/ironic.yaml
test/e2e/sushy-tools/sushy-emulator.conf

This PR augments the e2e testing framework by integrating sushy-tools and Redfish, enhancing test coverage across different management interfaces alongside the existing VBMC and IPMI tests.
Fixes #1374

🌱 Integrate sushy-tools and Redfish into e2e testing

---

apis/go.mod
apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
apis/metal3.io/v1alpha1/baremetalhost_webhook.go
apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go
apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go

Logging:
- Rename the webhook loggers for consistency and easier grepping
- Remove redundant logging from the validation code
Errors:
- Provide wrapped errors in a consistent fashion
- Do not refer to internal constant names in user-visible strings
- Provide allowed values when saying that something is not allowed
- Use the stdlib error routines instead of the deprecated pkg/errors.
- Do not shadow the errors package name by local variables

🌱 Clean up logging and error handling in the webhooks

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

Doing so may interfere with cleaning. Updates to deploy_interface will
be rejected by Ironic, causing BMO to enter infinite reconcile retries.

🐛 Do not update instance_info and deploy_interface for active nodes

---

main.go

Structured logging tools expect a POSIX timestamp. 0a887a16fb26dd26a2b372953ec8d860a3a251b5 reverted to changing the timestamp formatting only in development log mode, after 9ecf1718dfe3f785e151b6d2b5a01ba04e0a00a9 had explicitly and unconditionally set the format to ISO-8601.
However, almost immediately after this, 5bf044038b17aec6c2265d325046f475bc4bb52f bumped the controller-runtime version from 0.13.1 to 0.14.5. In 0.14, the default zap options in controller-runtime [changed to RFC3339](https://github.com/kubernetes-sigs/controller-runtime/commit/60e524b7f4a6264662adfd1a2bd3e40b75393270) - which is the same as ISO-8601 but even worse because subsecond precision (which can be very important to debugging) is lost as well.
This change explicitly restores the original default.

:bug: Don't munge timestamp in structured logs, again

---

test/e2e/basic_provisioning_test.go
test/e2e/config/fixture.yaml
test/e2e/config/ironic.yaml

Validate BMH status retention across delete & recreate with annotations.
Fixes #1368

🌱 Implement Detached/Status Annotation E2E Test

---

.github/workflows/e2e-fixture-test.yml
test/e2e/basic_ops_test.go
test/e2e/basic_provisioning_test.go
test/e2e/config/ironic.yaml
test/e2e/external_inspection_test.go
test/e2e/inspection_test.go
test/e2e/re_inspection_test.go

Implement lightweight fixture-based tests to ensure CI platform flexibility.
Fixes #1406

🌱 Add github workflow for e2e fixture tests

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/bmceventsubscription_controller.go
controllers/metal3.io/host_state_machine_test.go
controllers/metal3.io/hostfirmwaresettings_controller.go
go.mod
go.sum
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/adopt_test.go
pkg/provisioner/ironic/clients/client.go
pkg/provisioner/ironic/clients/features.go
pkg/provisioner/ironic/configdrive_test.go
pkg/provisioner/ironic/delete_test.go
pkg/provisioner/ironic/dependencies.go
pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/power_test.go
pkg/provisioner/ironic/provision_test.go
pkg/provisioner/ironic/ready_test.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/ironic/updatehardwarestate_test.go
pkg/provisioner/ironic/validatemanagementaccess_test.go
pkg/provisioner/provisioner.go

Rather than bumping the microversion every time we need new features,
we will keep the baseline version and try to negotiate a higher version
in the provisioner. The new AvailableFeatures object provides
information about the supported features.
Includes:
- https://github.com/metal3-io/baremetal-operator/pull/1433

✨ Implement API version negotiation

---

pkg/provisioner/ironic/adopt_test.go
pkg/provisioner/ironic/configdrive_test.go
pkg/provisioner/ironic/delete_test.go
pkg/provisioner/ironic/dependencies.go
pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/power_test.go
pkg/provisioner/ironic/provision_test.go
pkg/provisioner/ironic/ready_test.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/ironic/updatehardwarestate_test.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

In preparation for the future microversion negotiation handling:
1) Remove the unnecessary ironicDependenciesChecker abstraction.
It probably made more sense when Inspector was used explicitly.
2) Change tests to make Ready the default state (and NotReady
an explicit override for the few tests that need it).

🌱 Refactor handling the provisioner's ready status

---

pkg/hardwareutils/bmc/redfish.go
pkg/hardwareutils/bmc/redfish_virtualmedia.go

Enable the redfish and redfish-virtualmedia RAID interfaces so that RAID can be configured using these interfaces.

🌱 Enable the Redfish RAID interfaces

---

test/e2e/basic_ops_test.go
test/e2e/basic_provisioning_test.go
test/e2e/common.go
test/e2e/config/fixture.yaml
test/e2e/external_inspection_test.go
test/e2e/inspection_test.go
test/e2e/re_inspection_test.go

**What this PR does**:
As the title says
Fixes #1436

🌱 Implement Helper Functions for E2E Tests

---

go.mod
go.sum
pkg/hardwareutils/bmc/access.go
pkg/hardwareutils/bmc/access_test.go
pkg/hardwareutils/bmc/ibmc.go
pkg/hardwareutils/bmc/idrac.go
pkg/hardwareutils/bmc/idrac_virtualmedia.go
pkg/hardwareutils/bmc/ilo4.go
pkg/hardwareutils/bmc/ilo5.go
pkg/hardwareutils/bmc/ipmi.go
pkg/hardwareutils/bmc/irmc.go
pkg/hardwareutils/bmc/redfish.go
pkg/hardwareutils/bmc/redfish_virtualmedia.go
pkg/provisioner/ironic/clients/features.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/prepare_test.go
pkg/provisioner/ironic/testbmc/testbmc.go

Ironic introduced a new interface called Firmware Interface This commit aims to addapt existing code to support creating nodes with the new field.
- Rename "firmwareUpgrades" to "firmwareUpdates", since this
can be used for upgrades and downgrades.
- gophercloud updated to a newer version
* go get -v github.com/gophercloud/gophercloud@master
* go mod tidy
- All BMCs have now FirmwareInterface() with default values
- Ironic provisioner updated to receive FirmwareInterface when creating a node
Exposes the firmware interface field that was introduced in ironic and will help in future work of  metal3-io/metal3-docs#364

✨ Expose  FirmwareInterface in Node/BMC

---

Dockerfile
Makefile
hack/e2e/ensure_go.sh

Bump golang version to 1.20.11 which will fix security vulnerability [CVE-2023-45284](https://osv.dev/vulnerability/GO-2023-2186)

 🌱Bump golang version to 1.20.11

---

.github/dependabot.yml

Dependabot recently is creating quite a few unnecessary PRs which need to be closed manually, having ok-to-test creates a lot of unneeded tests. Removing the label would allow adding labels selectively by reviewers and save some test bandwidth

🌱 Delete "ok-to-test" label from dependabot PRs

---

hack/markdownlint.sh

Bump markdownlint to 0.13.0. No extra fixes needed in BMO, and this should be cherry-picked to release branches to keep project-infra config simpler.
Simplify the ignore rules by not adding everything but two rules, but just ignore the two rules we violate. Added also TODO item to fix those in future commit.
TODO: bump the image in project-infra when all bump PRs are merged.

🌱 bump markdownlint to 0.13.0

---

hack/ci-e2e.sh
hack/clean-e2e.sh
hack/e2e/net.xml
test/e2e/common.go
test/e2e/config/fixture.yaml
test/e2e/config/ironic.yaml
test/e2e/external_inspection_test.go
test/e2e/live_iso_test.go
test/e2e/re_inspection_test.go
test/go.mod

🌱E2e live iso ssh implementation

---

hack/gosec.sh

Manual cherry-pick of #1474.
It also backports #1362 that makes gosec.sh actually do something for non-root modules.

🌱 bump gosec to 2.18.2

---

hack/ci-e2e.sh

🌱 e2e: Enhanced Serial Log Checking Functionality 

---

hack/ci-e2e.sh
hack/e2e/ensure_htpasswd.sh

🐛 Fix htpasswd command not found

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
apis/metal3.io/v1alpha1/baremetalhost_types_test.go
cmd/make-bm-worker/main.go
config/base/crds/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml
docs/api.md
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go
pkg/provisioner/ironic/validatemanagementaccess_test.go
test/e2e/basic_provisioning_test.go

In preparation for the eventual removal of MD5 checksums, add a new
ChecksumType "auto" that instructs IPA to detect the type
Requires IPA from the 2023.2 release series. Users with older IPA
should provide the algorithm explicitly.

✨ Add an explicit way to auto-detect ChecksumType

---

hack/ci-e2e.sh
test/e2e/config/ironic.yaml

The goal is to be able to run jobs with vbmc and sushy-tools in
parallel. The archives must then have unique names so that they don't
overwrite each other in jenkins.
Provisioning seems to take longer with VBMC so timeout is also
increased.
Fixes #

🌱 E2e: Name artifacts based on emulator

---

test/e2e/common.go
test/e2e/e2e_suite_test.go

This PR refactors and uses a common function to install ironic and bmo. This will be useful later should we have to install other stuff with kustomize.

🌱 E2E: Have a common function to install BMO and Ironic

---

Makefile

We're overlapping our version numbers with really old version numbers, ie. capm3-v0.4.1 vs v0.4.1 when using grep without line-start ^. Fix the issue, so the correct previous tag is used in release automation.

📖 fix previous release detection in make release-notes

---

Dockerfile
Makefile
hack/e2e/ensure_go.sh

There are some vulnerabilities that are fixed in 1.20.12. They're not affecting us, but scanners nag, so might as well bump.

🌱 bump golang to 1.20.12

---

.github/workflows/build-images-action.yml

This PR adds an action to trigger the bmo and keepalived container builds whenever a PR is merged in this repo.

🌱 Add github action to trigger container images build

---

README.md

Update build badges for 0.5 branch to show 1.6 integration job results.

📖 update build badges

---

.github/workflows/build-images-action.yml
.github/workflows/dependabot.yml
.github/workflows/e2e-fixture-test.yml
.github/workflows/kubesec.yml
.github/workflows/lint-docs.yaml
.github/workflows/pr-verifier.yaml
.github/workflows/release.yaml

Move permissions from top-level to job-level as well.
Cleanup actions formatting to be the same for easier reading and maintenance. Add missing version tags.
These is highlighted by the CLOmonitor/OpenSSF Scorecard. This restores score for token permissions to 10/10.
/hold
until https://github.com/metal3-io/ip-address-manager/pull/408 is reviewed and merged.

🌱 reduce github actions permissions

---

Makefile

There's a difference between the ginkgo cli version and ginkgo version that e2e uses:
https://github.com/Nordix/baremetal-operator/blob/main/test/go.mod#L9
https://github.com/Nordix/baremetal-operator/blob/main/Makefile#L27
Error log:
```bash
Ginkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:                                                             
Ginkgo CLI Version:                                                                                                                                                      
2.13.0                                                                                                                                                                 
Mismatched package versions found: …
```

🐛 Fix ginkgo version mismatch between cli and import package in e2e

---

.markdownlint-cli2.yaml
CONTRIBUTING.md
docs/api.md
docs/configuration.md
docs/deploying.md
docs/dev-setup.md
hack/markdownlint.sh
ironic-deployment/README.md
test/e2e/README.md

Switch markdownlint container to markdownlint-cli2. This CLI version supports the enable/disable rules in markdown files and allows us to ignore issues locally, not just globally.
- project-infra PR https://github.com/metal3-io/project-infra/pull/619 needs to merge for markdownlint here to pass

:book: switch markdownlint container to markdownlint-cli2

---

README.md
test/e2e/README.md

This adds the trigger phrases for the e2e tests to the README.md and also the build badge for the periodic job.
Fixes #

📖 Add trigger phrases and status badge for e2e tests

---

Makefile
hack/ci-e2e.sh
hack/clean-e2e.sh
hack/create_bmcs.sh
hack/e2e/ensure_yq.sh
hack/e2e/net.xml
test/e2e/README.md
test/e2e/basic_ops_test.go
test/e2e/bmc.go
test/e2e/common.go
test/e2e/config/bmcs-fixture.yaml
test/e2e/config/bmcs-sushy-tools.yaml
test/e2e/config/bmcs-vbmc.yaml
test/e2e/config/fixture.yaml
test/e2e/config/ironic.yaml
test/e2e/e2e_suite_test.go
test/e2e/external_inspection_test.go
test/e2e/inspection_test.go
test/e2e/live_iso_test.go
test/e2e/provisioning_and_annotation_test.go
test/e2e/re_inspection_test.go
test/e2e/upgrade_test.go

 🌱 Enable parallel testing in E2E

---

hack/clean-e2e.sh
tools/bmh_test/clean_local_bmh_test_setup.sh

Fixes #1531
This PR takes the `tools/bmh_test/clean_local_bmh_test_setup.sh` into use:
- Removed `-e` as many operations could fail, but the script should keep going

🐛 Fix VM selection in clean-e2e.sh

---

tools/run_local_ironic.sh

This change will introduce the configuration options necessary to run locally deployed (local container no K8s) Ironic with customized TLS enabled iPXE.
Currently the custom iPXE firmware is being produced in the metal3-dev-env when this feature is enabled.
This PR should not cause any issue if merged, but the feature supported in this PR will become available only after https://github.com/metal3-io/ironic-image/pull/429 is merged.

:seedling: add iPXE TLS support to local ironic deployment

---

config/default/kustomization.yaml

🐛 Fix an indentation error in kustomization file regarding ironic configmap generator

---

test/e2e/config/fixture.yaml

Add the interval 'wait-power-state' to our fixture test to fix a flake.

🌱 Add 'wait-power-state' interval to fixture test for flake fix

---

.github/workflows/e2e-fixture-test.yml

We're facing many failures in GH-action-based E2E fixture tests. This is likely due to the github VM is too small and cannot handle two gingko threads.

:seedling: Reduce GH fixture test GINKGO_NODES to 1

---

hack/ci-e2e.sh

The variables used for setting basic auth credentials were not exported, meaning that envsubst did not pick them up. This caused the auth config to have empty values.
Fixes #

🌱 E2E: Fix basic auth config

---

test/e2e/common.go
test/e2e/e2e_suite_test.go
test/e2e/upgrade_test.go

This PR adds Ironic and BMO to the cleanup phase in upgrade tests. This is needed as a preparation for multiple upgrade tests (multiple versions of BMO upgrade + ironic upgrade), as the test has to start from a clean state (with no Ironic nor BMO).
We also move installation of Ironic and BMO to the `It{}`, as it's more related to the test itself, rather than a preparation.
Notice that this change has allowed the test to be ran multiple times using the same cluster, as followed:
```
export GINKGO_FOCUS=upgrade
hack/ci-e2e.sh # first time
export UPGRADE_DEPLOY_CERT_MANAGER=false
<extra exports normally handled by ci-e2e.sh>
make test-e2e # As many times as needed
```
We could apply this to the required e2e tests as well if running multiple times is a requirement. That's not the main focus …

🌱 Add ironic and bmo cleanup for upgrade BMO E2E tests

---

apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

Allow BMC address to be updated if the BMH is in the Registering state or is detached.
This allows the BMC address to be updated if there are changes in the BMC network, or if a mistake was made when setting it the first time.

🌱 Allow BMC address to be updated

---

docs/dev-setup.md

This PR updates the project's documentation to include an alternative method for setting up the development environment using Tilt and Kind.

📖 Add alternative Tilt setup method to documentation

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/bmceventsubscription_controller.go
controllers/metal3.io/host_config_data_test.go
controllers/metal3.io/host_state_machine_test.go
controllers/metal3.io/hostfirmwaresettings_controller.go
controllers/metal3.io/preprovisioningimage_controller.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/factory.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/ironic_test.go
pkg/provisioner/provisioner.go
pkg/secretutils/secret_manager.go

There is no compelling reason to use TODO/Background: we have context available in reconcilers.
GopherCloud 2.0.0-beta2 will require context in its calls, so also pass the context to the provisioner.

🌱 Use real Context and make provisioners context-aware

---

hack/ci-e2e.sh

There is a bug in the [new docker release](https://github.com/google/go-containerregistry/issues/1870) that [affects minikube image load](https://github.com/kubernetes/minikube/issues/18021). While we wait for a new minikube release, we can work around the issue by exporting the image to an archive and load it from there instead.
Fixes #

🌱 E2E: Workaround issue with minikube image load

---

cmd/get-hardware-details/main.go
go.mod
go.sum
hack/e2e/ensure_go.sh
pkg/provisioner/ironic/adopt_test.go
pkg/provisioner/ironic/capabilities_test.go
pkg/provisioner/ironic/clients/client.go
pkg/provisioner/ironic/clients/features.go
pkg/provisioner/ironic/configdrive_test.go
pkg/provisioner/ironic/delete_test.go
pkg/provisioner/ironic/dependencies.go
pkg/provisioner/ironic/factory.go
pkg/provisioner/ironic/findhost_test.go
pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go
pkg/provisioner/ironic/hardwaredetails/hardwaredetails_test.go
pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/power_test.go
pkg/provisioner/ironic/prepare_test.go
pkg/provisioner/ironic/provision_test.go
pkg/provisioner/ironic/provisioncapacity_test.go
pkg/provisioner/ironic/raid.go
pkg/provisioner/ironic/raid_test.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/ironic/testserver/ironic_test.go
pkg/provisioner/ironic/update_opts.go
pkg/provisioner/ironic/updatehardwarestate_test.go
pkg/provisioner/ironic/updateopts_test.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

Although the current version is specified as 1.5.1, it's actually
a commit somewhere in the 2.0 branch. This change brings us to
a more specific version.
2.0.0-beta2 introduced a requirement on Context for all calls.

⚠️ Update to gophercloud 2.0.0-beta2

---

OWNERS

This PR adds 
@lentzi90 as an approver
@Rozzii as a reviewer
Thanks a lot folks for your continuous efforts and contributions to this repository. Keep up the good work. 
And also moves the following people to emeritus since their focus has shifted elsewhere:
@andfasano 
@ardaguclu 
@bfournie 
@dukov 
@furkatgofurov7 
Thanks a lot folks for all your efforts and your contributions you have made to this repository. Best of luck.

🌱 Update OWNERS file

---

.github/workflows/build-images-action.yml

It is needed in release branches as well.
/hold
Until tag building is verified in IPAM release branch first.

🌱 add build image action to release-0.5

---

Dockerfile
Makefile

Golang 1.20 is out of support in Feb 2024. Bumping golang image only in dockerfile, but not go.mod because it will break library consumers.

🌱 Bump go to v1.21.7

---

test/e2e/common.go
test/e2e/e2e_config.go

As titled. The e2e config related functionalities is growing, and we should have a separate file for it.

:seedling: Move e2e config functionality to a separate file

---

apis/go.mod
apis/go.sum
docs/dev-setup.md
go.mod
go.sum
test/go.mod
test/go.sum

🌱 Bump CAPI to v1.5.6

---

pkg/provisioner/ironic/clients/features_test.go

:seedling: Add unit test on features.go

---

.gitignore
test/e2e/basic_ops_test.go
test/e2e/external_inspection_test.go
test/e2e/inspection_test.go
test/e2e/live_iso_test.go
test/e2e/provisioning_and_annotation_test.go
test/e2e/re_inspection_test.go
test/e2e/upgrade_test.go

:seedling: E2E: Add labels on test coverage

---

.github/workflows/e2e-fixture-test.yml

Adding release-* as branch trigger to e2e fixture workflow, so when the next release branch is cut, we get e2e fixture triggering correctly.
This doesn't enable e2e fixture for branches that do not have this workflow file themselves, so right now we only support e2e fixtures in main and release-0.5.

🌱 add release-* as branch trigger to e2e fixture workflow

---

docs/deploying.md
hack/ci-e2e.sh
ironic-deployment/components/basic-auth/auth.yaml
ironic-deployment/components/basic-auth/kustomization.yaml
ironic-deployment/overlays/basic-auth_tls/basic-auth_tls.yaml
ironic-deployment/overlays/basic-auth_tls/kustomization.yaml
ironic-deployment/overlays/e2e/kustomization.yaml
tools/deploy.sh
tools/run_local_ironic.sh

It was only used for cross-service communication. Now that the
deployment scripts no longer support inspector, it is unused.

🌱 Remove last traces of auth-config

---

apis/go.mod
apis/go.sum
go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/go.mod
test/go.sum

JSON unmarshalling can enter infinite loop.
https://osv.dev/vulnerability/GO-2024-2611

🐛 bump google.golang.org/protobuf to v1.33.0

---

.github/workflows/release.yaml
Makefile
hack/tools/release/notes.go

Support beta and RC releases in release note generator. Rename notes.go the same way, and add nice unfolding summary section to hide details in beta/rc notes.
Fix previous release tag pattern detection in Makefile.
Example output visible in CAPM3 PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1567

🌱 add support for beta/rc releases in release notes

---

ironic-deployment/overlays/basic-auth_tls/kustomization.yaml

Added some comments to instruct secret and configmap generation for `ironic-deployment/overlays/basic-auth_tls` overlay

:seedling: Update ironic basic-auth-tls overlay

---

test/e2e/basic_ops_test.go
test/e2e/external_inspection_test.go
test/e2e/inspection_test.go
test/e2e/live_iso_test.go
test/e2e/provisioning_and_annotation_test.go
test/e2e/re_inspection_test.go

Checks whether the skipCleanup variable is true or not.If true,it skips the cleanup of the test resources
Fixes #1629

🌱 check for skipCleanup before running cleanup of test resources

---

PROJECT
apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
apis/metal3.io/v1alpha1/hostfirmwarecomponents_types_test.go
config/base/crds/bases/metal3.io_hostfirmwarecomponents.yaml
config/base/crds/kustomization.yaml
config/base/crds/patches/cainjection_in_hostfirmwarecomponents.yaml
config/base/crds/patches/webhook_in_hostfirmwarecomponents.yaml
config/base/rbac/hostfirmwarecomponents_editor_role.yaml
config/base/rbac/hostfirmwarecomponents_viewer_role.yaml
config/base/rbac/role.yaml
config/render/capm3.yaml
config/samples/metal3.io_v1alpha1_hostfirmwarecomponents.yaml
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine_test.go
controllers/metal3.io/hostfirmwarecomponents_controller.go
controllers/metal3.io/hostfirmwarecomponents_test.go
main.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

- New Controller for HostFirmwareComponents
- Updated the CRD based on kustomization
- added GetFirmwareComponentsForNode to the Provisioner interface
- implemented GetFirmwareComponentsForNode in ironic.go
metal3-io/metal3-docs#364

✨ HostFirmwareComponents CRD and Controller  & Tests

---

ironic-deployment/base/ironic.yaml
ironic-deployment/components/tls/tls.yaml

Using them allows us not to care about all possible ways Ironic can be
installed. In the future, we can use the mounted secrets to exercise
less trivial API resources such as conductors or drivers
(see https://github.com/metal3-io/baremetal-operator/issues/1528).

🌱 Make use of the new liveness/readiness probe scripts

---

hack/ci-e2e.sh

In CI we currently specify the emulator to use (sushy-tools or VBMC) and can in addition specify the protocol for sushy-tools. This change is a preparation to switch to specifying the protocol instead and picking the emulator based on it.
Fixes #

🌱 E2E: Prepare for emulator based on protocol

---

hack/ci-e2e.sh

We are now specifying the BMC protocol directly and do not need to expose the emulator variable. The emulator will be picked based on the protocol.
Fixes #

🌱 E2E: Cleanup emulator variable

---

controllers/metal3.io/baremetalhost_controller.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

This commit is to address some feedback from #1559.
- Automatically create the HFC for the BMH
- GetFirmwareComponents now takes into consideration that an empty list was returned and will only throw an error if the FirmwareInterface is different from `redfish`.
**What this PR does / why we need it**: metal3-io/metal3-docs#364

🐛  Fixes for HostFirmwareComponents 

---

apis/metal3.io/v1alpha1/baremetalhost_types_test.go
controllers/metal3.io/bmceventsubscription_controller_test.go

This PR adds unit tests to baremetalhost_types_test.go for SetOperationalStatus,HasBMCDetails,SetHardwareProfile function in baremetalhost_types.go and it also adds unit tests for adding finalizers in bmceventsubscription_controller_test.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:  This PR increases unit test coverage in baremetalhost_types and slightly in bmceventsubscription_controller
Part of #1574

🌱Added unit tests for baremetalHostTypes and bmceventSubscriptionController

---

go.mod
go.sum

When bumping [gophercloud/v2 to v2.0.0-beta.2](https://github.com/metal3-io/baremetal-operator/pull/1569), it brought along a patch version to go directive in root go.mod. This set up a very strict golang requirement on BMO, which was made worse by the [golang bump to v1.21.9](https://github.com/metal3-io/baremetal-operator/pull/1658).
[My PR in gophercloud](https://github.com/gophercloud/gophercloud/pull/3032) fixed this issue, and we need to take in this v2.0.0-beta.3 + some commits to include the fix, in order to not release BMO 0.6.0 with this strict golang requirement.
In main, we should aim to bump to beta.4 as soon as it is released and preferably cherry-pick that to release-0.6 branch too.

🌱  bump gophercloud/v2 to beta.3 + some commits to fix go.mod

---

ironic-deployment/base/ironic.yaml

🌱 Pinning ironic image release-24.1

---

test/e2e/basic_ops_test.go
test/e2e/common.go
test/e2e/live_iso_test.go
test/e2e/provisioning_and_annotation_test.go
test/e2e/re_inspection_test.go
test/go.mod
test/go.sum

BMO E2E is using some functions from CAPM3-E2E. This likely causes circular imports in the future.

:seedling: Remove capm3_e2e dependency from bmo E2E

---

Makefile

BMO E2E is now importing ginkgo 2.17.1, but cli version is lagging.

:seedling: Fix mismatched versions between imported and cli ginkgo

---

controllers/metal3.io/hostfirmwaresettings_test.go
pkg/provisioner/fixture/fixture.go

We already have a test provisioner, one more is unnecessary.

🌱 Remove redundant Provisioner from HostFirmwareSettings tests

---

README.md

Update e2e test triggers after migrating to prow.
To check prow test list: `/test ?`

🌱 Update CI triggers after migrating to prow jenkins operator

---

hack/verify-release.sh

Few improvements from previous minor release cycle:
- add missing k8s.io/apiserver to module sync
- change artefact to artifact for more common spelling
- match container image detection from release notes to match the earlier change in the release tooling
- rename some of the titles to be more descriptive
- mutate go.mod files for osv-scanner so it can accurately report vulnerablities in golang stdlib (ie. mutate "go 1.21" directive to "go 1.21.9" with patch version read off from main Dockerfile
- add version check for some tools, otherwise they'll give confusing output
This will be cherry-picked to 0.6 and 0.5 after it merges here as it affects patch release checks.

🌱 improve hack/verify-release.sh script

---

.github/workflows/release.yaml
Makefile
hack/tools/release/notes.go

Basically a cherry-pick from CAPM3 PR #1567 originally, and manual cherry-pick of BMO PR #1636 for the release workflow / release note generator.
Support beta and RC releases in release note generator. Move some logic from Makefile to the release note generator, and then add nice unfolding summary section to hide details in beta/rc notes.
Fix previous release tag pattern detection in Makefile.

🌱 backported fixes for Makefile and release workflow

---

go.mod
go.sum
pkg/provisioner/ironic/delete_test.go
pkg/provisioner/ironic/inspecthardware_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/power_test.go
pkg/provisioner/ironic/updatehardwarestate_test.go
pkg/provisioner/ironic/validatemanagementaccess_test.go

It keeps changing, now they reworked the HTTP error handling, so
1) switch to the new helper function,
2) stop relying on the exact error message in tests,
3) modernize the touched code a bit.

🌱 Update to the Gophercloud beta.4+commits

---

apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
config/base/crds/bases/metal3.io_hostfirmwarecomponents.yaml
config/render/capm3.yaml
controllers/metal3.io/hostfirmwarecomponents_controller.go
controllers/metal3.io/hostfirmwarecomponents_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

- Make Updates and Components optional in HostFirmwareComponentsStatus, so we don't get errors when they are empty.
- The UpdatedAt field for FirmwareComponentStatus can be nil, this caused runtime error in the BMO. Now we check the field before adding it.
**What this PR does / why we need it**: metal3-io/metal3-docs#364

🐛  Fix Status logic for HostFirmwareComponents

---

controllers/metal3.io/baremetalhost_controller.go

PreprovisioningImage not created on poweroff
There is a new state StatePoweringOffBeforeDelete
that should not create the PreprovisioningImage.
This new state comes from a previous one called
StateDeleting that was contemplated about
not creating the PreprovisioningImage.
Just added the new state to nor create the image.
Tested with the changes over release 4.14 on an OCP4.14 cluster. I dont think it should be different on higher versions. Suggestions? 
Fixes #

🐛  PreprovisioningImage should not be created on poweroff before delete

---

hack/e2e/ensure_minikube.sh

minikube v1.33.0 supports k8s v1.30. 

🌱 bump minikube to v1.33.0

---

.golangci.yaml
apis/metal3.io/v1alpha1/baremetalhost_types.go
cmd/make-virt-host/main.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/bmceventsubscription_controller.go
controllers/metal3.io/bmceventsubscription_controller_test.go
controllers/metal3.io/controller_test.go
controllers/metal3.io/demo_test.go
controllers/metal3.io/host_config_data_test.go
controllers/metal3.io/host_state_machine.go
controllers/metal3.io/host_state_machine_test.go
controllers/metal3.io/hostfirmwarecomponents_test.go
controllers/metal3.io/hostfirmwaresettings_test.go
main_test.go
pkg/hardwareutils/bmc/ilo4.go
pkg/hardwareutils/bmc/ilo5.go
pkg/hardwareutils/bmc/irmc.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/dependencies.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/raid.go
pkg/provisioner/ironic/testbmc/testbmc.go
pkg/provisioner/ironic/testserver/ironic.go
test/e2e/cert_manager.go
test/e2e/common.go
test/e2e/e2e_suite_test.go
test/e2e/upgrade_test.go

This PR adds the following last set of golangci linters
- asasalint
- bidichk
- dupword
- durationcheck
- errcheck
- errchkjson
- gci
- ginkgolinter
- goprintffuncname
- loggercheck
- nakedret
- nilerr
- noctx
- nosprintfhostport
- unparam
- usestdlibvars
I was also eager to enabled `containedctx`, however it had some issues with recently introduced structs with the following error
```
pkg/provisioner/ironic/ironic.go:112:2: found a struct that contains a context.Context field (containedctx)
ctx context.Context
```
Since this needs discussion, this is currently disabled.

🌱 Enabled last batch of linters

---

pkg/provisioner/ironic/capabilities.go
pkg/provisioner/ironic/ironic.go

This is a part of the effort to make ironic/ironic.go more manageable.
Currently, it consists of more than 2000 lines and contains most of
the actual provisioning logic.
We already split tests into separate files, I'm thinking of splitting
the code along the same line.

🌱 Refactoring: introduce capabilities.go

---

ironic-deployment/base/ironic.yaml

In PR: https://github.com/metal3-io/baremetal-operator/pull/1679 ironic image was not pinned everywhere. This PR is fixing it.

🐛 Pinning ironic image release-24.1 where it was missed

---

go.mod
go.sum

Bump gophercloud to official beta.5 from beta.4+commits

🌱 bump gophercloud to v2.0.0-beta.5

---

pkg/provisioner/ironic/inspecthardware.go
pkg/provisioner/ironic/ironic.go

This is a part of the effort to make ironic/ironic.go more manageable.
Currently, it consists of more than 2000 lines and contains most of
the actual provisioning logic.
We already split tests into separate files, I'm thinking of splitting
the code along the same line.

🌱 Refactoring: introduce inspecthardware.go

---

config/overlays/e2e-release-0.4/kustomization.yaml
config/overlays/e2e-release-0.5/kustomization.yaml
config/overlays/e2e-release-0.6/kustomization.yaml
ironic-deployment/overlays/e2e-release-24.0-with-inspector/kustomization.yaml
ironic-deployment/overlays/e2e-release-24.1/kustomization.yaml
ironic-deployment/overlays/e2e-with-inspector/kustomization.yaml
test/e2e/common.go
test/e2e/config/ironic.yaml
test/e2e/e2e_suite_test.go
test/e2e/upgrade_test.go

We are changing CI infrastructure. An unfortunate side-effect is that some steps are taking longer than they used to. Because of this we now see some timeouts.
This commit is for increasing the relevant timeouts to make the CI stable again.
Fixes #

🌱 E2E: Increase timeouts to stabilize CI

---

main.go

We add a few command-line flags to the baremetal-operator binary to configure more `ctrl.Options{}`.

:seedling:  Add more ctrl options flags

---

test/e2e/common.go
test/e2e/e2e_suite_test.go
test/e2e/upgrade_test.go

These functions are useful and can be used in other packages as well. For e.g. https://github.com/metal3-io/baremetal-operator/pull/1669

:seedling: Export BuildKustomizeManifest and GetKubeconfigPath functions in E2E

---

docs/api.md

The content has been migrated there in an expanded form.

🌱 Link to the user guide for supported hardware

---

main.go
main_test.go

TLS config code causes security linters to report false positive about TLS versions that can be configured.
This is porting over [CAPO PR 2037](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2037).

🌱 refactor TLS config

---

.github/ISSUE_TEMPLATE/failing-test.yaml
.github/ISSUE_TEMPLATE/flaking-test.yaml

This adds issue templates for failing and flaky tests, consistent with what we have in CAPM3 already.
Fixes #

🌱 Add issue templates for flaky/failing tests

---

pkg/provisioner/ironic/clients/client_test.go

:seedling: Add unit test on pkg/provisioner/ironic/client.go

---

.github/workflows/e2e-fixture-test.yml

This improves the github workflow for fixture tests by uploading the artifacts, similar to what we already have for jenkins jobs.
Fixes #

🌱 Upload artifacts from fixture tests

---

hack/shellcheck.sh

Make shellcheck consider only files.
If branch name ended with .sh or .sh/something, it was found on the filesystem as something ending with .sh, and shellcheck picked it up, and linting failed obviously.

🌱 shellcheck only files

---

.github/workflows/e2e-fixture-test.yml
.github/workflows/release.yaml
.golangci.yaml
Dockerfile
Makefile
Tiltfile
apis/go.mod
go.mod
hack/e2e/ensure_go.sh
hack/generate.sh
hack/golint.sh
hack/gomod.sh
hack/tools/go.mod
hack/unit.sh
pkg/hardwareutils/go.mod
test/go.mod

This PR bumps the golang version to v1.22 in different go modules, tests and Dockerfile.

🌱 Bump golang to v1.22

---

.github/workflows/e2e-test-periodic.yml
.github/workflows/e2e-test-pull.yaml
.github/workflows/e2e-test.yml
hack/ci-e2e.sh
hack/e2e/ensure_go.sh

Run the E2E tests as github workflows. This adds one reusable workflow (test-e2e.yml) that can be called by other workflows, in this PR test-e2e-pull.yml and test-e2e-periodic.yml. This way we avoid duplication and can have different configuration for pull requests and periodics.
- test-e2e-periodic.yml runs the e2e suite for redfish, redfish-virtualmedia and ipmi
- test-e2e-pull.yml runs the e2e suite for redfish-virtualmedia and ipmi
Fixes #

🌱 E2E: Run as github workflow

---

pkg/provisioner/ironic/clients/auth_test.go

This PR adds unit test for LoadAuth funciton, mentioned in the issue https://github.com/metal3-io/baremetal-operator/issues/1574
Fixes #  https://github.com/metal3-io/baremetal-operator/issues/1574
The provided test cases cover the following scenarios for the LoadAuth function:
```
No Authentication Directory Exists:
Test Case: NoAuthDirectory
Description: Tests the scenario where the ironic authentication directory does not exist. The function should return NoAuth as the authentication type without any errors.
Valid Authentication Credentials:
Test Case: ValidAuth
Description: Tests the scenario where the ironic directory exists with valid username and password files. The function should return HTTPBasicAuth with …
```

🌱 Add unit test for LoadAuth funciton in auth.go

---

Dockerfile
Makefile
hack/e2e/ensure_go.sh

Bump golang to 1.21.11 for:
https://osv.dev/vulnerability/GO-2024-2887
https://osv.dev/vulnerability/GO-2024-2888

🌱 bump golang to 1.21.11

---

tools/run_local_ironic.sh

It tries to execute the htpasswd string instead of redirecting it to file, thanks to extra subshell `"$( ... )"`. Removed.
https://jenkins.nordix.org/blue/organizations/jenkins/metal3-dev-env-integration-test-ubuntu-main/detail/metal3-dev-env-integration-test-ubuntu-main/21/pipeline/
```console
[2024-06-11T06:57:16.454Z] /home/metal3ci/go/src/github.com/metal3-io/baremetal-operator/tools/run_local_ironic.sh: line 176: YC76iK4sKn42:$2y$05$DPXYNTSnqeIG9RGFEREgd.we9gOOlFbnsKQPnAPlF2lSzzCotRM6C: command not found
[2024-06-11T06:57:16.454Z] make: *** [Makefile:12: launch_mgmt_cluster] Error 127
```

🐛 fix htpasswd generation in run_local_ironic.sh

---

tools/deploy.sh

This commit:
- removes the unnecessary parts of the htpasswd file generation and clears up the content of the file
The reason:
- The original command was designed to generate an env variable but the new ironic-image logic expects the content  to be suitable for a htpasswd file this the variable name and the "=" is not needed.
Fixes: #1785

:bug: Fix incorrect htpasswd file generation

---

.github/workflows/e2e-test-optional-periodic-release-0.5.yml
.github/workflows/e2e-test-optional-periodic-release-0.6.yml
.github/workflows/e2e-test-optional-periodic.yml
.github/workflows/e2e-test-periodic-main.yml
.github/workflows/e2e-test-periodic-release-0.5.yml
.github/workflows/e2e-test-periodic-release-0.6.yml

Otherwise workflows try to run on forks as well, which might not have CNCF (or any matching runners) and they would just keep scheduling and eventually after 30 hours get cancelled and maintainers get spammed.

🌱 limit running BMO e2e periodics to metal3-io repo

---

Makefile

🐛 fix make install and make uninstall
fix make install and make uninstall
Fixes #1788

🐛 fix make install and make uninstall

---

.github/workflows/e2e-test.yml

By default, if a step in github action fails, the subsequent steps won't be run. This is not ideal in case of running e2e tests, as we would like the tests artifacts to be uploaded, even if the tests fail.
This PR enables test artifacts upload for failed tests.

:seedling: Always upload test artifacts, even if the tests fail

---

.github/dependabot.yml

This PR add the following:
- Adds newly introduced multi-directories feature in dependabot. With this hopefully all the go modules would be bumped in one PR for a dependancy. Also this PR optimizes the dependabot configs a bit by adding a group for k8s.io dependancy bump and allowing patch versions for the ignore rules.
- Also add release branch configurations for dependabot

🌱 Optimize the dependabot configuration and add release branch configurations

---

hack/generate.sh
hack/gomod.sh

As a continuation of https://github.com/metal3-io/project-infra/pull/797, we use basic-checks image in local tests too for BMO.

:seedling: Use basic-checks image in generate and gomod tests

---

test/e2e/bmc.go
test/e2e/e2e_suite_test.go

A minor PR to not use gomega's `Expect()` in `LoadBMCConfig()`.
Reason: Using `Expect()` inside the function prevents reusage of the function in locations where ginkgo is not in use (e.g. https://github.com/metal3-io/baremetal-operator/pull/1767). This inclusion is unnecessary anyway, and `Expect()` should be located in the e2e suite.

:seedling: E2E: Remove gomega in LoadBMCConfig()

---

apis/metal3.io/v1alpha1/hostfirmwarecomponents_types.go
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/host_state_machine.go
controllers/metal3.io/hostfirmwarecomponents_controller.go
controllers/metal3.io/hostfirmwarecomponents_test.go
main.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/provision_test.go

Currently any changes in HostFirmwareComponents won't trigger the firmware update on it.
This commit aims to fix the issues we have observed while testing with real hardware.
**What this PR does / why we need it**: metal3-io/metal3-docs#364

🐛  Fix HFC to execute updates

---

controllers/metal3.io/baremetalhost_controller.go

We shouldn't set controller reference for HostFirmwareComponents, since they are to solve a problem with ReplicaSet and Pod that doesn't exist here, see [1]
[1] https://github.com/kubernetes/design-proposals-archive/blob/acc25e14ca83dfda4f66d8cb1f1b491f26e78ffe/api-machinery/controller-ref.md
**What this PR does / why we need it**: https://github.com/metal3-io/baremetal-operator/pull/1793#discussion_r1665123646

🌱 Use OwnerReference for HostFirmwareComponents

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/hostfirmwarecomponents_controller.go

This commit fixes the following cases for HFC:
- Status Components Information using the newer information that ironic contains.
- Clear the Status Updates in case of a failed fiirmware update, so it can retry.
Also change the condition as a follow-up to baremetal-operator#1793
**What this PR does / why we need it**: metal3-io/metal3-docs#364,

🐛 Fix HFC Status

---

.github/workflows/release.yaml
.golangci.yaml
Dockerfile
Tiltfile
hack/e2e/ensure_go.sh
hack/generate.sh
hack/gofmt.sh
hack/golint.sh
hack/gomod.sh
hack/unit.sh

Bumping golang since version 1.20 is deprecated
Fixes #1804

🌱 Bump golang to 1.22

---

.github/dependabot.yml

Config has mistakenly listed `/api` as a gomod ecosystem directory, but the correct directory in BMO is `/apis`.

🌱 fix dependabot config on api directory location

---

.github/workflows/dependabot.yml

Dependabot build wf is failing with `Package 'libvirt', required by 'virtual:world', not found`
For e.g. https://github.com/metal3-io/baremetal-operator/actions/runs/10205894991/job/28237655368?pr=1832
This PR should help fixing it.

:bug: Fix libvirt missing in dependabot build wf

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/base/crds/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml

It does not change anything for v1alpha1 (it is always populated)
but may send a wrong message about the field we're going to deprecate.

🌱 Do not mark hardwareProfile as required in the status

---

.github/workflows/build-images-action.yml

This assumes https://github.com/metal3-io/project-infra/pull/833 was merged, and that `QUAY_IO_USERNAME` and `QUAY_IO_TOKEN` secrets exist, for pushing the image to `quay.io`.
An example of complete workflow (except for the push part):
https://github.com/metal3-io/baremetal-operator/actions/runs/10280659565/job/28448467379?pr=1861
/hold to wait for the secrets.

:seedling: Move container build to gh runner

---

.github/workflows/build-images-action.yml

The container build github workflow should be triggered only if it's running on the upstream.

:seedling: Make container build only run for metal3.io repo

---

.github/workflows/release.yaml
.golangci.yaml
Dockerfile
Makefile
Tiltfile
hack/e2e/ensure_go.sh
hack/generate.sh
hack/golint.sh
hack/gomod.sh
hack/unit.sh

This is done since golang 1.21 is deprecating in August 2024
Fixes #1803

🌱 Bump golang to 1.22 in release 0.6

---

pkg/provisioner/ironic/ironic.go

The `net.LookupIP` function expects a hostname and not a full address.

:bug: Resolve BMC hostname, not address

---

test/go.mod
test/go.sum

Dependabot has issues bumping this for some reason in https://github.com/metal3-io/baremetal-operator/pull/1857 ,  doing it manually.

🌱 bump cert-manager to 1.10.2

---

ironic-deployment/base/ironic.yaml

This PR pins ironic image branch release-26 to BMO release-0.8 branch.

🌱 Pinning ironic image to release-26.0 branch

---

controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_config_data.go
controllers/metal3.io/host_config_data_test.go

The BareMetalHost CRD allows the UserData, MetaData, and NetworkData for the provisioned host to be specified as links to k8s Secrets. There are fields for both the Name and Namespace of the Secret, meaning that the baremetal-operator will read a Secret from any namespace. If a Secret contains the key "value" (or "userData", "metaData", or "networkData"), its corresponding value can be exfiltrated by a user provisioning a Host pointing to that Secret, then retrieving that data from the provisioned host.
Authored-by: Zane Bitter <zbitter@redhat.com>

🐛 Disallow fetching secrets from namespaces different from the host's one

---

README.md

Update triggers for release-0.8

:book: Update test triggers on README

---

test/e2e/basic_ops_test.go
test/e2e/common.go
test/e2e/external_inspection_test.go
test/e2e/inspection_test.go
test/e2e/live_iso_test.go
test/e2e/provisioning_and_annotation_test.go
test/e2e/re_inspection_test.go
test/go.mod
test/go.sum

This PR adds custom resource collection/dumping to BMO e2e tests. The collection is done at AfterEach of each test case.
It currently collects all CRDs and related CRs, including BMHs, but adding a filter if we one need should be easy.
It also calls framework.DumpAllResources as that was mentioned in the linked issue, but that doesn't seem to do much. I'm not sure if it should be included.
This PR is related to #1383 and fulfills two of the subtasks.

🌱 Add resource dumping to e2e tests

---

Makefile

Ginkgo CLI version is once again mismatches with the packaged version.
To prevent this from happening again, this PR pins the Ginkgo CLI version to whatever version it is in `test/go.mod`.

:seedling: Pin ginkgo cli to test/go.mod ginkgo package

---

test/e2e/config/ironic.yaml

`ironic:e2e` isn't an image we build or have, so trying to load it is just confusing, and wasteful too.

:seedling: Cleanup unused ironic:e2e tryload

---

controllers/metal3.io/baremetalhost_controller_test.go

~~When using this method, the `saveHostStatus` will requeue the object and create more reconciles for the object when the only thing that has changed is the lastupdated field in the status.  This leads to multiple reconciles because this happens during each run through the reconciler.~~
This adds a test to the baremetalhost controller to validate that the saveHostStatus will not requeue the object and create more reconciles when lastUpdated is updated.
~~Fixes https://github.com/metal3-io/baremetal-operator/issues/1253~~

🌱Add test for baremetalhost controller updateEventHandler

---

.github/workflows/e2e-test.yml

This reverts commit 6aa2b8e71727c1e550e99cafe727e9b0f15dc1e0.
ubuntu-latest only has 14GB disk, while ubuntu-latest-4-cores has 140GB. Our optional e2e tests need more disk for the VM disks than ubuntu-latest can offer, hence reverting.

:seedling: Revert "use ubuntu-latest rather than hosted 4-core runner"

---

tools/deploy.sh

Currently deploy.sh tries to use ${SCRIPTDIR} in its KUSTOMIZE variable which breaks calling it via the Makefile to build kustomize in some cases (it certainly does on my system!). To fix, I added another variable, KUSTOMIZE_BUILD which points to exactly what the Makefile wants to see.
Fixes #

🌱 Improve deploy.sh to differentiate between build and run of kustomize

---

.github/dependabot.yml

Make CAPI a pattern in dependabot config, so cluster-api and cluster-api/test packages get updated with single dependabot PR.
Same has been implemented in CAPM3 and IPAM as well.

🌱 make CAPI a pattern in dependabot config

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/base/crds/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml

Follow-up to commit 9a30c0de44ff7534b568000bb3f818a8d168af82.

🌱 Fix minor issues in the API help strings

---

.github/workflows/pr-verifier.yaml

Reuse PR verifier workflow from project-infra, so it is easier to maintain in a single place and reduces number of dependabot bump PRs targeting Github Actions, creating less noise.

🌱 Reuse PR verifier workflow from project-infra

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/bmceventsubscription_controller.go

Added Error message when reconciling loop is triggered more than once
Fixes #
https://github.com/metal3-io/baremetal-operator/issues/1787#event-13218719410

🌱 Added Error message when reconciling loop is triggered more than once

---

.github/workflows/dependabot.yml

generate test in prow also generates the manifests. This makes sure that manifests are upto date in case any change is needed in them caused by go modules/code changes.

🌱 Add manifest generation while generating code

---

config/base/manager.yaml
main.go

Move TLS 1.3 from hardcoded default value to a config flag.
This aligns BMO implementation to CAPM3/IPAM implementation while keeping TLS 1.3 as default.

🌱 Move TLS 1.3 from hardcoded default value to a config flag

---

hack/ci-e2e.sh
test/e2e/basic_ops_test.go
test/e2e/common.go
test/e2e/config/fixture.yaml
test/e2e/config/ironic.yaml
test/e2e/e2e_config.go
test/e2e/e2e_suite_test.go
test/e2e/external_inspection_test.go
test/e2e/inspection_test.go
test/e2e/live_iso_test.go
test/e2e/provisioning_and_annotation_test.go
test/e2e/re_inspection_test.go
test/e2e/upgrade_test.go

Fixes #1383
There will be a new file called "ironic-nodes.json" in the testcase log directory.

:seedling:  Fetch Ironic node list after each e2e test

---

pkg/provisioner/fixture/fixture.go

The fixture provisioner did have a delay previously, but it was removed as part of some work on reducing access to sensitive information. Now that we are running tests with the fixture provisioner, this has become an issue, since inspection happens so fast that it is hard to detect.
This commit introduces artificial delay without accessing any extra information.
Fixes #

🌱 Introduce inspection delay for the fixture provisioner

---

controllers/metal3.io/preprovisioningimage_controller.go
controllers/metal3.io/preprovisioningimage_controller_test.go
pkg/provisioner/ironic/factory_test.go

This improves test coverage by adding a few unit tests.
I did a half-hearted attempt to test the preprovisioning image controllers `Reconcile` function but it got too complicated. That is still something that could be improved in the future.
Fixes #1574 (it ticks the remaining two boxes)

🌱  Improve test coverage

---

.golangci.yaml
pkg/provisioner/fixture/fixture.go
test/e2e/config/fixture.yaml

We have started hitting the deadline for golangci-lint. This commit doubles it from 5m to 10m. It also adjusts the fixture provisioners artificial inspection delay and the interval that is used when checking for it.
Fixes #

🌱 Adjust test and linter timings

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
config/base/crds/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
controllers/metal3.io/host_state_machine_test.go
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/clients/features.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/servicing.go
pkg/provisioner/ironic/servicing_test.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/provisioner.go

This PR enables BMO to run Ironic servicing operations (such as applying firmware settings changes - or in the future firmware updates to already provisioned nodes). Servicing is an opt-in feature and is controlled by creation of a HostUpdatePolicy for a node with attributes indicating the desire to make changes to firmware configuration onReboot.
This is a partial implementation of metal3-io/metal3-docs@e260d42304a5822816ebc1752ab6c0818b9ee589  (please note only firmware settings changes are currently supported, firmware update support will be added next).

✨ Add reference to HostUpdatePolicy in Servicing with HFS Support

---

tools/deploy.sh

Using /dev/urandom has entropy issue. It can run out especially in CI, leaving jobs stuck. We have used uuidgen in BMO e2e for long time now and it works great. These usernames/passwords just need to be anything random to make sure nothing is hardcoded, so uuidgen works great for that anyways.

:seedling: use uuidgen to generate random username/password

---

README.md

This adds status badges for all e2e tests on the main branch. We could consider adding badges also for the release branches, but it may become hard to read with so many badges.
Fixes #

:book: Add e2e status badge to readme

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
controllers/metal3.io/baremetalhost_controller.go
pkg/provisioner/ironic/ironic.go

If we have to recreate the provisioner's state during deprovisioning, we must
first call Adopt() to ensure that something will actually happen to deprovision it.
This is the case regardless of provisioning method, but previously only
happened when an image was provisioned. In practice, the ironic provisioner
was attempting to adopt in cases where it was not originally intended to, and
subsequent changes mean it is never necessary.
If an externally provisioned host has a provisioning image set and then
the externallyProvisioned flag is removed, we should not begin an inspection
(which would involve rebooting the host), but instead move directly to
the provisioned state. This is also the case regardless of
provisioning method, but previously only happened when an image was
provisioned.

:bug: Make custom deploy equivalent to image deploy

---

.github/workflows/golangci-lint.yml
.golangci.yaml
Dockerfile
Makefile
Tiltfile
cmd/make-bm-worker/templates/templates_test.go
hack/e2e/ensure_go.sh
pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go

Bump Go to 1.23.3 and golangci-lint to 1.60.3 which supports Go 1.23.
Ignore couple new warnings that are generated, as there is no immediate good options.
Cleanup golangci-lint config from deprecated configs.
Include timeouts where needed, golangci-lint 1.60 is defaulting to real short runs and failing otherwise.
Manual cherry-pick of #2069 due conflict in golangci-lint config.
/hold
until #2069 is merged, so they can be merged as identical.

:seedling: Bump Go to 1.23.3 and golangci-lint to 1.60.3

---

controllers/metal3.io/baremetalhost_controller.go

When a provisioning error happens and firmware updates are involved, we should only set the Status Updates of the HFC to nil if they are not nil.

🐛 Update HFC Status when handling error in actionPreparing

---

controllers/metal3.io/dataimage_controller.go

This fixes the issue of dataImage resource not being deleted, if the corresponding BMH is deleted without detaching the dataImage.

:bug: Remove dataImage finalizer if BMH is missing

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/bmceventsubscription_controller.go

It does not work by concatenating strings.
This reverts commit 3a4cabbe135b6f392085ec6272f42ab4b6cefa14.

🌱 Do not add colons to structured logging

---

apis/metal3.io/v1alpha1/doc.go
apis/metal3.io/v1alpha1/hostfirmwaresettings_types.go

- fix: add json tags to match field annotation tag `+patchStrategy`
- fix: add missing doc.go for proper groupName inference
Most go code generators such as kube-openapi rely on gengo [[1](https://github.com/kubernetes/gengo/)] to infer the annotated tags.
When dealing with package annotations, gengo extracts them from the doc.go file [[2](https://github.com/kubernetes/gengo/blob/2b36238f13e9b8aebe4c286c2ffb2fc71f4be3c5/types/types.go#L121-L126)].
The types defined in `apis/metal3.io/v1alpha1` do have a package annotated with `+groupName`.
However, the annotation is in the `groupversion_info.go` file instead.
You can see comments that refer to this issue [[3](https://github.com/kubernetes/code-generator/issues/150#issuecomment-1773718101)] …

🌱 Add missing comment tags

---

ironic-deployment/overlays/e2e/kustomization.yaml

The live-ISO test is currently failing due to a bug in ironic. To avoid blocking main while this is sorted out, this commit pins ironic to an unaffected version.
Fixes #
Workaround for #2110

🌱 E2E: Pin ironic as workaround for failing tests

---

.github/workflows/golangci-lint.yml
Makefile
hack/tools/deploy-cli/deploy-cli.go
hack/tools/deploy-cli/main.go

This pr fixes errors found by osv-scanner in deploy-cli.
It also adds `hack/tools` package as a linting target, so that
any failure due to dependencies changes will get detected in the future.
Fixes #2121

🐛 Add hack/tools to bed linted and fix errors in deploy-cli

---

.golangci.yaml
config/base/manager.yaml
config/base/rbac/kustomization.yaml
config/base/rbac/metrics_auth_role.yaml
config/base/rbac/metrics_auth_role_binding.yaml
config/base/rbac/metrics_reader_role.yaml
config/base/rbac/metrics_service.yaml
config/overlays/e2e/kustomization.yaml
config/render/capm3.yaml
main.go
test/e2e/e2e_suite_test.go

https://github.com/metal3-io/baremetal-operator/pull/2102 has introduced controller-runtime's `WithAuthenticationAndAuthorization` filter which also requires extra RBAC roles and role bindings for metrics authentication and authorization. This PR adds those.

✨ Add RBAC files for metrics authentication and authorization

---

config/overlays/fixture-release-0.8/kustomization.yaml

Fixture overlay for release-0.8 was wrongly tagged with release-0.9 ref. Putting back the correct tags.

:seedling: Fix BMO fixture-release-0.8 tag names

---

test/e2e/e2e_suite_test.go

Currently the periodic optional tests are failing to check if metrics service is available or not. Perhaps we need to wait for a while for the service to be available.

🌱 Add intervals while checking metrics service

---

test/e2e/e2e_suite_test.go

Since the `cmd` block is outside the `eventually` block, when the same `cmd` object is used multiple times, we see `exec: Stdout already set` error. Moving it inside the `eventually` block should solve it.

🐛 Fix metrics service validation

---

hack/ci-e2e.sh
ironic-deployment/overlays/e2e-local-ironic/ironic-patch.yaml
ironic-deployment/overlays/e2e-local-ironic/kustomization.yaml

this commit:
- adds support for running the e2e tests with locally built ironic image
- adds environment variable to enable the feature on demand
Reason:
There are scenarios outside the CI pipelines when developers need to run the e2e tests and run it with a custom ironic build e.g. to test new features.

:sparkles: add support for locally built ironic in e2e test

---

test/e2e/config/fixture.yaml

this commit:
- increases the timeout and refresh interval for the "external-inspection" spec's "waiting for the BMH to become available" test
On some test platforms the previous configuration proved to be insufficient. Tests were failing without any issue simply because of being a bit slower than expected.

:seedling: increase 1 timeout in external-inspection test

---

test/e2e/e2e_suite_test.go

BMO optional test is not deploying BMO via e2e_suite_test.go but that is done separately in upgrade test. Hence the check is failing since we are not deploying BMO in e2e suite test but we are checking for metrics service to be up. This PR makes sure that metrics service is only checked when BMO is deployed.

🐛  Fix BMO optional test by not checking metrics service

---

.golangci.yaml
config/base/manager.yaml
config/base/rbac/kustomization.yaml
config/base/rbac/metrics_auth_role.yaml
config/base/rbac/metrics_auth_role_binding.yaml
config/base/rbac/metrics_reader_role.yaml
config/base/rbac/metrics_service.yaml
config/overlays/e2e/kustomization.yaml
config/render/capm3.yaml
main.go
test/e2e/e2e_suite_test.go

Manual cherry-pick of #2116 
https://github.com/metal3-io/baremetal-operator/pull/2102 has introduced controller-runtime's WithAuthenticationAndAuthorization filter which also requires extra RBAC roles and role bindings for metrics authentication and authorization. This PR adds those and also adds an e2e test around it

✨ Add RBAC files for metrics authentication and authorization 

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
apis/metal3.io/v1alpha1/baremetalhost_types_test.go

Previously, if no checksum type was specified into the BMH CR, it automatically handled it as MD5, causing errors to whom used different hashing algorithms. 
It adds checks on the length of the checksum string to understand which hashing algorithm when the BMH CRs do not have an explicit `.spec.image.checksumType` field.
Fixes #2172

:bug: Adding empty checksumType checks on BMH  to automatically detect hashing algorithm

---

apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go

Add to BMH creation a validation, which checks if any secret references is from namespaces other than BMH's. This is to prevent the secret leakage when a user references secrets from other ns just to get the secrets out.
Fixes #1965

:bug: Add validation against cross-namespace secret references

---

hack/e2e/ensure_kind.sh

In ensure_kind.sh, the downloaded binary file's name is kind-linux-amd64, so we should run `sudo install kind-linux-amd64` instead of `sudo install kind`.

:seedling: Fix ensure_kind.sh filename

---

Dockerfile
Makefile
hack/e2e/ensure_go.sh

Golang stdlib has issue in crypto/x509, fixed in golang 1.23.5. https://osv.dev/GO-2025-3373
Golang stdlib has issue in net/http, fixed in golang 1.23.5. https://osv.dev/vulnerability/GO-2025-3420
Both codepaths are used in the code.

:bug: bump golang to 1.23.5

---

controllers/metal3.io/baremetalhost_controller.go

Currently we are creating HFC for all BMH.
HFC only works for redfish based hardware, so we should only create when we detect that is redfish is in use.

🐛  Do not create HFC for non-redfish BMH

---

controllers/metal3.io/baremetalhost_controller.go

Add the ownerReference for dataImage as soon as its created, so that in case of forced BMH deletion the dataImage is not left orphaned.

:bug: Set ownerReference for dataImage during BMH Reconcile

---

.github/workflows/lint-docs.yaml
.github/workflows/pipeline.yml
.github/workflows/pr-gh-workflow-approve.yaml
.github/workflows/pr-verifier.yaml

We have "edited" as leftover workaround from days before we had "PR auto-reapprover" workflow in some jobs. In some jobs it is specifically needed as those workflows check the PR metadata which is covered by the edited. Add "ready_for_review" for consistency as a trigger type as well.
Similar PRs will be pushed across Metal3 repos to make things consistent after [discussion in ironic-image PR.](https://github.com/metal3-io/ironic-image/pull/620#pullrequestreview-2604851729)

:seedling: workflows: sync pull_request trigger types

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/dataimage_controller.go

This is followup to https://github.com/metal3-io/baremetal-operator/pull/2238, fixing issues raised in the previous pr : https://github.com/metal3-io/baremetal-operator/pull/2238/files/0efbb139a9dfe3b5011780bd725968f7b76c91ff
Also updates the order of checks in the dataImage reconcile ( as per Zane's [comment here](https://github.com/metal3-io/baremetal-operator/pull/2249#discussion_r1955816469) )  :
1. paused annotation
2. owner reference
3. finalizer
4. detached host

:bug: Add BMH OwnerReference for DataImage right after its creation 

---

ironic-deployment/overlays/e2e/kustomization.yaml

The issue has been fixed so we can safely revert the workaround.
Revert of https://github.com/metal3-io/baremetal-operator/pull/2112
Fixes #
/hold
until the issue is properly fixed.
Expecting the live-ISO test to fail here.

🌱 e2e: Revert temporary pinning of Ironic

---

Dockerfile
Makefile
hack/e2e/ensure_go.sh

Bump golang to 1.23.7.
We'll have bunch of dependencies requiring this soon due vulns fixed in it.

:seedling: bump golang to 1.23.7

---

apis/metal3.io/v1alpha1/baremetalhost_types.go
apis/metal3.io/v1alpha1/baremetalhost_validation.go
apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
config/base/crds/bases/metal3.io_baremetalhosts.yaml
config/render/capm3.yaml
controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/baremetalhost_controller_test.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/clients/features.go
pkg/provisioner/ironic/clients/features_test.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/register.go
pkg/provisioner/ironic/register_test.go
pkg/provisioner/ironic/testserver/ironic.go
pkg/provisioner/provisioner.go

Add support for disable_power_off
as described in https://github.com/metal3-io/metal3-docs/pull/478

✨ Add support for Disablepoweroff

---

ironic-deployment/overlays/e2e-release-25.0/kustomization.yaml
ironic-deployment/overlays/e2e-release-26.0/kustomization.yaml

These were missed when backporting a change to the certificates to BMO
0.8. The CA certificiate no longer has an IP address, so the patch must
be adjusted for that.
Fixes #

🌱 E2E: Fix ironic overlays for 25.0 and 26.0

---

hack/generate.sh
hack/gomod.sh

We forgot to bump these local scripts to go 1.23 long time ago.

:seedling: bump local hack scripts to basic-checks:golang-1.23

---

.github/workflows/lint-docs.yaml
.github/workflows/pipeline.yml
.github/workflows/pr-gh-workflow-approve.yaml
.github/workflows/pr-verifier.yaml
.github/workflows/unit.yml

Re-adding "edited" trigger to testing workflows to workaround Dependabot workflow issue.
Ref: https://github.com/metal3-io/ironic-standalone-operator/issues/162
Ref: https://github.com/metal3-io/baremetal-operator/issues/2082

:seedling: fix dependabot testing issues by re-adding "edited"

---

pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/raid.go
pkg/provisioner/ironic/register.go

Replace the deprecated library with standard fmt and errors.

🌱 Replace deprecated pkg/errors with stdlib in provisioner/ironic

---

hack/ci-e2e.sh

This commit:
- updates the "systemrescue" iso url used for e2e tests
This commit is needed because the old url has become unavailable.
Fixes: https://github.com/metal3-io/baremetal-operator/issues/2314

:bug: update rescue iso used for e2e tests

---

apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
apis/metal3.io/v1alpha1/bmceventsubscription_validation_test.go
controllers/metal3.io/bmceventsubscription_controller.go
controllers/metal3.io/bmceventsubscription_controller_test.go

The BMCEventSubscription spec uses a Secret reference for the HTTPHeadersRef field. This allows the user to specify any namespace. To prevent leaking Secrets, this commit restricts the namespace to the same namespace that the BMCEventSubscription is in.

:warning: Only accept HTTPHeadersRef in same namespace

---

.github/workflows/golangci-lint.yml
.golangci.yaml
Makefile

This PR also bumps golangci-lint-action to 6.5.2. While doing that it removes some of the old unsupported golangci-lint settings.

🌱 Bump golangci-lint to v1.64.7

---

test/vbmctl/main.go
test/vbmctl/templates/VM.xml.tpl

We should let Ironic take care of booting the VMs and configuring boot order.
Otherwise we may unintentionally do a netboot before ironic is ready and
tries a virtualmedia boot for example.
Fixes #

🌱 E2E: Avoid net-booting VMs unintentionally

---

controllers/metal3.io/baremetalhost_controller.go
controllers/metal3.io/dataimage_controller.go
controllers/metal3.io/host_state_machine_test.go
go.mod
go.sum
pkg/provisioner/demo/demo.go
pkg/provisioner/fixture/fixture.go
pkg/provisioner/ironic/clients/features.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

Use the newly introduced [virtual media get api](https://github.com/gophercloud/gophercloud/pull/3303) to get the current dataImage status.

:sparkles: Use standard GetVirtualMedia API for checking dataImage status

---

OWNERS_ALIASES

According to our [community standards ](https://github.com/metal3-io/community/blob/main/CONTRIBUTOR-LADDER.md#reviewer)both Adil and Peppi-lotta has reached the level to be reviewers in BMO. They are also active in reviewing code in metal3.io org in general. Thanks a lot Adil and Peppi. Keep up the good work.

🌱 Add Adil and Peppi-lotta as reviewers

---

Makefile

The ./internal directory is not a separate Go module and is included
with the root already.

🌱 Makefile: do not explicit include ./internal/

---

.github/dependabot.yml

Replace release-0.8 config with release-0.10 config. Otherwise it will generate PRs for 0.8 on merge, which is now only-tested mode.

:seedling: add dependabot config for release-0.10

---

pkg/hardwareutils/bmc/access_test.go
pkg/hardwareutils/bmc/idrac_virtualmedia.go
pkg/hardwareutils/bmc/redfish.go
pkg/hardwareutils/bmc/redfish_virtualmedia.go

Ironic supports [1] not providing a system ID when the BMC handles
exactly one system (which is a common case for standalone servers).
On the other hand, we see a high number of cases where the address is
provided as redfish://host/redfish/v1/, which currently fails with a
very confusing JSON parsing errors.
This change updates all Redfish drivers to ignore paths that are empty
or contain only /redfish/v1. Refactor the drivers to DRY.
[1] https://review.opendev.org/c/openstack/ironic/+/707208

🐛 Redfish: correctly handle missing system ID

---

internal/controller/metal3.io/baremetalhost_controller.go
internal/controller/metal3.io/baremetalhost_controller_test.go

When an operator wants to update bare metal firmware, it must pass to `HostFirmwareComponents.Spec` a list of components and URIs for the update. In the old behavior, the controller will try to update the whole list, but it is desired to update only the firmware that was not updated. This PR fixes this passing to `TargetComponents` only the subset of unupdated components.

:bug: Make firmware update handle only a subset of `Spec.Updates`

---

README.md

Update CII badge to be BMO specific as required by OpenSSF.

:book: update CII badge

---

README.md

We don't run optional e2e on release branches, hence there is no badge and the link is broken. 
```text
ERROR: 1 dead links found!
[✖] https://github.com/metal3-io/baremetal-operator/actions/workflows/e2e-test-optional-periodic-release-0.9.yml/badge.svg → Status: 404
```text

:book: remove optional e2e badge link

---

internal/webhooks/metal3.io/v1alpha1/baremetalhost_validation.go
internal/webhooks/metal3.io/v1alpha1/baremetalhost_validation_test.go

Changing ExternallyProvisioned does not actually work. Furthermore, it
results in a host hopelessly stuck in the "inspecting" state (in my
testing, I could not even delete it). Until we sort out this issue, let
us prevent users from getting into a problem.
Workaround for: #2465
Includes:
- https://github.com/metal3-io/baremetal-operator/pull/2471

⚠️ Prevent changing ExternallyProvisioned in the webhook

---

.github/workflows/e2e-test-optional-periodic.yml
.github/workflows/e2e-test-periodic-main.yml
.github/workflows/e2e-test-periodic-release-0.10.yml
.github/workflows/e2e-test-periodic-release-0.8.yml
.github/workflows/e2e-test-periodic-release-0.9.yml

We sometimes would like to run BMO periodics manually in addition to scheduled actions.

:seedling: make BMO periodics manually triggerable

---

docs/configuration.md
pkg/provisioner/ironic/factory.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/ironic/register.go
pkg/provisioner/ironic/register_test.go

It's a common mistake among my customers to use drivers like `ipmi`,
`redfish` (as opposed to e.g. `redfish-virtualmedia`) without configuring
a provisioning network.
This change adds a new environment variable to tell BMO that no
provisioning network is available.

✨ Allow disabling drivers that require a provisioning network

---

.golangci.yaml
Dockerfile
Makefile
Tiltfile
hack/e2e/ensure_go.sh
hack/generate.sh
hack/gomod.sh

- gomods are still using v1.23.x
- Dockerfile and prow jobs are bumped to use v1.24.3

🌱 Bump golang to v1.24

---

.golangci.yaml
Dockerfile
Makefile
Tiltfile
hack/e2e/ensure_go.sh
hack/generate.sh
hack/gomod.sh

- gomods are still using v1.23.x
- Dockerfile and prow jobs are bumped to use v1.24.3

🌱 Bump golang to 1.24.3

---

test/go.mod
test/go.sum

Bump circl to v1.6.1 due GHSA-2x5j-vhc8-9cwm
Manual cherry-pick of https://github.com/metal3-io/baremetal-operator/pull/2518

:seedling: bump cloudflare/circl to v1.6.1 in /test

---

Dockerfile
Makefile
hack/e2e/ensure_go.sh

Bump golang to 1.24.4.
This closes following uncalled/unrelated vulnerabilities in stdlib:
- https://osv.dev/GO-2025-3749
- https://osv.dev/GO-2025-3750
- https://osv.dev/GO-2025-3751

:seedling: bump golang to 1.24.4

---

config/default/ironic.env
config/overlays/e2e/ironic.env
config/render/capm3.yaml
pkg/provisioner/ironic/factory.go
pkg/provisioner/ironic/factory_test.go
pkg/provisioner/ironic/ironic.go

Ironic has global configuration that allows specifying them, even
depending on the architecture. Our ironic-image supports that when
IPA downloader is used (and should start supporting explicit variables
too).
Fixes: #2100 

✨ Stop requiring DEPLOY_KERNEL/RAMDISK

---

tools/run_local_ironic.sh

After adding IPv6 support to dev env, it is possible that the used IP addresses are v6. In this case the address needs to be surrounded by brackets when using as a host address. This PR adds a check for IPv6 address and proper surrounding to IPv6 addresses in the `run_local_ironic.sh`.
Fixes #

:bug: Add IPv6 address check to run local

---

Dockerfile
Makefile
hack/e2e/ensure_go.sh

Bumps golang to v1.24.5. This patch has some bug fixes as well uncalled vulnerability fixes for example GHSA-wprm-fgrx-xj42.

🌱 Bump golang to v1.24.5

---

test/e2e/bmc.go
test/e2e/config/bmcs-ipmi.yaml
test/e2e/config/bmcs-redfish-virtualmedia.yaml
test/e2e/config/bmcs-redfish.yaml
test/e2e/provisioning_and_annotation_test.go

This makes it possible to specify the rootDeviceHints in the "BMCs" config file for e2e tests. It is necessary when running the tests against real hardware that may have different disk devices.
It also adds bootMode and disableCertificateVerification that may be
needed depending on the hardware.
Fixes #

🌱 E2E: Expose more BMC related fields

---

Dockerfile
Makefile
hack/e2e/ensure_go.sh

Manual-cherry pick of #2602 to bump golang to 1.24.6.

:seedling: bump golang to 1.24.6

---

.github/workflows/osv-scanner-scan.yml

The osv-scanner workflow should continue on error when uploading SARIF files and send Slack notifications for both vulnerabilities and workflow failures.
This ensures we get notified of any issues with the workflow.
Fixes #

🌱 Add continue-on-error and improve Slack notifications for osv-scanner

---

hack/e2e/net.xml
test/e2e/automated_cleaning_test.go
test/e2e/bmc.go
test/e2e/common.go
test/e2e/external_inspection_test.go
test/e2e/live_iso_test.go
test/e2e/provisioning_and_annotation_test.go
test/e2e/re_inspection_test.go
test/vbmctl/main.go

We have been "cheating" a bit in CI by configuring static IPs for the VMs through libvirt dhcp. This is not something we can rely on for real hardware. For that, we would either need to manually configure DHCP or make use of cloud-init to configure the IPs. This commit attempts to do the latter.
Fixes #

🌱 E2E: Set static IPs through user-data

---

test/e2e/README.md

Update the test/e2e/README.md to ease running e2e script locally.
Add info on GINKGO_FOCUS, GINKGO_SKIP and BMC_PROTOCOL, and how to clean up after running the ci-e2e.sh script.
Updates the README to better inform users on how to run the e2e locally, since at least one person appreciated new info  on these.

:book: Update info on running e2e locally

---

docs/releasing.md

Alpha release mention was missing in release documentation. Alpha release should follow the same convention as beta release.

📖 Add alpha release in release documentation

---

ironic-deployment/overlays/e2e-release-26.0/ironic_bmo_configmap.env
ironic-deployment/overlays/e2e-release-27.0/ironic_bmo_configmap.env
ironic-deployment/overlays/e2e-release-28.0/ironic_bmo_configmap.env
ironic-deployment/overlays/e2e-release-29.0/ironic_bmo_configmap.env
ironic-deployment/overlays/e2e-release-30.0/ironic_bmo_configmap.env
ironic-deployment/overlays/e2e-release-31.0/ironic_bmo_configmap.env
ironic-deployment/overlays/e2e/ironic_bmo_configmap.env

Tests are having issue when downloading the IPA image from upstream and hits timeout. So here we are passing IPA_BASEURI variable to ironic vars to download the IPA image from Nordix cache.

🌱 Add IPA_BASEURI to download ipa image from Nordix

---

.github/workflows/e2e-test-optional-periodic.yml
.github/workflows/e2e-test.yml

We are hitting the 90 minute timeout in the optional periodics. This PR makes the timeout configurable per workflow and increases it to 120 minutes for the optional periodics.
Fixes #

🌱 E2E: Make timeout configurable and increase it for optional periodics

---

internal/controller/metal3.io/baremetalhost_controller.go
pkg/provisioner/ironic/ironic.go
pkg/provisioner/provisioner.go

The current code ignores PreprovisioningImages for provisioned nodes. While normally there is a leftover PreprovisioningImage from the deployment, it's not the case for externally provisioned hosts.
Fixes #2689

🐛 Create a PreprovisioningImage for servicing if needed

---

internal/controller/metal3.io/baremetalhost_controller.go

Instead of hardcoding x86, we query the CPU architecture of the running Go binary.
Assisted-By: claude-4-sonnet

:warning: Change architecture default to match controller

---

config/overlays/e2e/kustomization.yaml
config/overlays/e2e/namespaced-manager-patch.yaml
config/overlays/e2e/upgrade-bmo/kustomization.yaml
config/overlays/e2e/upgrade-bmo/namespace.yaml
config/overlays/e2e/upgrade-ironic/kustomization.yaml
config/overlays/e2e/upgrade-ironic/namespace.yaml
test/e2e/upgrade_test.go

This PR fixes  BMO e2e optional test by adding upgrade-bmo and upgrade-ironic to namespace watch list. 
Fixes #

🐛 Align BMO e2e optional test to namespace scoped config
