test/e2e/baremetal_test.go
This PR will need to be created when the other ones merge, too.
=> Add more tests

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go, pkg/controller/baremetalhost/baremetalhost_controller.go
Wrap a few very long comments, remove one that isn't needed, and fix a
paste-o in another.
Addresses comments left on PR #7
=> clean up comments

Makefile, docs/testing.md
Wrap up the test run with a simple Makefile
=> add a makefile to make running the tests easier

docs/publishing-images.md
=> add step to deploy the new image

pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/controller/baremetalhost/baremetalhost_controller_test.go, pkg/provisioner/fixture/fixture.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/provisioner.go
This split is a prerequisite to making the ironic provisioner really depend on having ironic present.
=> Add test provisioner

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go
=> adds Available() method stub to BareMetalHost

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go, pkg/provisioner/ironic/ironic.go
To match the new storage and nic types
=> Better ironic defaults

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go, pkg/apis/metalkube/v1alpha1/baremetalhost_types_test.go
also adds unit tests for BareMetalHost.Available
=> host.Available returns false if host is being deleted

pkg/apis/metalkube/v1alpha1/baremetalhost_types.go, pkg/controller/baremetalhost/baremetalhost_controller_test.go
=> add BareMetalHost.NeedsProvisioning() method

pkg/provisioner/ironic/ironic.go
Rather than making the caller fetch the node again, return it from
ensureExists() when we have a good value.
This will be used by the Provision() method, being added separately.
=> update ensureExists to return the ironic node

pkg/controller/baremetalhost/baremetalhost_controller.go
Move the credential look-up and checking logic together into one
function to streamline Reconcile().
=> clean up credential management

.travis.yml, Makefile, cmd/make-worker/main.go, pkg/utils/stringlist.go
Set up travis to run unit and linter test jobs.
=> enable travis-ci

Makefile, deploy/operator.yaml, deploy/role.yaml, deploy/role_binding.yaml, deploy/service_account.yaml, docs/dev-setup.md
Create roles, accounts, etc. using "metalkube" in the name.
=> add metalkube to resource names

deploy/crds/example-host-bad-credentials.yaml, deploy/crds/example-host.yaml
Make it clear that some of the secrets are broken in specific ways and
meant to be used for testing.
Make the good example host file clear by giving it a better name.
=> clean up example hosts yaml files

docs/dev-setup.md
If go get fails it does not always check out the source.
=> fix go get step in installation instructions

pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/provisioner/ironic/ironic.go
Add details and extra operational events
=> More event updates

pkg/provisioner/ironic/ironic.go
We were fetching the checksum value before determining if we need to
pass it to ironic. Move the fetch into the code block where we pass
the value to ironic in the update call.
=> only fetch the checksum value when we need it

pkg/provisioner/ironic/ironic.go
Ironic may return a 409 status indicating that the host is busy any
time a change is requested. Add explicit handling for those errors so
they are treated as expected and so we wait before trying again.
=> look for busy status from ironic

build/Dockerfile
genisoimage provides mkisofs which is required.
=> Install genisoimage package

pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/controller/baremetalhost/baremetalhost_controller_test.go
Without this change, hosts in an error state cannot always be deleted.
Rather than trying to handle each delete case separately, merge them
all into 1 function that explicitly ignores certain error cases to
build enough objects to tell the provisioner that we need to delete
the host and then allows the k8s API to do that when the host is
cleaned up.
=> combine all delete handling

.travis.yml, Makefile, build/Dockerfile
Build a docker image from the repo as part of the test suite.
=> add a travis job to test building docker images

pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/controller/baremetalhost/baremetalhost_controller_test.go, pkg/controller/baremetalhost/demo_test.go, pkg/provisioner/demo/demo.go
Fix the demo provisioner based on the new logic for Reconcile() and add unit tests to ensure it stays up to date.
=> Demo unit tests

Makefile, README.md, deploy/operator.yaml, docs/configuration.md, pkg/provisioner/ironic/ironic.go
We don't always want these values to change, but sometimes they must,
so provide a way to do it.
=> add environment variables for configuring the operator

cmd/make-bm-worker/main.go
Fixes #158
Please bear with me I have 0 golang experience
=> Add hardwareProfile to the bmhost

cmd/make-bm-worker/main.go, cmd/make-bm-worker/templates/templates.go
Had some issues with my rebase on pull #174 so I decided to just recreate a new PR request that has the 1 commit with the changes as requested.  Sorry about all that.
=> adding bootmac as an option to the bm-worker tool

docs/dev-setup.md
This PR aims to update dev document according to the latest deployment script [1].
[1] https://github.com/metal3-io/metal3-dev-env/blob/master/03_launch_mgmt_cluster.sh#L37-L41
=> Adding namespace option into *kubectl apply* command

deploy/ironic_bmo_configmap.yaml, deploy/operator_ironic.yaml
Still a bit of a work in progress but it does launch the containers
and it should be close to working.
=> Add ironic to baremetal operator deployment.

docs/api.md, pkg/apis/metal3/v1alpha1/baremetalhost_types.go
=> Add description field to host spec

cmd/make-virt-host/main.go
=> Remove hardcode in BMC username and password

Gopkg.lock, Gopkg.toml, vendor/github.com/gophercloud/gophercloud/acceptance/openstack/blockstorage/extensions/extensions.go, vendor/github.com/gophercloud/gophercloud/acceptance/openstack/networking/v2/extensions/qos/rules/rules.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/v1/introspection/results.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/v1/introspection/testing/fixtures.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/results.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/testing/fixtures.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/rules/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/rules/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/rules/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/rules/testing/fixtures.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/rules/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/ruletypes/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/ruletypes/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/ruletypes/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/ruletypes/testing/fixtures.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/ruletypes/urls.go
This pulls in the fix for hostname support
https://github.com/gophercloud/gophercloud/pull/1627
=> Update to latest gophercloud revision

Makefile, build/Dockerfile, cmd/manager/main.go, pkg/version/version.go
=> log component version on startup

docs/api.md, pkg/bmc/access.go, pkg/bmc/access_test.go, pkg/bmc/irmc.go
#234
Signed-off-by: Dao Cong Tien <tiendc@vn.fujitsu.com>
=> Add support for Fujitsu driver iRMC

pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/provisioner/demo/demo.go, pkg/provisioner/fixture/fixture.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/provisioner.go
=> Adopt externally-provisioned hosts in Ironic

docs/testing.md
=> Update docs for linter testing

docs/api.md, docs/baremetalhost-states.md, pkg/apis/metal3/v1alpha1/baremetalhost_types.go, pkg/apis/metal3/v1alpha1/baremetalhost_types_test.go, pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/provisioner/fixture/fixture.go, pkg/provisioner/ironic/ironic.go
=> fix adoption for steady state hosts

Makefile
-two Makefile targets added
-coverage statistics written to file
-code coverage results launched to browser
fix: #283
=> add coverage info to unit test output

pkg/controller/baremetalhost/baremetalhost_controller.go
If the Secret referenced in the Host does not exist yet, we need to
periodically poll to see if it has been created as we cannot set a watch
on a Secret that does not exist. We should not publish a new event each
time this occurs.
=> Don't publish multiple events on missing Secret

hack/gofmt.sh, hack/gosec.sh, hack/govet.sh, hack/markdownlint.sh, hack/shellcheck.sh, hack/unit.sh, tools/run_local_ironic.sh
This allows ironic and all the hack tools to be run using Docker.
=> Parameterize container runtime in scripts

tools/run_local_ironic.sh
Fix wrong image dir reference and
missing ipa-downloader container
=> BMO+Ironic container local run script fixed

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/ironic_test.go
to be consumed by CAPBM to refer to the node
=> Add metal3 metadata for deployment from baremetalhost

pkg/bmc/access_test.go, pkg/bmc/redfish.go
=> Add ilo5-virtual-media bmc support

pkg/bmc/access_test.go
=> Update unit tests for AccessDetails interface

docs/dev-setup.md, docs/publishing-images.md
Fixes some OpenShift-isms in the docs
Closes: #200
=> Rename some oc CLI docs to kubectl

docs/dev-setup.md
=> Update CRD file name in dev guide

Makefile, deploy/ironic_ci.env, tools/run_local_ironic.sh
when running ironic containers locally, the environment variables
were missing
/cc @stbenjam 
/cc @fmuyassarov
=> Fix missing environment variables in CI

deploy/crds/metal3.io_baremetalhosts_crd.yaml, pkg/apis/metal3/v1alpha1/baremetalhost_types.go
=> Make optional date-time fields nullable

README.md
for Ubuntu and CentOS, v1alpha1 and v1alpha2
=> add E2E tests build status in Readme

deploy/ironic-keepalived-config/image_patch.yaml
Change the image for ironic endpoint keepalived
=> Change ironic endpoint keepalived image

cmd/make-bm-worker/main.go, cmd/make-bm-worker/templates/templates.go, deploy/crds/metal3.io_baremetalhosts_crd.yaml, docs/api.md, docs/dev-setup.md, pkg/apis/metal3/v1alpha1/baremetalhost_types.go, pkg/bmc/access.go, pkg/bmc/access_test.go, pkg/bmc/idrac.go, pkg/bmc/ipmi.go, pkg/bmc/irmc.go, pkg/bmc/redfish.go, pkg/controller/baremetalhost/baremetalhost_controller.go, pkg/provisioner/ironic/ironic.go, test/e2e/baremetal_test.go
Pending to be tested
fixes #392
=> Add verify ca

docs/configuration.md, pkg/controller/baremetalhost/baremetalhost_controller.go
Add support to reconcile concurrently
Continues from PR:  #344
Fixes #336
=> Add support to reconcile concurrently

pkg/provisioner/ironic/ironic.go
If we end up reconciling the Host again after starting an inspection in
Ironic, but before the IntrospectionStatus is available in
ironic-inspector, we don't want to attempt to start another inspection.
Check if the host is already in the correct state in Ironic before
trying to change the state to 'inspecting'.
This issue was identified in #393, but may not be the cause.
=> Avoid starting inspection twice

pkg/controller/baremetalhost/baremetalhost_controller.go
This is to comply with CAPI secrets content in v1alpha3
=> Look for userData or value in the userdata secret

README.md
Replace v1alpha1 CI status badge with v1alpha3 CI status.
=> Replace v1a1 CI status badge with v1a3

docs/api.md
This PR updates the api.md and adds detailed description about how pause annotation for bmh should be handled.
=> Update pause annotation description

docs/api.md
This small PR fixes the  bmh pause annotation value in api.md.
=> Fix bmh pause annotation key in api.md

cmd/manager/main.go
=> Add --namespace cli argument support for BMO

.travis.yml
There's no sense in running the same job on both prow and travis.
=> remove lint job from travis

pkg/bmc/access_test.go, pkg/provisioner/demo/demo.go, pkg/provisioner/fixture/fixture.go, pkg/provisioner/ironic/ironic_test.go
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>
=> Fix some warning: "redundant type from array, slice, or map composite literal"

Makefile, cmd/get-hardware-details/main.go
This name is more descriptive.
=> Rename make-introspection to get-hardware-details

docs/statusAnnotation.md, pkg/apis/metal3/v1alpha1/baremetalhost_types.go
This PR adds description about the status annotation in BMH.
Related to #524
=> Add status annotation documentation

.travis.yml, Makefile, hack/Dockerfile.golint, hack/golint.sh
Try to make the targets simpler and single-purpose. Also update the make target to use the same command as the gosec.sh script.
Addresses #505
=> clean up Makefile

deploy/ironic_ci.env, tools/run_local_ironic.sh
=> Fix IP address in ironic_ci.env

docs/deploying.md
**What this PR does / why we need it:**
This PR adds some missing parts and fixes typos in the documentation
=> 🏃 Add small changes to BMO and Ironic deployment documentation

OWNERS
Since I have now 10 commits in the repo, I would like to be added in the reviewers list
=> Add kashifest in the reviewers list

pkg/controller/baremetalhost/baremetalhost_controller.go
In saveHostStatus, we get the BMH right after updating the 
annotation. In some cases the cache is not updated yet, causing
an error in the status update. This could lead to a loop in   
some cases where the cache was slow to update as the annotations 
were always changed since operationHistory was changing every 
time (it uses the current time as end time for an operation).
To solve this :
- Discard operationHistory when comparing status annotation to  
current status to prevent unneeded updates of the annotation 
leading to additional conflicts
- Do not throw an error upon conflict in saveHostStatus, but  
requeue after an info message
=> Fix SaveHostStatus infinite loop on update conflicts

docs/api.md, pkg/apis/metal3/v1alpha1/baremetalhost_types.go
This PR will remove API changes made in [550](https://github.com/metal3-io/baremetal-operator/pull/550).
=> Remove Unhealthy annotation changes

cmd/make-bm-worker/templates/templates.go, cmd/make-bm-worker/templates/templates_test.go, cmd/make-virt-host/main.go
=> Set Online to false when rendering BMH CRs

docs/dev-setup.md
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
=> docs/dev-setup: fix error link

.gitignore, docs/dev-setup.md, tilt-provider.json
This is for https://github.com/metal3-io/cluster-api-provider-metal3/pull/132
=> Add Tilt provider file for integration with CAPM3 Tilt setup

docs/dev-setup.md, tools/run_local_ironic.sh
Fixes [metal3-dev-env/issues/443](https://github.com/metal3-io/metal3-dev-env/issues/443)
=> Make ironic environment variables configurable

pkg/controller/baremetalhost/host_state_machine.go, pkg/controller/baremetalhost/host_state_machine_test.go, pkg/provisioner/ironic/ironic.go
=> ensure the boot mode is set in ironic before starting inspection

.travis.yml, Makefile, apis/metal3.io/v1alpha1/baremetalhost_types.go, docs/dev-setup.md, hack/markdownlint.sh, hack/shellcheck.sh
* Documentation
* Travis config
* Hack script pruning
=> Remove operator-sdk leftovers

config/basic-auth/default/kustomization.yaml, config/tls/kustomization.yaml
#676 is not properly solving the kustomize path issue. This is a fix for that.
=> Fix tls kustomization path

config/manager/manager.yaml, config/render/capm3.yaml
=> Remove limits and requests from manager manifest

pkg/provisioner/ironic/ironic.go
Share the clients client instead of making a new one every time we
create a provisioner (during every call to Reconcile) so we can reuse
the transport and open connections.
This is an alternative to #710
=> cache the ironic api clients

pkg/provisioner/ironic/delete_test.go, pkg/provisioner/ironic/testserver/ironic.go
Add new test cases for the Ironic provisioner.Delete()
=> start adding unit tests for Ironic.Delete

docs/deploying.md, ironic-deployment/tls/default/kustomization.yaml, ironic-deployment/tls/default/tls.yaml, ironic-deployment/tls/keepalived/kustomization.yaml, ironic-deployment/tls/keepalived/tls.yaml, tools/deploy.sh, tools/run_local_ironic.sh
This PR is related to:
https://github.com/metal3-io/ironic-image/pull/206
https://github.com/metal3-io/metal3-dev-env/pull/525
=> Enable TLS between Ironic and MariaDB

pkg/provisioner/ironic/testserver/ironic.go
Signed-off-by: zouyu <zouy.fnst@cn.fujitsu.com>
=> A typo in the comment for WithNodeStatesProvisionUpdate

pkg/provisioner/ironic/validatemanagementaccess_test.go
As seen in the regression CI discovered that prompted
https://github.com/metal3-io/baremetal-operator/pull/768
we're missing some test coverage of the two possible
image sources in ValidateManagementAccess
=> Add test coverage of Spec vs Status Image

pkg/provisioner/ironic/ironic.go
=> Add missing newline in console log

pkg/provisioner/ironic/capabilities_test.go, pkg/provisioner/ironic/ironic.go
The current approach won't scale when we have more capabilities.
=> Refactor capabilities parsing

apis/metal3.io/v1alpha1/baremetalhost_types.go, config/crd/bases/metal3.io_baremetalhosts.yaml, config/render/capm3.yaml, pkg/bmc/access.go, pkg/bmc/ibmc.go, pkg/bmc/idrac.go, pkg/bmc/idrac_virtualmedia.go, pkg/bmc/ilo4.go, pkg/bmc/ilo5.go, pkg/bmc/ipmi.go, pkg/bmc/irmc.go, pkg/bmc/redfish.go, pkg/bmc/redfish_virtualmedia.go, pkg/provisioner/ironic/capabilities_test.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/testbmc/testbmc.go, pkg/provisioner/ironic/updateopts_test.go
Design: https://github.com/metal3-io/metal3-docs/pull/161
This depends on https://github.com/metal3-io/baremetal-operator/pull/783
=> Automatic setting of UEFI secure boot

.travis.yml, Dockerfile, Tiltfile, go.mod, go.sum, hack/Dockerfile.golint, hack/generate.sh, hack/gofmt.sh, hack/gomod.sh, hack/govet.sh, hack/unit.sh
Bump the Golang version to [1.16](https://blog.golang.org/go1.16)
=> Bump the Golang version to 1.16

config/certmanager/certificate.yaml, config/crd/patches/cainjection_in_baremetalhosts.yaml, config/crd/patches/webhook_in_baremetalhosts.yaml, config/default/kustomization.yaml, config/default/webhookcainjection_patch.yaml
Upgrade cert-manager, CRD, Webhook to v1
Fixes: https://github.com/metal3-io/baremetal-operator/issues/804
=> Upgrade CRD & Webhook to v1

controllers/metal3.io/baremetalhost_controller.go, controllers/metal3.io/host_state_machine.go, controllers/metal3.io/host_state_machine_test.go, controllers/metal3.io/metrics.go, docs/configuration.md, pkg/provisioner/demo/demo.go, pkg/provisioner/fixture/fixture.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/provisioncapacity_test.go, pkg/provisioner/provisioner.go
=> Use PROVISIONING_LIMIT also for deprovisioning.

.travis.yml
Enabling unit and lint tests in travis temporarily until praw is fixed.
=> Add unit and lint test in travis

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/update_opts.go, pkg/provisioner/ironic/updateopts_test.go
=> Fix travis lint test

apis/metal3.io/v1alpha1/baremetalhost_types.go, pkg/provisioner/ironic/testserver/server.go, pkg/provisioner/ironic/updatehardwarestate_test.go
=> Fix some typos

ironic-deployment/ironic/ironic.yaml, tools/run_local_ironic.sh
Make run command for ironic-inspector explicit and define the entrypoint
for local run.
=> Define command for ironic-inspector run

docs/api.md
Adding RAID Parameters in api.md.
=> Adding RAID Parameters in api.md

ironic-deployment/ironic/ironic.yaml, tools/deploy.sh
This PR is related to these PRs, and needs to wait for them to go in:
https://github.com/metal3-io/ironic-image/pull/247
It enables the feature of Ironic containers that automatically restart when the certificates are updated.
=> Restart Ironic containers when certificates are changed

apis/metal3.io/v1alpha1/baremetalhost_types.go
=> fix comment

docs/inspectAnnotation.md
=> Document re-inspection API

docs/ironic-endpoint-keepalived-configuration.md
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>
=> Unify `kubectl apply -f` format

controllers/metal3.io/baremetalhost_controller.go, pkg/provisioner/demo/demo.go, pkg/provisioner/fixture/fixture.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/provisioner.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
=> Fix some typos in comments

controllers/metal3.io/host_state_machine.go
Follow-up to https://github.com/metal3-io/baremetal-operator/pull/884.
=> Custom deploy: fix insufficient condition

docs/api.md, pkg/bmc/idrac.go
Extended BIOS Configuration for iDRAC.
=> BIOS Configurations for iDRAC

pkg/bmc/irmc.go
=> Remove duplicate if statement

apis/metal3.io/v1alpha1/baremetalhost_types.go, config/crd/bases/metal3.io_baremetalhosts.yaml, config/render/capm3.yaml, controllers/metal3.io/baremetalhost_controller.go, controllers/metal3.io/baremetalhost_controller_test.go, controllers/metal3.io/host_state_machine_test.go, docs/api.md, pkg/bmc/irmc.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/prepare_test.go, pkg/provisioner/ironic/raid.go, pkg/provisioner/ironic/raid_test.go, pkg/provisioner/provisioner.go
When I test on a server(irmc) without a RAID controller, this will cause an error.
I am very sorry for ignored this situation in the previous code.
=> Avoid always do delete_configuration clean step

config/OWNERS, ironic-deployment/OWNERS, resources/keepalived-docker/OWNERS, tools/OWNERS
Add @kashifest  and @fmuyassarov  as approvers in the following directories
```
/config
/ironic-deployment
/resources
/tools
```
=> Add kashifest and fmuyassarov as approvers

OWNERS
As discussed and approved over email.
Also removing @russellb who has requested to retire.
=> Add @andfasano and @fmuyassarov as approvers

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/updateopts_test.go, pkg/provisioner/ironic/validatemanagementaccess_test.go
Honor DefaultDeployInterface value from Ironic config.
=> Honor DefaultDeployInterface value from Ironic config

docs/dev-setup.md
=> 📖 Update old branch name mention in docs

tools/run_local_ironic.sh
=> Fix outdated URL in run_local_ironic

.dockerignore, PROJECT, apis/metal3.io/v1alpha1/baremetalhost_types.go, apis/metal3.io/v1alpha1/groupversion_info.go, config/crd/kustomization.yaml, config/crd/kustomizeconfig.yaml, config/crd/patches/cainjection_in_baremetalhosts.yaml, config/crd/patches/webhook_in_baremetalhosts.yaml, config/crd/patches/webhook_in_firmwareschemas.yaml, config/crd/patches/webhook_in_hostfirmwaresettings.yaml, config/crd/patches/webhook_in_preprovisioningimages.yaml, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_config_patch.yaml, config/manager/controller_manager_config.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_client_clusterrole.yaml, config/rbac/auth_proxy_role.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/kustomization.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, config/render/capm3.yaml, hack/manifestlint.sh, hack/unit.sh, main.go
=> Uplift to kubebuilder v3

docs/api.md, pkg/ironic/bmc/access_test.go, pkg/ironic/bmc/ilo4.go
This hardware seems pretty popular still, no reason not to support it.
=> Support ilo4 virtual media

Tiltfile
Fix kustomize binary path in Tiltfile
=> Fix kustomize binary path in Tiltfile

controllers/metal3.io/baremetalhost_controller.go, controllers/metal3.io/baremetalhost_controller_test.go
Fixes https://github.com/metal3-io/baremetal-operator/issues/1053
=> Do not add secret finalizer while deleting a host

docs/api.md
=> update provisioning state info

cmd/make-bm-worker/main.go, cmd/make-bm-worker/templates/templates.go, cmd/make-bm-worker/templates/templates_test.go
* Improve the options of make-bm-worke so that it can generate more detailed yaml
* fix the position of disableCertificateVerification
* add some UT
* add the effective value of boot-mode argument
* fix consumer-namespace in template
=> make-bm-worker: add some options and fix some issues

controllers/metal3.io/hostfirmwaresettings_controller.go
Publish events for all invalid settings, not just the first one found.
=> Publish events for all invalid HostFirmwareSettings

controllers/metal3.io/baremetalhost_controller.go, controllers/metal3.io/baremetalhost_controller_test.go, controllers/metal3.io/metrics.go
=> Add prometheus metric for provisioner not ready

apis/metal3.io/v1alpha1/baremetalhost_validation.go, apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
This patch adds WebHook validation for Hardware RAID to validate the following:
1. ``physicalDisks`` specified without ``controller`` not allowed.
2. ``numberOfPhysicalDisks`` and length of ``physicalDisks`` must be consistent. 
This is in accordance with the WebHook validation outline provided in #855 . The functionality that enables these parameters in ``HardwareRAID`` is available in #1062 
The patch also provides unit test coverage for the validations added into the WebHook.
=> Add physicalDisk and controller WebHook validation for HardwareRAID

Makefile
Provide ability to set flags, for example -build-preprov-image.
=> Allow flags to be set when running bmo

Makefile
These make targets can be used to change the image used for BMO, Ironic,
Mariadb, keepalived and IPA downloader. This is similar to how things work in CAPM3.
The deploy target was removed. It has been broken for at least a year
since the name of the image was changed. I.e. it could apply the
manifests but the image substitution didn't work.
The idea is to unify how image replacement works in CAPM3 and BMO and solve https://github.com/metal3-io/metal3-dev-env/issues/908 by making use of these make targets in metal3-dev-env.
For reference, [this is how the image replacement works in CAPM3](https://github.com/metal3-io/cluster-api-provider-metal3/blob/2d686bf00a7d4babd8287dffc9f8bdabe07c26f2/Makefile#L370-L378).
=> Add make targets for setting images

apis/metal3.io/v1alpha1/baremetalhost_validation.go, apis/metal3.io/v1alpha1/baremetalhost_validation_test.go
This PR adds mac address validation for BootMACAddress if it is not empty.
=> Add mac address validation for BootMACAddress

pkg/provisioner/ironic/ironic.go
Otherwise it's hard to track why maintenance is on.
=> Set maintenance reason when turning maintenance on

docs/api.md, hack/markdownlint.sh
* Specify which driver uses which technology.
* +http and +https are supported for most drivers
=> Clarify documentation on BMC formats

docs/api.md
=> docs/api: Add iRMC default port info

OWNERS
He's been active on BMO recently and has a good working knowledge of
Ironic and its images.
=> Add Riccardo to reviewers

.github/workflows/kubesec.yml, template/sarif.tpl
Kubesec is a security risk analysis tool for Kubernetes manifest files. This PR adds a github action script to BMO so it is scanned by Kubesec weekly.
Github action test result can be seen here: https://github.com/Nordix/baremetal-operator/actions/runs/2155435134
And test security alert can be seen here: https://github.com/Nordix/baremetal-operator/security/code-scanning?query=is%3Aopen+branch%3AAdd-kubesec-nam
=> Add kubesec to BMO

OWNERS
I have contributed some code to the community and review PRs regularly. I would like to be a reviewer.
Here is my contribution:
https://github.com/metal3-io/baremetal-operator/pulls?q=is%3Apr+author%3Azhouhao3+is%3Aclosed
=> Add zhouhao3 to reviewers

pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/raid.go, pkg/provisioner/ironic/raid_test.go
Signed-off-by: Moshe Levi <moshele@nvidia.com>
=> use StepInterface constants

.github/workflows/release.yaml
Missed updating golang in release.yml
=> 🌱 Bump golang 1.19 in release.yml

Dockerfile
Uplift and pin golang 1.19.4 with digest.
=> 🌱 pin golang:1.19.4 with digest

hack/generate.sh, hack/gofmt.sh, hack/golint.sh, hack/gomod.sh, hack/gosec.sh, hack/markdownlint.sh, hack/unit.sh
Use docker.io consistently as image registry, and pin more checks by a version and digest.
=> 🌱 use docker.io consistently, and pin more checks

go.mod, go.sum, pkg/provisioner/ironic/delete_test.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/provision_test.go, pkg/provisioner/ironic/testserver/ironic.go, pkg/provisioner/ironic/updatehardwarestate_test.go
Redo of https://github.com/metal3-io/baremetal-operator/pull/1088
=> 🌱  set maintenance reason when turning maintenance on

SECURITY_CONTACTS
Our user-guide is now properly hosted at https://book.metal3.io/
=> 📖  update user-guide url

pkg/provisioner/ironic/provision_test.go, pkg/provisioner/ironic/testserver/ironic.go
Most of them were not testing what they are supposed to test. The
exposed errors, for example, were due to a misconfigured Validate
mock, not because of actual deployment failures. Clean it up.
=> 🐛 Fix ironic Provision() unit tests

config/rbac/role.yaml, config/render/capm3.yaml, controllers/metal3.io/baremetalhost_controller.go
Without these you get a bunch of "cannot set an ownerRef on a resource you can't delete" errors.
=> Add missing rbac rules for BaremetalHost Controller

CONTRIBUTING.md, docs/releasing.md
BMO branching proposal was approved in community meeting on 2023-06-21 and BMO release process will have release branches going into future. Update the release process document to reflect this.
Also update CONTRIBUTING.md which details some of the same things.
Fixes: #1283
=> 📖 update releasing.md with release branches

apis/go.mod, apis/go.sum, go.mod, go.sum
=> 🌱 Bump controller-runtime to v0.15.2

docs/releasing.md
Fix api -> apis in release artifact checklist.
=> 📖 fix typo in releasing.md

README.md
=> 📖 Add test trigger description for diffrerent branches in README

apis/metal3.io/v1alpha1/baremetalhost_types.go, apis/metal3.io/v1alpha1/profile/profile.go, config/crd/bases/metal3.io_baremetalhosts.yaml, config/render/capm3.yaml
See the design proposal https://github.com/metal3-io/metal3-docs/pull/332
=> ⚠️ Add "empty" profile and officially deprecate hardware profiles

.gitignore
Adding go work files in gitignore, so some do not push it accidentally.
=> 🌱 Adding go work files in gitignore

hack/verify-release.sh
Add `./hack/verify-release.sh` to check if the release process has been completed, and/or regular chores have been done before release. This script has been adapted from the one I wrote for CAPM3.
Another PR(s) will be created to fix the issues identified.
=> 🌱 add verify-release.sh

.github/workflows/pr-verifier.yaml
Adding PR title verifier. This uses https://github.com/kubernetes-sigs/kubebuilder-release-tools and makes sure that the title has an icon added. This will make the release process easier.
=> 🌱 Adding PR title verifier

CONTRIBUTING.md
Updating contributing guide regarding signing off of commits
=> 📖 Commit signing off update.

CONTRIBUTING.md, hack/markdownlint.sh
in addition to adding ci support and branch maintenance section , this PR also fixes a minor issue in markdownlint script
=> 🌱 Add CI support and branch maintenance section

go.mod, go.sum, pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go, pkg/provisioner/ironic/hardwaredetails/hardwaredetails_test.go
They provide the same information in different places.
=> ✨ Support both Ironic and Inspector inventory formats

hack/ci-e2e.sh, test/e2e/basic_ops_test.go, test/e2e/basic_provisioning_test.go, test/e2e/common.go, test/e2e/config/ironic.yaml, test/e2e/external_inspection_test.go, test/e2e/inspection_test.go, test/e2e/live_iso_test.go, test/e2e/re_inspection_test.go
=> 🌱 E2e Add SSH Key-Based Authentication

README.md
Add release-0.5 information to README.md
=> 📖 add release-0.5 to README.md

Dockerfile, Makefile, hack/e2e/ensure_go.sh
=> 🌱 Bump golang to v1.20.14

apis/go.mod, pkg/hardwareutils/bmc/access.go, pkg/hardwareutils/go.mod, pkg/hardwareutils/go.sum
=> 🌱 Drop dependency on pkg/errors from hardwareutils

.github/workflows/build-images-action.yml
It is needed in release branch.
/hold
Until verified with IPAM release to work with tags as well.
=> 🌱 add build images action to release-0.4

.github/workflows/golangci-lint.yml, Makefile
=> 🌱 Bump golangci-lint to v1.56.2

.github/workflows/e2e-fixture-test.yml
Fix e2e fixture test workflow trigger branch.
=> 🌱 fix e2e fixture workflow trigger

Dockerfile, Makefile
=> 🌱 bump golang to 1.21.8

README.md
Update build status on release 0.4
=> 🌱 Update build status for release-0.4

README.md
This PR:
- Update build status badges
- Update test triggers
=> 🌱 Update readme on test triggers on release-0.6

config/base/manager_auth_proxy_patch.yaml, config/render/capm3.yaml
=> 🌱 chore(deps): bump kube-rbac-proxy to v0.16.0

OWNERS
Adding myself as a reviewer for BMO
=> :seedling: Add mquhuy as a reviewer

Dockerfile, Makefile, hack/e2e/ensure_go.sh
https://osv.dev/GO-2024-2824
https://osv.dev/GO-2024-2887
https://osv.dev/GO-2024-2888
=> 🌱 bump golang to 1.22.4

Dockerfile, Makefile, hack/e2e/ensure_go.sh
=> 🌱 bump golang to 1.22.5

Dockerfile, hack/e2e/ensure_go.sh
=> 🌱 bump golang to 1.22.6

.github/dependabot.yml
Add dependabot config for release-0.8 branch.
=> 🌱 add dependabot config for release-0.8 branch

.github/dependabot.yml
Fix dependabot ignore rules for 0.8 branch.
=> 🌱 fix dependabot ignore rules for 0.8 branch

README.md
This PR:
Update build status badges
Update test triggers
=> :book: Update readme on test triggers on release-0.8

Dockerfile, Makefile, hack/e2e/ensure_go.sh
=> 🌱 bump golang to 1.22.7

hack/ci-e2e.sh
This is a workaround for a long existing issue in minikube which we opened long ago but it seems it has not gone away. Here is the issue for more detail https://github.com/kubernetes/minikube/issues/14456
=> 🌱 Fix minikube restart in e2e by trying in a loop

Dockerfile, Makefile, hack/e2e/ensure_go.sh
=> 🌱 bump golang to 1.22.8

OWNERS_ALIASES
Adding @elfosardo and @Rozzii as approvers. Thanks folks for your contributions.
=> 🌱 Add Riccardo and Adam as approvers

controllers/metal3.io/baremetalhost_controller.go
The t in function name appears to be just a simple typo.
=> 🌱 Fix misspelling in function name

.github/workflows/osv-scanner-scan.yml
Add scheduled osv-scanner workflow.
=> :seedling: add scheduled osv-scanner workflow

hack/verify-release.sh
Make use of 'make go-version' rather than parse it from Dockerfile. Cherry-picked from IPAM.
=> :seedling: simplify go version handling in verify-release.sh

README.md
Adds status badges for the e2e tests.
Fixes #
=> 📖 Add e2e status badge to readme

hack/tools/go.mod, hack/tools/go.sum, test/go.mod, test/go.sum
=> 🌱 Bump CAPI to v1.9.1

.github/dependabot.yml
Remove dependabot config for release-0.6 and add releasse-0.9.
=> :seedling: update dependabot config for release-0.9

README.md
**What this PR does / why we need it**: Update README badges and e2e triggers
=> :seedling: Update README badges and e2e triggers

.github/workflows/e2e-test.yml
Save resources in case the test stucks.
Fixes #2189
=> 🐛 Set e2e timeout to 1.5h

hack/tools/go.mod, hack/tools/go.sum, test/go.mod, test/go.sum
**What this PR does / why we need it**: Bump CAPI to 1.9.5
=> :seedling: Bump CAPI to 1.9.5

config/overlays/e2e-release-0.4/ironic.env, ironic-deployment/overlays/e2e-release-24.0-with-inspector/kustomization.yaml, ironic-deployment/overlays/e2e-with-inspector/kustomization.yaml
The overlays for the older releases had some issues with the patches and values after the switch to kind. This fixes that.
Fixes #
/hold
Using a temporary commit to run the optional tests.
=> 🌱 E2E: Fix kustomization for Ironic with inspector

releasenotes/v0.9.1.md
=> :rocket: Release v0.9.1

releasenotes/v0.8.1.md
=> :rocket: Release v0.8.1

OWNERS, OWNERS_ALIASES
@mquhuy is not active as a reviewer in this project anymore. Thanks Huy for all your contributions.
=> 🌱 Move @mquhuy to emeritus reviewers

controllers/metal3.io/baremetalhost_controller.go
The `desiredPowerOnState` for dataImage should be checked before the reboot annotation, so that we can ensure the desired dataImage operations happened in the `powerOff` state before removing the annotation.
=> :bug: Handle dataImage before reboot annotation to prevent annotation removal before all actions are complete

.golangci.yaml, pkg/provisioner/ironic/clients/auth_test.go
Fixes https://github.com/metal3-io/baremetal-operator/issues/2364
=> 🌱 Enable usetesting linter in golangci-lint

hack/tools/release/notes.go
**What this PR does / why we need it**:  When running make release-notes for v0.10.0-beta.0 I encountered a few problems. In addition to "Merge pull request" pattern there was a "Merge commit from fork" pattern. I added this as an if so that notes.go doesn't break if this patter occurs. 
I also changed the order of warning printing so that it matches the order in previous pre-releases.
=> :bug: Fix few errors when making beta release notes

.gitignore, .golangci.yaml, apis/metal3.io/v1alpha1/hostfirmwarecomponents_types_test.go, controllers/metal3.io/baremetalhost_controller_test.go, controllers/metal3.io/host_config_data_test.go, controllers/metal3.io/host_state_machine_test.go, controllers/metal3.io/hostfirmwarecomponents_test.go, controllers/metal3.io/hostfirmwaresettings_test.go, pkg/provisioner/ironic/adopt_test.go, pkg/provisioner/ironic/bios_test.go, pkg/provisioner/ironic/clients/client_test.go, pkg/provisioner/ironic/clients/updateopts_test.go, pkg/provisioner/ironic/configdrive_test.go, pkg/provisioner/ironic/delete_test.go, pkg/provisioner/ironic/factory_test.go, pkg/provisioner/ironic/inspecthardware_test.go, pkg/provisioner/ironic/ironic_test.go, pkg/provisioner/ironic/power_test.go, pkg/provisioner/ironic/prepare_test.go, pkg/provisioner/ironic/provision_test.go, pkg/provisioner/ironic/provisioncapacity_test.go, pkg/provisioner/ironic/ready_test.go, pkg/provisioner/ironic/register_test.go, pkg/provisioner/ironic/servicing_test.go, pkg/provisioner/ironic/updatehardwarestate_test.go
resolves https://github.com/metal3-io/baremetal-operator/issues/2363
=> 🌱 Enable testifylint linter in golangci-lint

.golangci.yaml, cmd/make-bm-worker/templates/templates_test.go, test/e2e/common.go
https://github.com/metal3-io/baremetal-operator/issues/2358
=> 🌱Enable intrange linter in golangci-lint

.github/workflows/release.yaml
Setting GITHUB_TOKEN in workflow env.
Fixes #
=> 🌱 Minor fix release workflow

hack/tools/go.mod, hack/tools/go.sum, test/go.mod, test/go.sum
=> 🌱 Bump CAPI to v1.10.0

releasenotes/v0.10.0.md
Release Notes for v0.10.0 release
=> 🚀 Release v0.10.0

ironic-deployment/base/ironic.yaml
**What this PR does / why we need it**: Pin ironic to version 29.0
=> :seedling: Pin ironic to version 29.0

releasenotes/v0.10.1.md
**What this PR does / why we need it**: Release v0.10.1 (where Ironic is pinned)
=> :rocket: Release v0.10.1

.golangci.yaml, cmd/get-hardware-details/main.go, hack/tools/deploy-cli/deploy-cli.go, internal/controller/metal3.io/action_result.go, internal/controller/metal3.io/host_state_machine.go, main.go, pkg/provisioner/demo/demo.go, pkg/provisioner/fixture/fixture.go, pkg/provisioner/ironic/clients/features.go, pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go, pkg/provisioner/ironic/inspecthardware.go, pkg/provisioner/ironic/ironic.go, pkg/provisioner/ironic/register.go, test/e2e/common.go, test/e2e/e2e_config.go, test/vbmctl/main.go
**What this PR does / why we need it**: This enables the `mnd` linter and fixes the initial issues caused by it.
Fixes #2359 
**Note**: I made some guesses about best `const` names to replace the numbers that `mnd` was complaining about. If there are opinions on more appropriate names, I would be happy to fix them up.
=> 🌱 enable mnd linter

.github/workflows/e2e-test-periodic-release-0.10.yml
Adds periodic jobs for release-0.10 and removes release-0.6
Fixes #
=> 🌱 Update periodic workflows for release-0.10

CONTRIBUTING.md, README.md
**What this PR does / why we need it**: Add release-0.10 triggers to README.md
=> :book: Add release-0.10 triggers to README.md

.golangci.yaml, apis/metal3.io/v1alpha1/baremetalhost_types.go, apis/metal3.io/v1alpha1/firmwareschema_types.go, apis/metal3.io/v1alpha1/preprovisioningimage_types.go, cmd/make-virt-host/main.go, pkg/provisioner/ironic/ironic.go
**What this PR does / why we need it**: Enabled tagliatelle linter
Fixes #2362
=> :seedling: Enable tagliatelle linter

README.md
**What this PR does / why we need it**: Update badges and e2e triggers in README.md
=> :book: Update badges and e2e triggers in README.md

.gitignore, .golangci.yaml, internal/controller/metal3.io/baremetalhost_controller.go, pkg/provisioner/ironic/ironic.go
Enable nilnil linter and fix warnings flagged by it. Add .vscode/ directory to gitignore.
Fixes #2360
=> :seedling: Enable nilnil linter, fix warnings

hack/tools/release/notes.go
Currently release notes are not genrated properly for Alpha release as it does for Beta/RC. This PR adds the fucntionality to generate Alhpa release notes as well.
=> 🌱 Add Alpha release in the release notes generator

.github/workflows/e2e-test.yml
Move to new CNCF Github runners, try nro 2. Previous try at PR #2599 and revertion in PR #2622. 
/hold
Until stable.
=> :seedling: update github runners to oci gh arc runners

.github/workflows/e2e-test-periodic-release-0.11.yml
This commit:
- Add periodic release-0.11 e2e test GH workflows
=> :seedling: Add periodic release-0.11 test
